In [2]:
import numpy as np
import pandas as pd
import plotly.express as px
import seaborn as sns

# Feature Engineering

### Domain Knowledge Features

In [3]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
# Create profit column fro
df['profit'] = (df.total_bill * 0.86) + df.tip
df['profit']

0      15.6214
1      10.5524
2      21.5686
3      23.6748
4      24.7574
        ...
239    30.8858
240    25.3748
241    21.4962
242    17.0752
243    19.1508
Name: profit, Length: 244, dtype: float64

### String Operations

**Get Email Providers**

In [5]:
df = pd.read_csv('Ecommerce Purchases.csv')
df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [8]:
df.Email.str.split('@')

0                    [pdunlap, yahoo.com]
1                   [anthony41, reed.com]
2       [amymiller, morales-harrison.com]
3          [brent16, olson-robinson.info]
4          [christopherwright, gmail.com]
                      ...
9995            [iscott, wade-garner.com]
9996                [mary85, hotmail.com]
9997                 [tyler16, gmail.com]
9998           [elizabethmoore, reid.net]
9999             [rachelford, vaughn.com]
Name: Email, Length: 10000, dtype: object

In [13]:
df.Email.str.split('@').str[1]

0                  yahoo.com
1                   reed.com
2       morales-harrison.com
3        olson-robinson.info
4                  gmail.com
                ...
9995         wade-garner.com
9996             hotmail.com
9997               gmail.com
9998                reid.net
9999              vaughn.com
Name: Email, Length: 10000, dtype: object

In [10]:
df['email_domain'] = df.Email.str.split('@').str[1]
df['email_domain']

0                  yahoo.com
1                   reed.com
2       morales-harrison.com
3        olson-robinson.info
4                  gmail.com
                ...
9995         wade-garner.com
9996             hotmail.com
9997               gmail.com
9998                reid.net
9999              vaughn.com
Name: email_domain, Length: 10000, dtype: object

In [14]:
df.email_domain.value_counts()

email_domain
hotmail.com          1638
yahoo.com            1616
gmail.com            1605
smith.com              42
williams.com           37
                     ...
mclaughlin.net          1
black-powell.com        1
johnson-booth.com       1
farmer.org              1
reed.biz                1
Name: count, Length: 3416, dtype: int64

### Get Browser, OS and Device Info from User Agent
you can use this library to extract information from User Agent Data
https://github.com/selwin/python-user-agents

In [17]:
import user_agents

ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36'

ua = user_agents.parse(ua)

In [ ]:
print('Is a bot? ', ua.is_bot)
print('Is mobile? ', ua.is_mobile)
print('Is PC? ',ua.is_pc)
print('Is Tablet? ',ua.is_tablet)
print('Is Touch Capable? ',ua.is_touch_capable)
print('OS Family: ',ua.os.family)
print('OS Version: ',ua.os.version)
print('Browser Family: ',ua.browser.family)
print('Browser Version: ',ua.browser.version)
print('Device Family: ',ua.device.family)
print('Device Brand: ',ua.device.brand)
print('Device Model: ',ua.device.model)

Is a bot?  False
Is mobile?  False
Is PC?  True
Is Tablet?  False
Is Touch Capable?  False
OS Family:  Windows
OS Version:  (10,)
Browser Family:  Chrome
Browser Version:  (90, 0, 4430)
Device Family:  Other
Device Brand:  None
Device Model:  None

In [19]:
ua.os

OperatingSystem(family='Windows', version=(10,), version_string='10')

In [20]:
# Extract Browser Column

def extract_browser(x):

    x = user_agents.parse(x)
    return x.browser.family

df['browser'] = df['Browser Info'].apply(extract_browser)
df['browser']

0         Opera
1         Opera
2            IE
3        Safari
4         Opera
         ...
9995     Chrome
9996         IE
9997     Safari
9998    Firefox
9999    Firefox
Name: browser, Length: 10000, dtype: object

In [21]:
df.browser.value_counts()

browser
Opera            2076
IE               2052
Chrome           1984
Firefox          1973
Safari           1292
Mobile Safari     623
Name: count, dtype: int64

### Get Location from IP address
you can use this library to extract location information from IP address
https://github.com/tomas-net/ip2geotools

In [22]:
from ip2geotools.databases.noncommercial import DbIpCity as ip2geo

response = ip2geo.get('45.243.72.231', api_key='free')

Status code 403 from https://nominatim.openstreetmap.org/search: ERROR - 403 Client Error: Forbidden for url: https://nominatim.openstreetmap.org/search?q=Port+Said%2C+Port+Said+EG&format=jsonv2&addressdetails=1&limit=1
Status code 403 from https://nominatim.openstreetmap.org/search: ERROR - 403 Client Error: Forbidden for url: https://nominatim.openstreetmap.org/search?q=Port+Said%2C+EG&format=jsonv2&addressdetails=1&limit=1

In [23]:
print(response.city)
print(response.country)
print(response.region)

Port Said
EG
Port Said

In [38]:
ip = '222.21.209.138'

response = ip2geo.get(ip, api_key='free')

Status code 403 from https://nominatim.openstreetmap.org/search: ERROR - 403 Client Error: Forbidden for url: https://nominatim.openstreetmap.org/search?q=Wuhan%2C+Hubei+CN&format=jsonv2&addressdetails=1&limit=1
Status code 403 from https://nominatim.openstreetmap.org/search: ERROR - 403 Client Error: Forbidden for url: https://nominatim.openstreetmap.org/search?q=Wuhan%2C+CN&format=jsonv2&addressdetails=1&limit=1

In [42]:

print(response.country)
print(response.region)
print(response.city)

CN
Hubei
Wuhan

#### To extract City from IP Address, but this code will take long time as the response takes time

In [47]:
# def extract_city(x):

#     response = ip2geo.get(x, api_key='free')
#     return response.city

# df['city'] = df['IP Address'].apply(extract_city)
# df['city']

### 1) Work with Lat and Long

we will use this library: https://pypi.org/project/geopy/

**1) Measuring Distance**

In [43]:
from geopy.distance import great_circle

my_home = (30.109919, 31.308797) # (lat, long)
my_cafe = (30.120982, 31.322026)

In [46]:
round(great_circle(my_home, my_cafe).kilometers, 2)

1.77

In [ ]:
round(great_circle(my_home, my_cafe).meters, 2)

In [51]:
round(great_circle(my_home, my_cafe).miles, 2)

1.1

### 2) Geocoding features to get the address from lat, long or reverse.

we will use this library: https://pypi.org/project/geopy/

In [48]:
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="Data Science course")

In [55]:
location = geolocator.geocode("175 5th Avenue NY")
location.raw

{'place_id': 405659852,
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
 'osm_type': 'way',
 'osm_id': 264768896,
 'lat': '40.7410592',
 'lon': '-73.9896416',
 'class': 'building',
 'type': 'office',
 'place_rank': 30,
 'importance': 9.175936522464359e-05,
 'addresstype': 'building',
 'name': 'Flatiron Building',
 'display_name': 'Flatiron Building, 175, 5th Avenue, Flatiron District, Manhattan Community Board 5, Manhattan, New York County, City of New York, New York, 10010, United States',
 'boundingbox': ['40.7407596', '40.7413004', '-73.9898715', '-73.9895014']}

In [94]:
location = geolocator.geocode("Cairo Festival, Cairo, Egypt")
location.raw

{'place_id': 44327320,
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
 'osm_type': 'node',
 'osm_id': 2570419850,
 'lat': '30.0325130',
 'lon': '31.4129600',
 'class': 'place',
 'type': 'village',
 'place_rank': 19,
 'importance': 0.1746475799110849,
 'addresstype': 'village',
 'name': 'كايرو فستيفال سيتى',
 'display_name': 'كايرو فستيفال سيتى, القاهرة, 11528, مصر',
 'boundingbox': ['30.0125130', '30.0525130', '31.3929600', '31.4329600']}

In [95]:
location.raw['lat'], location.raw['lon']

('30.0325130', '31.4129600')

In [96]:
location = geolocator.reverse("29.981650417493046, 31.428900499194086")
location.raw

{'place_id': 44652783,
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
 'osm_type': 'way',
 'osm_id': 338687680,
 'lat': '29.9817123',
 'lon': '31.4289629',
 'class': 'highway',
 'type': 'residential',
 'place_rank': 26,
 'importance': 0.05341293736171508,
 'addresstype': 'road',
 'name': '',
 'display_name': 'التجمع الثالث, القاهرة, 11936, مصر',
 'address': {'neighbourhood': 'التجمع الثالث',
  'village': 'التجمع الثالث',
  'city': 'القاهرة',
  'state': 'القاهرة',
  'ISO3166-2-lvl4': 'EG-C',
  'postcode': '11936',
  'country': 'مصر',
  'country_code': 'eg'},
 'boundingbox': ['29.9785046', '29.9825297', '31.4280647', '31.4292666']}

In [97]:
location.raw['address']['country']

'مصر'

In [98]:
location.raw['address']['neighbourhood']

'التجمع الثالث'

In [99]:
import folium

m = folium.Map(location=(location.raw['lat'], location.raw['lon']), zoom_start=15)

In [100]:
m = folium.Map(location=(location.raw['lat'], location.raw['lon']), zoom_start=15)

folium.Marker(
    location=(location.raw['lat'], location.raw['lon']),
    tooltip="Click me!",
    popup="YouVerseHub",
    icon=folium.Icon(icon="cloud"),
).add_to(m)

In [101]:
m

# Handling Outliers

## 1) Using datasist library.

In [61]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [62]:
px.box(df, y= 'total_bill')

### Detect Outlier Indices

In [60]:
from datasist.structdata import detect_outliers

outlier_indices = detect_outliers(df, 0, ['total_bill'])
outlier_indices

[59, 102, 142, 156, 170, 182, 184, 197, 212]

### Replace Outlier Indices with the Median

In [102]:
from datasist.structdata import detect_outliers

outlier_indices = detect_outliers(df, 0, ['total_bill'])

Median = df.total_bill.median()

df.total_bill.loc[outlier_indices] = Median

/tmp/ipykernel_11565/452787750.py:7: FutureWarning:

ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


/tmp/ipykernel_11565/452787750.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### You can write the last line of code this way to avoid this warning

In [ ]:
from datasist.structdata import detect_outliers

outlier_indices = detect_outliers(df, 0, ['total_bill'])

Median = df.total_bill.median()

df.loc[outlier_indices, 'totall_bill'] = Median   # This line of code

## 2) Using Custom Function.

In [64]:
def custom_outliers(dataframe, column, lower_bound = 0.1, upper_bound = 0.9):

    # Compute percentile boundaries
    lower_threshold = dataframe[column].quantile(lower_bound)
    upper_threshold = dataframe[column].quantile(upper_bound)

    # Find outlier indices
    outlier_indices = df[(dataframe[column] < lower_threshold) | (dataframe[column] > upper_threshold)].index
    return outlier_indices

In [65]:
# Detect outliers lower than 20% value or higher than 80% value
custom_outliers(dataframe= df, column= 'total_bill', lower_bound= 0.2, upper_bound= 0.8)

Index([  1,   4,   5,   6,   7,  10,  11,  16,  23,  30,  39,  43,  44,  47,
        48,  50,  51,  52,  53,  54,  56,  57,  58,  62,  67,  70,  72,  73,
        75,  77,  82,  83,  85,  88,  90,  92,  95,  96,  97,  99, 100, 107,
       111, 112, 114, 116, 117, 118, 120, 124, 125, 126, 128, 132, 133, 135,
       136, 141, 143, 145, 147, 148, 149, 155, 157, 167, 168, 169, 172, 173,
       175, 178, 179, 180, 187, 192, 195, 196, 206, 207, 210, 211, 214, 216,
       217, 218, 219, 220, 222, 226, 232, 233, 235, 236, 237, 238, 239, 240],
      dtype='int64')

In [66]:
# Detect outliers lower than 10% value or higher than 90% value
custom_outliers(dataframe= df, column= 'total_bill', lower_bound= 0.1, upper_bound= 0.9)

Index([  6,  10,  11,  16,  23,  30,  39,  43,  44,  47,  51,  52,  53,  56,
        67,  82,  83,  85,  92,  95, 111, 112, 116, 126, 135, 136, 141, 145,
       148, 149, 155, 167, 172, 173, 175, 178, 179, 180, 187, 195, 207, 210,
       218, 219, 222, 226, 235, 237, 238],
      dtype='int64')