### Import Necessary Libraries

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

# Load Dataset

In [2]:
df = pd.read_csv('DataAnalyst.csv', index_col= 0)
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True

# Data Exploration

In [3]:
# Check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2253 entries, 0 to 2252
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          2253 non-null   object
 1   Salary Estimate    2253 non-null   object
 2   Job Description    2253 non-null   object
 3   Rating             2253 non-null   float64
 4   Company Name       2252 non-null   object
 5   Location           2253 non-null   object
 6   Headquarters       2253 non-null   object
 7   Size               2253 non-null   object
 8   Founded            2253 non-null   int64
 9   Type of ownership  2253 non-null   object
 10  Industry           2253 non-null   object
 11  Sector             2253 non-null   object
 12  Revenue            2253 non-null   object
 13  Competitors        2253 non-null   object
 14  Easy Apply         2253 non-null   object
dtypes: float64(1), int64(1), object(13)
memory usage: 281.6+ KB

In [4]:
# Check summary statistics for Numerical
df.describe().round(2)

        Rating  Founded
count  2253.00  2253.00
mean      3.16  1398.52
std       1.67   901.93
min      -1.00    -1.00
25%       3.10    -1.00
50%       3.60  1979.00
75%       4.00  2002.00
max       5.00  2019.00

In [5]:
# Check summary statistics for Categorical
df.describe(include= 'object').T

,count,unique,top,freq
Job Title,2253,1272,Data Analyst,405
Salary Estimate,2253,90,$41K-$78K (Glassdoor est.),57
Job Description,2253,2253,"You.\n\nYou bring your body, mind, heart and s...",1
Company Name,2252,1513,"Staffigo Technical Services, LLC\n5.0",58
Location,2253,253,"New York, NY",310
Headquarters,2253,483,"New York, NY",206
Size,2253,9,51 to 200 employees,421
Type of ownership,2253,15,Company - Private,1273
Industry,2253,89,-1,353
Sector,2253,25,Information Technology,570
Revenue,2253,14,Unknown / Non-Applicable,615
Competitors,2253,291,-1,1732
Easy Apply,2253,2,-1,2173

In [6]:
# Check duplicates
df.duplicated().sum()

np.int64(0)

In [7]:
# Check Missing Values
df.isna().sum()

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         1
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
Easy Apply           0
dtype: int64

In [8]:
# Check Missing Values
df.isna().mean() * 100

Job Title            0.000000
Salary Estimate      0.000000
Job Description      0.000000
Rating               0.000000
Company Name         0.044385
Location             0.000000
Headquarters         0.000000
Size                 0.000000
Founded              0.000000
Type of ownership    0.000000
Industry             0.000000
Sector               0.000000
Revenue              0.000000
Competitors          0.000000
Easy Apply           0.000000
dtype: float64

# Data Cleaning

In [9]:
df.dropna(inplace= True, ignore_index= True)

In [10]:
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),Maintains systems to protect data from unautho...,2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,-1,-1
2248,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),Position:\nSenior Data Analyst (Corporate Audi...,2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",-1
2249,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),"Title: Technical Business Analyst (SQL, Data a...",-1.0,Spiceorb,"Denver, CO",-1,-1,-1,-1,-1,-1,-1,-1,-1
2250,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),Summary\n\nResponsible for working cross-funct...,3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),-1,-1
2251,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),"You.\n\nYou bring your body, mind, heart and s...",3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",-1

In [ ]:
# THIS will replace -1 and '-1' with NaN
df = df.replace('-1', np.nan).replace(-1, np.nan)
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961.0,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),NaN,True
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893.0,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),NaN,NaN
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003.0,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,NaN
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002.0,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),NaN,NaN
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009.0,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,RQS - IHHA - 201900004460 -1q Data Security An...,$78K-$104K (Glassdoor est.),Maintains systems to protect data from unautho...,2.5,"Avacend, Inc.\n2.5","Denver, CO","Alpharetta, GA",51 to 200 employees,NaN,Company - Private,Staffing & Outsourcing,Business Services,Unknown / Non-Applicable,NaN,NaN
2248,Senior Data Analyst (Corporate Audit),$78K-$104K (Glassdoor est.),Position:\nSenior Data Analyst (Corporate Audi...,2.9,Arrow Electronics\n2.9,"Centennial, CO","Centennial, CO",10000+ employees,1935.0,Company - Public,Wholesale,Business Services,$10+ billion (USD),"Avnet, Ingram Micro, Tech Data",NaN
2249,"Technical Business Analyst (SQL, Data analytic...",$78K-$104K (Glassdoor est.),"Title: Technical Business Analyst (SQL, Data a...",NaN,Spiceorb,"Denver, CO",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2250,"Data Analyst 3, Customer Experience",$78K-$104K (Glassdoor est.),Summary\n\nResponsible for working cross-funct...,3.1,Contingent Network Services\n3.1,"Centennial, CO","West Chester, OH",201 to 500 employees,1984.0,Company - Private,Enterprise Software & Network Solutions,Information Technology,$25 to $50 million (USD),NaN,NaN
2251,Senior Quality Data Analyst,$78K-$104K (Glassdoor est.),"You.\n\nYou bring your body, mind, heart and s...",3.4,SCL Health\n3.4,"Broomfield, CO","Broomfield, CO",10000+ employees,1864.0,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),"Centura Health, HealthONE, Denver Health and H...",NaN

In [12]:
df.isna().sum()

Job Title               0
Salary Estimate         1
Job Description         0
Rating                271
Company Name            0
Location                0
Headquarters          171
Size                  162
Founded               659
Type of ownership     162
Industry              352
Sector                352
Revenue               162
Competitors          1731
Easy Apply           2172
dtype: int64

In [13]:
df.isna().mean().round(4) * 100

Job Title             0.00
Salary Estimate       0.04
Job Description       0.00
Rating               12.03
Company Name          0.00
Location              0.00
Headquarters          7.59
Size                  7.19
Founded              29.26
Type of ownership     7.19
Industry             15.63
Sector               15.63
Revenue               7.19
Competitors          76.87
Easy Apply           96.45
dtype: float64

In [15]:
df.dropna(subset= ['Salary Estimate'], inplace= True, ignore_index= True)

In [ ]:
# drop the 'Competitors' and 'Easy Apply' columns becouse the null values in these columns above 40%
df.drop(['Competitors', 'Easy Apply'], axis= 1, inplace= True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
cat_cols = df.select_dtypes(include= 'object').columns
cat_cols

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Company Name',
       'Location', 'Headquarters', 'Size', 'Type of ownership', 'Industry',
       'Sector', 'Revenue', 'Competitors', 'Easy Apply'],
      dtype='object')

In [16]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('\n', '-' * 100, '\n')

Job Title
1272
['Data Analyst, Center on Immigration and Justice (CIJ)'
 'Quality Data Analyst'
 'Senior Data Analyst, Insights & Analytics Team [Customer Operations]'
 ... 'Senior Data Analyst (Corporate Audit)'
 'Technical Business Analyst (SQL, Data analytics, ETL)'
 'Senior Quality Data Analyst']

 ----------------------------------------------------------------------------------------------------

Salary Estimate
89
['$37K-$66K (Glassdoor est.)' '$46K-$87K (Glassdoor est.)'
 '$51K-$88K (Glassdoor est.)' '$51K-$87K (Glassdoor est.)'
 '$59K-$85K (Glassdoor est.)' '$43K-$76K (Glassdoor est.)'
 '$60K-$110K (Glassdoor est.)' '$41K-$78K (Glassdoor est.)'
 '$45K-$88K (Glassdoor est.)' '$73K-$127K (Glassdoor est.)'
 '$84K-$90K (Glassdoor est.)' '$27K-$52K (Glassdoor est.)'
 '$42K-$74K (Glassdoor est.)' '$77K-$132K (Glassdoor est.)'
 '$98K-$114K (Glassdoor est.)' '$48K-$96K (Glassdoor est.)'
 '$26K-$47K (Glassdoor est.)' '$31K-$59K (Glassdoor est.)'
 '$47K-$81K (Glassdoor est.)' '$43K-$69K (Glassdoor est.)'
 '$49K-$112K (Glassdoor est.)' '$30K-$54K (Glassdoor est.)'
 '$55K-$103K (Glassdoor est.)' '$37K-$70K (Glassdoor est.)'
 '$57K-$103K (Glassdoor est.)' '$35K-$45K (Glassdoor est.)'
 '$42K-$66K (Glassdoor est.)' '$65K-$81K (Glassdoor est.)'
 '$113K-$132K (Glassdoor est.)' '$42K-$63K (Glassdoor est.)'
 '$60K-$66K (Glassdoor est.)' '$73K-$82K (Glassdoor est.)'
 '$67K-$92K (Glassdoor est.)' '$42K-$76K (Glassdoor est.)'
 '$97K-$129K (Glassdoor est.)' '$68K-$87K (Glassdoor est.)'
 '$29K-$38K (Glassdoor est.)' '$47K-$76K (Glassdoor est.)'
 '$74K-$123K (Glassdoor est.)' '$53K-$94K (Glassdoor est.)'
 '$46K-$102K (Glassdoor est.)' '$43K-$94K (Glassdoor est.)'
 '$45K-$78K (Glassdoor est.)' '$38K-$68K (Glassdoor est.)'
 '$37K-$44K (Glassdoor est.)' '$64K-$113K (Glassdoor est.)'
 '$50K-$93K (Glassdoor est.)' '$37K-$68K (Glassdoor est.)'
 '$73K-$89K (Glassdoor est.)' '$76K-$122K (Glassdoor est.)'
 '$60K-$124K (Glassdoor est.)' '$34K-$61K (Glassdoor est.)'
 '$24K-$48K (Glassdoor est.)' '$30K-$53K (Glassdoor est.)'
 '$41K-$86K (Glassdoor est.)' '$44K-$82K (Glassdoor est.)'
 '$48K-$88K (Glassdoor est.)' '$44K-$78K (Glassdoor est.)'
 '$110K-$190K (Glassdoor est.)' '$89K-$151K (Glassdoor est.)'
 '$69K-$127K (Glassdoor est.)' '$51K-$93K (Glassdoor est.)'
 '$58K-$93K (Glassdoor est.)' '$63K-$116K (Glassdoor est.)'
 '$53K-$104K (Glassdoor est.)' '$35K-$42K (Glassdoor est.)'
 '$43K-$77K (Glassdoor est.)' '$40K-$72K (Glassdoor est.)'
 '$50K-$86K (Glassdoor est.)' '$35K-$67K (Glassdoor est.)'
 '$57K-$70K (Glassdoor est.)' '$28K-$52K (Glassdoor est.)'
 '$46K-$86K (Glassdoor est.)' '$54K-$75K (Glassdoor est.)'
 '$53K-$99K (Glassdoor est.)' '$40K-$74K (Glassdoor est.)'
 '$57K-$104K (Glassdoor est.)' '$99K-$178K (Glassdoor est.)'
 '$93K-$159K (Glassdoor est.)' '$82K-$116K (Glassdoor est.)'
 '$65K-$120K (Glassdoor est.)' '$47K-$74K (Glassdoor est.)'
 '$55K-$101K (Glassdoor est.)' nan '$32K-$56K (Glassdoor est.)'
 '$36K-$67K (Glassdoor est.)' '$57K-$67K (Glassdoor est.)'
 '$49K-$91K (Glassdoor est.)' '$57K-$100K (Glassdoor est.)'
 '$78K-$104K (Glassdoor est.)']

 ----------------------------------------------------------------------------------------------------

Job Description
2252
["Are you eager to roll up your sleeves and harness data to drive policy change? Do you enjoy sifting through complex datasets to illuminate trends and insights? Do you see yourself working for a values-driven organization with a vision to tackle the most pressing injustices of our day?\n\nWe are looking to hire a bright, hard-working, and creative individual with strong data management skills and a demonstrated commitment to immigrant's rights. The Data Analyst will assist with analysis and reporting needs for Veras Center on Immigration and Justice (CIJ), working across its current projects and future Vera initiatives.\n\nWho we are:\n\nFounded in 1961, The Vera Institute is an independent, non-partisan, nonprofit organization that combines expertise in research, technical assistance, and demonstration projects to assist leaders in government and civil society examine justice policy and practice, and improve the systems people rely on for justice and safety.\nWe study problems that impede human dignity and justice.\nWe pilot solutions that are at once transformative and achievable.\nWe engage diverse communities in informed debate.\nAnd we harness the power of evidence to drive effective policy and practice\nWhat were doing:\n\nWe are helping to build a movementamong government leaders, advocates, and the immigration legal services communitytowards universal legal representation for immigrants facing deportation. In the face of stepped-up immigration enforcement, millions of non-citizens are at risk of extended detention and permanent separation from their families and communities. Veras Center on Immigration and Justice (CIJ) partners with government, non-profit partners, and communities to improve government systems that affect immigrants and their families. CIJ administers several nationwide legal services programs for immigrants facing deportation, develops and implements pilot programs, provides technical assistance, and conducts independent research and evaluation.\n\nThats where you come in:\nThe Data Analyst will support the Centers programmatic efforts through regular monitoring and reporting of federal government and subcontractor data. CIJ manages several proprietary databases that run on AWS and Caspio and uses SQL, R, and Python to manage data. This is an opportunity to help shape an innovative national research and policy agenda as part of a dedicated team of experts working to improve access to justice for non-citizens.\n\nVera seeks to hire a Data Analyst to work on various data management projects with its Center on Immigration and Justice (CIJ). In collaboration with other Data Analysts, this position will involve work across several projects, such as the Unaccompanied Childrens Program (UCP), a program to increase legal representation for immigrant children facing deportation without a parent or legal guardian. The position may cover additional duties for the Legal Orientation Program for Custodians (LOPC), which educates the custodians of unaccompanied children about their rights and the immigration court process.\n\nAbout the role:\n\nAs a Data Analyst, you will report to a member of the research team and work in close collaboration with other Vera staff on ongoing database management, monitoring, reporting, and analysis projects. Youll support the team by taking ownership of ongoing monitoring and reporting tasks involving large data sets. Other principal responsibilities will include:\nSupporting research staff by preparing large datasets for analysis, including merging, cleaning, and recoding data;\nProviding insights into program performance through summary statistics and performance indicators;\nProducing timely reports on Vera projects for team members and stakeholders;\nImproving recurring reporting processes by optimizing code and producing subsequent documentation;\nCoordinating database management tasks such as participating in new database design, modifying existing databases, and communicating with outside engineers and subcontractors;\nDeveloping codebooks and delivering user trainings through webinars and database guides;\nBuilding and maintaining interactive dashboards;\nDocumenting and correcting data quality issues;\nWorking with supervisors to prioritize program needs;\nAssisting on other projects and tasks as assigned.\nAbout you:\n\nYoure committed to improving issues affecting immigrants in the United States. Applicants with personal experiences with the immigration system are especially encouraged to apply.\n\nYoure just getting started in your career and have 1 2 years of professional or internship experience working with large datasets and preparing data for analysis.\n\nYou have a real enthusiasm for working with data.\n\nYou are comfortable writing queries in SQL, R, and/or Python, or have a solid foundation coding in other programming languages used to manipulate data. Experience working collaboratively using tools like Git/GitHub is a plus.\n\nYou have exceptional attention to detail, strong problem-solving ability and logical reasoning skills, and the ability to detect anomalies in data.\n\nYoure able to work on multiple projects effectively and efficiently, both independently and collaboratively with a team.\n\nThis position involves working with secure data that may require government security clearance. That clearance is restricted to U.S. citizens and citizens of countries that are party to collective defense agreements with the U.S. The list of those countries is detailed on this webpage. An additional requirement of that clearance is residence in the United States for at least three of the last five years.\n\nHow to apply:\n\nPlease submit cover letter and resume. Applications will be considered on a rolling basis until position is filled. Online submission in PDF format is preferred. Applications with no cover letter attached will not be considered. The cover letter should address your interest in CIJ and this position.\n\nHowever, if necessary, materials may be mailed or faxed to\n\nATTN: Human Resources / CIJ Data Analyst Recruitment\n\nVera Institute of Justice\n\n34 35th St, Suite 4-2A\n\nBrooklyn, NY 11232\n\nFax: (212) 941-9407\n\nPlease use only one method (online, mail or fax) of submission.\n\nNo phone calls, please. Only applicants selected for interviews will be contacted.\n\nVera is an equal opportunity/affirmative action employer. All qualified applicants will be considered for employment without unlawful discrimination based on race, color, creed, national origin, sex, age, disability, marital status, sexual orientation, military status, prior record of arrest or conviction, citizenship status, current employment status, or caregiver status.\n\nVera works to advance justice, particularly racial justice, in an increasingly multicultural country and globally connected world. We value diverse experiences, including with regard to educational background and justice system contact, and depend on a diverse staff to carry out our mission.\n\nFor more information about Vera and CIJs work, please visit www.vera.org.\n\nPowered by JazzHR"
 'Overview\n\nProvides analytical and technical support for the integration of multiple data sources used to prepare internal and external reporting for the Quality Management team and business stakeholders. Provides support and analytical insight for Quality Incentive measures, HEDIS measures, and Quality Improvement initiatives. Monitors, analyzes, and communicates Quality performance related to benchmarks. Collaborates with clinical and operational teams within Quality Management, as well as with CHOICE Clinical Operations and Business Intelligence & Analytics (BIA). Participates in data validation of current reporting and dashboards. Monitors data integrity of databases and provides recommendation accordingly. Participates in the development of internal dashboards and databases. Works under general direction.\n\nResponsibilities\nProvides support and analytical insight for Quality Incentive measures, HEDIS measures, and Quality Improvement initiatives.\nMonitors internal performance against benchmarks through analysis.\nParticipates in the identification, development, management, and monitoring of quality improvement initiatives.\nCollaborates with Education staff and makes recommendations for areas of focus in training of assessors and care managers, based on analysis of performance trends.\nResearches and identifies technical/operational problems surrounding systems/applications; communicates/refers complex and unresolved problems to management, Business Intelligence & Analytics (BIA), and/or IT.\nConducts ad hoc analyses to help identify operational gaps in care; drafts presentations, reports, publications, etc. regarding results of analyses.\nCommunicates results of data analysis to non-technical audiences.\nParticipates in prioritization of departmental goals based on identification of operational gaps in care.\nParticipates in establishing data quality specifications and designs. Coordinates and supports integrated data systems for analyzing and validating information.\nIdentifies and makes recommendations for reporting re-designs and platforms for reporting (e.g. automating a manual Excel file using macros, developing a MicroStrategy dashboard to replace manually updated Excel dashboards, moving data storage from Excel to Access, etc.), as needed. Trains staff on use of new/updated systems and related topics.\nAssists Quality management team with database and department reports. Conducts operations review and analysis of processes and procedures, issues report of findings and implements approved changes as required.\nIdentifies and recommends software needs and applications to accomplish required reporting.\nRetrieves, compiles, reviews and ensures accuracy of data from databases; researches and corrects discrepancies, as needed. Analyzes data from internal and external sources. Identifies and resolves data quality issues before reports are generated. Works with staff to correct data entry errors.\nAnalyzes data, identifies trends, reoccurring problems, statistically significant findings and prepares reports/summaries for management review.\nActs as a liaison between Quality Management, CHOICE Clinical Operations, and BIA.\nReviews and identifies trends and variances in data and reports. Researches findings and determines appropriateness of elevating identified issues to leadership for further review/evaluation/action.\nMonitors and maintains files by ensuring that files are current and of relevant nature.\nAnalyzes and corrects error reports to ensure timely and accurate data; develops corrective actions to prevent errors where possible.\nParticipates in special projects and performs other duties, as needed.\nQualifications\nEducation: Bachelors degree in bio/statistics, epidemiology, mathematics, computer science, social sciences, a related field or the equivalent work experience required. Masters degree with concentration in computer science, data science, or statistics preferred.\n\n\nExperience: Minimum of two years experience performing increasingly complex data analysis and interpretation, preferably in a managed care or health care setting, required. Experience with data extraction and manipulation required. Experience with relational databases and programming experience in SQL or PL/SQL required. Experience with claims data and health plan quality metrics (e.g., HEDIS, QARR) preferred. Proficiency conducting statistical analysis with R, SAS, Stata or other statistical software preferred. Advanced personal computer skills, including Microsoft Word, PowerPoint, Excel, and Access required. Effective oral, written communication and interpersonal skills required. Ability to multi task in a fast-paced environment required.\n\nCA2020'
 'We’re looking for a Senior Data Analyst who has a love of mentorship, data visualization, and generating actionable insights from raw data. In this role, you’ll have the opportunity to be an organizational influencer, who will generate insights with a good degree of autonomy, and partner with data science to grow deeper analytical skills. You will be joining the Insights & Analytics team, a team tasked with developing insights and reporting to support our customers and advisors’ needs. This team sits within the Customer Operations team, but is also connected to the Product organization.\n\nIn this role, you will work mainly with Customer Operations stakeholders to set KPIs and evaluate the effectiveness of current strategies and workflows. You will be involved in many aspects of data operations, from data auditing to building dashboards and analytical insights. For example, you will review the code of more junior analysts and organize coding workshops. You will build metrics to evaluate the performance of our advisors, eliminating confounding variables and creating weighted measures that account for individual success. You will define metrics and create dashboards to track the success of the current strategic direction. You will analyze the text-based interactions with our advisors to improve care quality. You will also analyze interactions with our chatbot to improve the responses of the bot to match customer expectations. You will collaborate with the Data Engineering team in pursuit of better data modeling and you can collaborate with the Data Science team on more modeling-heavy pursuits, like topic modeling or search recommendations. You will be a mentor to all other members of the analytics team, which demands that you excel in a culture of teaching and learning.\n\nYou will report to the Manager of the Insights & Analytics team, Customer Operations in Squarespace’s New York offices.\n\nRESPONSIBILITIES\nDesign and develop KPIs, reports, and dashboards using BI/data visualization tools that clearly track the effectiveness of current strategies\nExecute and communicate impactful analyses, using SQL and R/Python to improve the customer experience and drive Customer Operations and Product roadmap\nRaise the skill level of the analytics team through reviewing code, organizing training sessions, acting as a mentor, and introducing new analytical methods and tools\nHelp design and evaluate experiments and pilots, setting clear hypotheses and success metrics, as well as using the right statistical methods for analyses\nEffectively partner with Customer Operations and Product stakeholders, as well as our Data Engineering team\nQUALIFICATIONS\n4 or more years of experience as a data analyst, data scientist, or in a relevant field in which you have worked with large datasets to transform data to meaningful insights\nMastery of SQL, and experience with R/Python\nExperience with dashboarding/BI tools like Chartio, Looker, Tableau\nExperience with data cleaning, analysis, and presentation to non-technical stakeholders\nBachelor’s degree in a quantitative or logic-driven discipline\nIntellectual curiosity and a deep love of mentorship and generating actionable insights\nPreferred: Advanced degree (Master’s or PhD) in quantitative field\nPreferred: Experience with topic modeling, text analytics/natural language processing\nWe are hiring at various experience levels and we’re particularly interested in having a diverse team with a broad set of skills and viewpoints. If this seems like an opportunity you’d like to explore, but you’re not sure if you qualify, we encourage you to apply anyway!\n\nAbout Squarespace\n\nSquarespace makes beautiful products to help people with creative ideas succeed. By blending elegant design and sophisticated engineering, we empower millions of people — from individuals and local artists to entrepreneurs shaping the world’s most iconic businesses — to share their stories with the world. Squarespace’s team of more than 900 is headquartered in downtown New York City, with offices in Dublin and Portland. For more information, visit www.squarespace.com/about.\n\nToday, more than a million people around the globe use Squarespace to share different perspectives and experiences with the world. Not only do we embrace and celebrate the diversity of our customer base, but we also strive for the same in our employees. At Squarespace, we are committed to equal employment opportunity regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender, gender identity or expression, or veteran status. We are proud to be an equal opportunity workplace.'
 ...

In [19]:
with open('cat_cols.txt','w') as f:
    for col in cat_cols:
        f.write(f"{col}\n")
        f.write(f"Unique values: {df[col].nunique()}\n")
        f.write(f"Values:\n {df[col].unique()}\n")
        f.write('\n' + '-*' * 100 + '\n')

In [20]:
'Vera Institute of Justice\n3.2'.split("\n")[0]

'Vera Institute of Justice'

In [21]:
df['Company Name']= df['Company Name'].str.split("\n").str[0]
df['Company Name']

0                Vera Institute of Justice
1       Visiting Nurse Service of New York
2                              Squarespace
3                                 Celerity
4                                  FanDuel
                       ...
2246                         Avacend, Inc.
2247                     Arrow Electronics
2248                              Spiceorb
2249           Contingent Network Services
2250                            SCL Health
Name: Company Name, Length: 2251, dtype: object

In [22]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice,"New York, NY","New York, NY",201 to 500 employees,1961.0,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD)
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York,"New York, NY","New York, NY",10000+ employees,1893.0,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD)
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace,"New York, NY","New York, NY",1001 to 5000 employees,2003.0,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity,"New York, NY","McLean, VA",201 to 500 employees,2002.0,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD)
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel,"New York, NY","New York, NY",501 to 1000 employees,2009.0,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD)

In [20]:
df['min_salary'] = (df['Salary Estimate'].str.split('-').str[0].str[1:3] + '000').astype(float)
df['min_salary']

0       37000.0
1       37000.0
2       37000.0
3       37000.0
4       37000.0
         ...
2247    78000.0
2248    78000.0
2249    78000.0
2250    78000.0
2251    78000.0
Name: min_salary, Length: 2252, dtype: float64

In [21]:
df['max_salary'] = (df['Salary Estimate'].str.split('-').str[1].str.split().str[0].str[1:3] + '000').astype(float)
df['max_salary']

0       66000.0
1       66000.0
2       66000.0
3       66000.0
4       66000.0
         ...
2247    10000.0
2248    10000.0
2249    10000.0
2250    10000.0
2251    10000.0
Name: max_salary, Length: 2252, dtype: float64

In [22]:
df['avg_salary'] = (df.min_salary + df.max_salary) / 2
df['avg_salary']

0       51500.0
1       51500.0
2       51500.0
3       51500.0
4       51500.0
         ...
2247    44000.0
2248    44000.0
2249    44000.0
2250    44000.0
2251    44000.0
Name: avg_salary, Length: 2252, dtype: float64