### Import Necessary Libraries

In [14]:
import numpy as np
import pandas as pd
import plotly.express as px

### Load Data

In [15]:
df = pd.read_csv('ecommerce.csv')
df

,InvoiceNo,UnitPrice,OrderValue,Quantit,Country,InvoiceDate,InvoiceTime,Year-Month,Major Category,Minor Category,Description
0,549185,0.85,10.20,12,United Kingdom,7/4/11,09:35,2011-04,Clothes,Tops,PACK OF 20 NAPKINS PANTRY DESIGN
1,576381,2.95,35.40,12,United Kingdom,15/11/11,09:26,2011-11,Clothes,Shoes,NATURAL SLATE HEART CHALKBOARD
2,551192,1.25,20.00,16,United Kingdom,27/4/11,10:54,2011-04,Kitchen,Cutlery,36 PENCILS TUBE SKULLS
3,573553,7.46,7.46,1,United Kingdom,31/10/11,13:48,2011-10,Garden,Turf,SET 6 SCHOOL MILK BOTTLES IN CRATE
4,539436,2.51,2.51,1,United Kingdom,17/12/10,14:49,2010-12,Garden,Hoses,FINE WICKER HEART
...,...,...,...,...,...,...,...,...,...,...,...
695,564087,1.25,20.00,16,Hong Kong,23/8/11,09:38,2011-08,Clothes,Tops,WOOD STAMP SET THANK YOU
696,553148,0.55,13.20,24,Hong Kong,13/5/11,14:09,2011-05,Garden,Hoses,GREEN POLKADOT BOWL
697,564087,4.95,29.70,6,Hong Kong,23/8/11,09:38,2011-08,Garden,Rakes,TOY TIDY SPACEBOY
698,553148,0.85,27.20,32,Hong Kong,13/5/11,14:09,2011-05,Kitchen,Cooking Knives,RED RETROSPOT CHILDRENS UMBRELLA
699,564087,1.25,20.00,16,Hong Kong,23/8/11,09:38,2011-08,Clothes,Tops,PACK OF 60 SPACEBOY CAK

In [16]:
df.head()

,InvoiceNo,UnitPrice,OrderValue,Quantit,Country,InvoiceDate,InvoiceTime,Year-Month,Major Category,Minor Category,Description
0,549185,0.85,10.20,12,United Kingdom,7/4/11,09:35,2011-04,Clothes,Tops,PACK OF 20 NAPKINS PANTRY DESIGN
1,576381,2.95,35.40,12,United Kingdom,15/11/11,09:26,2011-11,Clothes,Shoes,NATURAL SLATE HEART CHALKBOARD
2,551192,1.25,20.00,16,United Kingdom,27/4/11,10:54,2011-04,Kitchen,Cutlery,36 PENCILS TUBE SKULLS
3,573553,7.46,7.46,1,United Kingdom,31/10/11,13:48,2011-10,Garden,Turf,SET 6 SCHOOL MILK BOTTLES IN CRATE
4,539436,2.51,2.51,1,United Kingdom,17/12/10,14:49,2010-12,Garden,Hoses,FINE WICKER HEART

### Data Overview

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   InvoiceNo       700 non-null    int64
 1   UnitPrice       700 non-null    float64
 2   OrderValue      700 non-null    float64
 3   Quantit         700 non-null    int64
 4   Country         700 non-null    object
 5    InvoiceDate    700 non-null    object
 6   InvoiceTime     700 non-null    object
 7   Year-Month      700 non-null    object
 8   Major Category  700 non-null    object
 9   Minor Category  700 non-null    object
 10  Description     700 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 60.3+ KB

In [19]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['invoiceno', 'unitprice', 'ordervalue', 'quantit', 'country',
       'invoicedate', 'invoicetime', 'year-month', 'major_category',
       'minor_category', 'description'],
      dtype='object')

In [21]:
# Check summary statistics for numerical columns

df.describe()

           invoiceno   unitprice  ordervalue      quantit
count     700.000000  700.000000  700.000000   700.000000
mean   559180.801429    3.367086   31.978471    20.865714
std     13246.185339    8.280695   63.658083    63.867322
min    536370.000000    0.120000    0.290000     1.000000
25%    547501.000000    1.250000    8.290000     3.000000
50%    559327.500000    1.950000   15.600000     8.000000
75%    570672.000000    3.750000   25.272500    16.000000
max    581587.000000  202.420000  633.600000  1152.000000

In [28]:
px.histogram(df, x='unitprice', nbins=50, title='Price Distribution')

In [34]:
# Check summary statistics for numerical columns

df.describe(include= 'object')

,country,invoicedate,invoicetime,year-month,major_category,minor_category,description
count,700,700,700,700,700,700,700
unique,5,240,341,13,4,17,398
top,United Kingdom,13/5/11,14:09,2011-11,Garden,Tops,POSTAGE
freq,300,17,20,106,189,63,11

In [33]:
df['country'].unique()

array(['United Kingdom   ', '       Germany   ', '        France   ',
       '     Australia   ', '     Hong Kong   '], dtype=object)

In [8]:
# Check Missing values

df.isna().sum()

invoiceno         0
unitprice         0
ordervalue        0
quantit           0
country           0
invoicedate       0
invoicetime       0
year-month        0
major_category    0
minor_category    0
description       0
dtype: int64

In [35]:
df.isna().mean()

invoiceno         0.0
unitprice         0.0
ordervalue        0.0
quantit           0.0
country           0.0
invoicedate       0.0
invoicetime       0.0
year-month        0.0
major_category    0.0
minor_category    0.0
description       0.0
dtype: float64

In [37]:
# Check duplicates

# df.duplicated().sum()
print(f"Number of duplicates: {df.duplicated().sum()}")

Number of duplicates: 0

### Data Cleaning

In [43]:
df.shape[0]

700

In [38]:
cat_cols = df.select_dtypes(include= 'object').columns
cat_cols

Index(['country', 'invoicedate', 'invoicetime', 'year-month', 'major_category',
       'minor_category', 'description'],
      dtype='object')

In [11]:
for col in cat_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique(), '\n')

country
5
['United Kingdom   ' '       Germany   ' '        France   '
 '     Australia   ' '     Hong Kong   ']

invoicedate
240
['   7/4/11   ' ' 15/11/11   ' '  27/4/11   ' ' 31/10/11   '
 ' 17/12/10   ' '  6/12/11   ' '  26/9/11   ' '  12/5/11   '
 '  20/9/11   ' '  25/1/11   ' '  15/9/11   ' '  18/4/11   '
 ' 13/12/10   ' ' 12/10/11   ' '   8/4/11   ' '  13/7/11   '
 '  6/12/10   ' '  24/8/11   ' '   5/8/11   ' '  5/12/10   '
 '  10/4/11   ' '  30/8/11   ' '  17/1/11   ' '   5/7/11   '
 '   7/7/11   ' '   8/3/11   ' '  27/9/11   ' ' 13/11/11   '
 '   7/3/11   ' '   6/1/11   ' '  26/4/11   ' '  19/1/11   '
 '  2/12/10   ' '  7/12/11   ' '   5/4/11   ' '  28/6/11   '
 '   1/2/11   ' '  20/1/11   ' '   4/5/11   ' '  19/5/11   '
 '  13/9/11   ' ' 10/11/11   ' ' 24/10/11   ' '  28/3/11   '
 '  17/7/11   ' '   1/6/11   ' '  9/12/11   ' '  25/9/11   '
 '   9/2/11   ' '  21/9/11   ' '  6/11/11   ' '  13/2/11   '
 '  29/3/11   ' ' 17/11/11   ' ' 10/12/10   ' '  8/12/11   '
 '  10/5/11   ' '  21/3/11   ' '  29/7/11   ' ' 29/11/11   '
 '  15/7/11   ' '   2/9/11   ' '   1/3/11   ' '  21/6/11   '
 ' 20/10/11   ' '  15/4/11   ' '   4/3/11   ' '  27/1/11   '
 '  19/6/11   ' '  18/9/11   ' ' 27/11/11   ' '  14/6/11   '
 '   4/7/11   ' '  10/6/11   ' '  15/2/11   ' '  28/2/11   '
 ' 23/11/11   ' '  18/8/11   ' '   9/8/11   ' ' 10/10/11   '
 '  26/5/11   ' ' 28/11/11   ' '  10/2/11   ' '   4/9/11   '
 '   8/6/11   ' '  26/7/11   ' '  11/4/11   ' '  12/7/11   '
 '  23/9/11   ' '   4/2/11   ' '  7/10/11   ' ' 16/12/10   '
 '  9/11/11   ' '  10/3/11   ' '  2/10/11   ' '  14/1/11   '
 ' 30/10/11   ' '  7/11/11   ' '   2/8/11   ' '   8/7/11   '
 '  30/3/11   ' '  11/1/11   ' '  17/3/11   ' '  21/4/11   '
 '  24/3/11   ' '  19/9/11   ' '  15/8/11   ' '  24/5/11   '
 '  10/8/11   ' ' 22/11/11   ' '  20/6/11   ' ' 21/12/10   '
 '  8/11/11   ' '  1/11/11   ' '  1/12/10   ' '   3/5/11   '
 '   9/3/11   ' '  6/10/11   ' '  14/7/11   ' ' 24/11/11   '
 ' 17/10/11   ' ' 14/10/11   ' '  2/11/11   ' '  11/9/11   '
 '  21/7/11   ' ' 20/11/11   ' '  28/9/11   ' '  16/6/11   '
 '  25/7/11   ' ' 14/12/10   ' '  17/8/11   ' ' 30/11/11   '
 ' 14/11/11   ' '  25/5/11   ' '   8/5/11   ' '  17/5/11   '
 '  14/2/11   ' '  9/12/10   ' '  31/5/11   ' '  22/6/11   '
 '  30/1/11   ' ' 16/11/11   ' '   9/1/11   ' '   2/6/11   '
 '  9/10/11   ' '   6/6/11   ' ' 20/12/10   ' '  15/6/11   '
 '  16/5/11   ' '   5/1/11   ' '  26/8/11   ' '  22/3/11   '
 '   9/6/11   ' '  24/2/11   ' '  23/3/11   ' '   8/9/11   '
 '  3/11/11   ' '   3/2/11   ' '   5/6/11   ' '  22/9/11   '
 '   1/5/11   ' '  1/12/11   ' '  7/12/10   ' '  21/1/11   '
 '   7/1/11   ' ' 18/11/11   ' '  11/3/11   ' '   3/6/11   '
 '  30/9/11   ' ' 16/10/11   ' '  17/6/11   ' '  17/4/11   '
 ' 11/11/11   ' '   7/2/11   ' '  13/6/11   ' '  31/1/11   '
 ' 21/10/11   ' '  4/12/11   ' '  19/4/11   ' '  22/8/11   '
 '  19/7/11   ' ' 19/10/11   ' ' 23/12/10   ' '  31/8/11   '
 '  23/8/11   ' '  27/7/11   ' '   1/8/11   ' ' 21/11/11   '
 '  10/1/11   ' ' 13/10/11   ' '  20/7/11   ' '  27/5/11   '
 '   6/9/11   ' ' 18/10/11   ' '  24/1/11   ' '  21/2/11   '
 '  16/3/11   ' ' 28/10/11   ' '  14/4/11   ' '  22/5/11   '
 '  14/3/11   ' '  14/9/11   ' '  25/3/11   ' '  3/12/10   '
 '  28/1/11   ' '  31/3/11   ' '  4/11/11   ' '  18/2/11   '
 ' 11/10/11   ' '  5/12/11   ' ' 15/12/10   ' '  23/2/11   '
 '  20/3/11   ' '  11/7/11   ' '  29/9/11   ' '  18/7/11   '
 ' 25/11/11   ' '  13/3/11   ' '   3/3/11   ' '  5/10/11   '
 '   7/9/11   ' '   9/9/11   ' '  21/8/11   ' '   4/4/11   '
 '  12/6/11   ' '   4/8/11   ' '  18/5/11   ' '  11/5/11   '
 '  27/2/11   ' '  2/12/11   ' '  25/8/11   ' '  20/4/11   '
 '  12/1/11   ' '  24/7/11   ' '   1/9/11   ' '  23/5/11   '
 '  16/9/11   ' '  12/8/11   ' '  13/5/11   ' '  12/4/11   ']

invoicetime
341
['   09:35   ' '   09:26   ' '   10:54   ' '   13:48   ' '   14:49   '
 '   12:38   ' '   13:36   ' '   12:01   ' '   12:31   ' '   14:33   '
 '   14:07   ' '   14:01   ' '   15:45   ' '   10:23   ' '   08:20   '
 '   13:14   ' '   12:41   ' '   15:08   ' '   10:32   ' '   16:59   '
 '   11:49   ' '   15:09   ' '   10:39   ' '   17:57   ' '   12:15   '
 '   12:16   ' '   12:53   ' '   13:58   ' '   14:03   ' '   09:23   '
 '   11:46   ' '   12:17   ' '   17:02   ' '   14:47   ' '   14:43   '
 '   12:08   ' '   11:44   ' '   11:30   ' '   18:01   ' '   12:32   '
 '   14:27   ' '   16:05   ' '   14:16   ' '   14:36   ' '   13:25   '
 '   08:40   ' '   13:46   ' '   14:54   ' '   17:33   ' '   10:03   '
 '   11:22   ' '   12:00   ' '   14:19   ' '   16:52   ' '   15:12   '
 '   14:06   ' '   15:18   ' '   09:11   ' '   11:26   ' '   15:17   '
 '   14:59   ' '   15:29   ' '   19:29   ' '   13:00   ' '   15:07   '
 '   15:10   ' '   11:58   ' '   09:48   ' '   09:21   ' '   16:33   '
 '   16:06   ' '   09:38   ' '   17:08   ' '   11:48   ' '   11:41   '
 '   11:03   ' '   10:40   ' '   14:41   ' '   15:51   ' '   10:08   '
 '   12:23   ' '   15:32   ' '   17:25   ' '   09:34   ' '   16:26   '
 '   11:11   ' '   13:52   ' '   13:20   ' '   11:19   ' '   16:30   '
 '   08:59   ' '   13:05   ' '   13:39   ' '   13:01   ' '   11:47   '
 '   17:44   ' '   10:46   ' '   17:54   ' '   14:08   ' '   17:09   '
 '   10:20   ' '   14:13   ' '   12:07   ' '   12:37   ' '   17:15   '
 '   15:54   ' '   14:42   ' '   17:00   ' '   12:42   ' '   17:47   '
 '   15:50   ' '   14:25   ' '   14:28   ' '   16:17   ' '   12:06   '
 '   16:39   ' '   08:43   ' '   12:27   ' '   15:16   ' '   13:06   '
 '   12:02   ' '   09:58   ' '   20:18   ' '   10:51   ' '   14:52   '
 '   12:52   ' '   14:55   ' '   10:41   ' '   09:46   ' '   13:09   '
 '   14:29   ' '   10:58   ' '   17:46   ' '   10:09   ' '   16:02   '
 '   13:41   ' '   15:19   ' '   10:35   ' '   18:29   ' '   12:48   '
 '   16:37   ' '   11:45   ' '   13:26   ' '   15:03   ' '   15:36   '
 '   12:04   ' '   13:10   ' '   11:42   ' '   11:39   ' '   12:29   '
 '   15:44   ' '   12:45   ' '   13:42   ' '   12:13   ' '   09:31   '
 '   13:27   ' '   14:09   ' '   11:40   ' '   15:06   ' '   11:23   '
 '   12:36   ' '   09:17   ' '   13:16   ' '   13:57   ' '   13:33   '
 '   15:53   ' '   08:23   ' '   15:22   ' '   12:46   ' '   11:12   '
 '   16:10   ' '   12:12   ' '   13:35   ' '   12:11   ' '   09:41   '
 '   14:11   ' '   12:25   ' '   14:20   ' '   14:58   ' '   11:43   '
 '   10:33   ' '   12:09   ' '   12:50   ' '   09:28   ' '   14:21   '
 '   11:32   ' '   10:45   ' '   11:13   ' '   10:48   ' '   17:01   '
 '   11:37   ' '   10:14   ' '   10:01   ' '   13:34   ' '   17:28   '
 '   12:20   ' '   16:50   ' '   14:56   ' '   14:45   ' '   14:14   '
 '   16:27   ' '   16:55   ' '   14:57   ' '   18:07   ' '   13:59   '
 '   10:00   ' '   11:56   ' '   16:51   ' '   09:50   ' '   09:30   '
 '   14:22   ' '   10:50   ' '   17:18   ' '   12:55   ' '   19:42   '
 '   15:31   ' '   12:03   ' '   16:19   ' '   15:00   ' '   09:44   '
 '   13:55   ' '   11:02   ' '   17:40   ' '   17:11   ' '   14:24   '
 '   11:53   ' '   08:54   ' '   12:35   ' '   13:51   ' '   11:38   '
 '   15:30   ' '   09:05   ' '   15:20   ' '   13:45   ' '   13:54   '
 '   12:40   ' '   09:37   ' '   09:29   ' '   14:04   ' '   14:46   '
 '   10:04   ' '   12:58   ' '   08:15   ' '   10:52   ' '   09:54   '
 '   11:18   ' '   08:03   ' '   12:28   ' '   10:26   ' '   10:24   '
 '   10:22   ' '   10:29   ' '   15:28   ' '   15:23   ' '   10:15   '
 '   10:47   ' '   11:25   ' '   09:04   ' '   14:38   ' '   13:40   '
 '   15:35   ' '   13:17   ' '   09:00   ' '   11:52   ' '   13:30   '
 '   15:13   ' '   15:42   ' '   16:34   ' '   15:55   ' '   13:08   '
 '   15:14   ' '   08:56   ' '   13:37   ' '   10:38   ' '   11:04   '
 '   10:53   ' '   14:26   ' '   10:19   ' '   17:53   ' '   15:43   '
 '   13:24   ' '   08:38   ' '   13:28   ' '   09:08   ' '   09:33   '
 '   15:47   ' '   08:31   ' '   13:22   ' '   16:28   ' '   09:13   '
 '   10:10   ' '   14:48   ' '   16:21   ' '   16:44   ' '   09:20   '
 '   13:15   ' '   16:07   ' '   08:45   ' '   11:20   ' '   15:58   '
 '   16:12   ' '   10:42   ' '   13:13   ' '   13:32   ' '   12:26   '
 '   14:10   ' '   11:51   ' '   10:11   ' '   11:33   ' '   14:18   '
 '   09:10   ' '   12:34   ' '   12:44   ' '   09:57   ' '   16:31   '
 '   14:23   ' '   13:49   ' '   09:43   ' '   14:17   ' '   13:56   '
 '   11:59   ' '   10:34   ' '   09:01   ' '   15:52   ' '   16:58   '
 '   15:01   ' '   11:34   ' '   07:39   ' '   13:12   ' '   15:04   '
 '   12:05   ' '   09:47   ' '   09:14   ' '   09:52   ' '   10:59   '
 '   13:50   ' '   08:51   ' '   09:32   ' '   12:30   ' '   15:41   '
 '   10:27   ']

year-month
13
['2011-04   ' '2011-11   ' '2011-10   ' '2010-12   ' '2011-12   '
 '2011-09   ' '2011-05   ' '2011-01   ' '2011-07   ' '2011-08   '
 '2011-03   ' '2011-06   ' '2011-02   ']

major_category
4
['    Clothes  ' '    Kitchen  ' '     Garden  ' '  Household  ']

minor_category
17
['          Tops' '         Shoes' '       Cutlery' '          Turf'
 '         Hoses' '          Hats' '      Curtains' '         Lamps'
 'Cooking Knives' '          Rugs' '        Chairs' '      Coasters'
 '        Scales' '        Plates' '         Seeds' '         Rakes'
 '         Bowls']

description
398
['   PACK OF 20 NAPKINS PANTRY DESIGN'
 '    NATURAL SLATE HEART CHALKBOARD '
 '             36 PENCILS TUBE SKULLS'
 ' SET 6 SCHOOL MILK BOTTLES IN CRATE'
 '                 FINE WICKER HEART '
 '       SEWING BOX RETROSPOT DESIGN '
 ' 3 TRADITIONAl BISCUIT CUTTERS  SET'
 '             BULL DOG BOTTLE OPENER'
 '           STRAWBERRY CHARLOTTE BAG'
 '             FAIRY SOAP SOAP HOLDER'
 '   PACK OF 12 VINTAGE DOILY TISSUES'
 '     PACK OF 60 DINOSAUR CAKE CASES'
 '     CAKE STAND 3 TIER MAGIC GARDEN'
 '           ICE CREAM PEN LIP GLOSS '
 '                LUNCH BAG CARS BLUE'
 '             6 RIBBONS RUSTIC CHARM'
 '      ROSE 3 WICK MORRIS BOX CANDLE'
 '      HAND WARMER SCOTTY DOG DESIGN'
 '           JAM MAKING SET WITH JARS'
 '12 PENCILS SMALL TUBE RED RETROSPOT'
 "    PAPER CHAIN KIT 50'S CHRISTMAS "
 '             LAUNDRY 15C METAL SIGN'
 '     PANTRY MAGNETIC  SHOPPING LIST'
 '       SUMMER BUTTERFLIES BAG CHARM'
 '                     SPOTTY BUNTING'
 '   PINK BLUE FELT CRAFT TRINKET BOX'
 '            QUEENS GUARD COFFEE MUG'
 '            TRAVEL CARD WALLET SUKI'
 '              DOORMAT RED RETROSPOT'
 ' 3 PIECE SPACEBOY COOKIE CUTTER SET'
 '                DOORMAT NEW ENGLAND'
 '               SLEEPING CAT ERASERS'
 'SET 12 LAVENDER  BOTANICAL T-LIGHTS'
 '   PLASTERS IN TIN VINTAGE PAISLEY '
 '       HOMEMADE JAM SCENTED CANDLES'
 '           SCOTTIES CHILDRENS APRON'
 '  3D TRADITIONAL CHRISTMAS STICKERS'
 '    CLOTHES PEGS RETROSPOT PACK 24 '
 '       AIRLINE BAG VINTAGE TOKYO 78'
 '              JASMINE VOTIVE CANDLE'
 '         ROUND CAKE TIN VINTAGE RED'
 '  SET OF 6 SPICE TINS PANTRY DESIGN'
 '  SET OF SALT AND PEPPER TOADSTOOLS'
 '             JUMBO BAG VINTAGE LEAF'
 '          LETTER "M" BLING KEY RING'
 '   PLASTERS IN TIN WOODLAND ANIMALS'
 '   SET OF 36 PAISLEY FLOWER DOILIES'
 '        PAPER BUNTING COLOURED LACE'
 ' PACK OF 60 PINK PAISLEY CAKE CASES'
 '    OFFICE MUG WARMER BLACK+SILVER '
 '       NUMBER TILE COTTAGE GARDEN 1'
 '       FOOD COVER WITH BEADS SET 2 '
 '     GLASS APOTHECARY BOTTLE ELIXIR'
 '             PAPER CHAIN KIT EMPIRE'
 '        GINGHAM HEART  DOORSTOP RED'
 '        HAND WARMER BABUSHKA DESIGN'
 '          PAPER CHAIN KIT RETROSPOT'
 'JUMBO BAG SCANDINAVIAN BLUE PAISLEY'
 '           VINTAGE SNAKES & LADDERS'
 '       EASTER TIN CHICKS PINK DAISY'
 '          CHARLOTTE BAG SUKI DESIGN'
 '         HOT WATER BOTTLE KEEP CALM'
 '             ABC TREASURE BOOK BOX '
 ' WOODEN TREE CHRISTMAS SCANDINAVIAN'
 '                  CARD PARTY GAMES '
 '           PARISIENNE CURIO CABINET'
 '               IVORY KITCHEN SCALES'
 '   IVORY PILLAR CANDLE SILVER FLOCK'
 '                       OWL DOORSTOP'
 "            CHILDREN'S SPACEBOY MUG"
 '                 JUMBO BAG ALPHABET'
 '          BROWN CHECK CAT DOORSTOP '
 '       GLASS JAR DIGESTIVE BISCUITS'
 '          JUMBO BAG DOILEY PATTERNS'
 '   ROSES REGENCY TEACUP AND SAUCER '
 '  ANTIQUE SILVER TEA GLASS ENGRAVED'
 '                     RETRO MOD TRAY'
 '        JUMBO BAG DOLLY GIRL DESIGN'
 '         RED RETROSPOT PUDDING BOWL'
 '        PACK OF 20 SPACEBOY NAPKINS'
 '                     DOTCOM POSTAGE'
 '                 WRAP ENGLISH ROSE '
 '           WOOD STAMP SET THANK YOU'
 '     CHRISTMAS PUDDING TRINKET POT '
 '              PIGGY BANK RETROSPOT '
 '         STORAGE TIN VINTAGE DOILY '
 '             BLUE HARMONICA IN BOX '
 '             TEA TIME PARTY BUNTING'
 '         HEART FILIGREE DOVE  SMALL'
 '              HEART OF WICKER SMALL'
 '     JUMBO BAG PINK VINTAGE PAISLEY'
 ' GARDENERS KNEELING PAD CUP OF TEA '
 '          ASSORTED COLOURS SILK FAN'
 '           3 STRIPEY MICE FELTCRAFT'
 ' DOORMAT FANCY FONT HOME SWEET HOME'
 'CLEAR DRAWER KNOB ACRYLIC EDWARDIAN'
 '      PACK OF 6 LARGE FRUIT STRAWS '
 '   RETROSPOT HEART HOT WATER BOTTLE'
 '         TRADITIONAL MODELLING CLAY'
 '         CHOCOLATE HOT WATER BOTTLE'
 '          SET OF 6 SOLDIER SKITTLES'
 '            HAND WARMER BIRD DESIGN'
 '             GREEN FERN SKETCHBOOK '
 '      SWEETHEART WIRE MAGAZINE RACK'
 '         SET/4 BIRD MIRROR MAGNETS '
 '        LUNCH BAG DOLLY GIRL DESIGN'
 '    BLACK CANDELABRA T-LIGHT HOLDER'
 '     BLUE SCANDINAVIAN PAISLEY WRAP'
 '               DOLLY GIRL LUNCH BOX'
 ' GROW A FLYTRAP OR SUNFLOWER IN TIN'
 "          JUMBO BAG 50'S CHRISTMAS "
 '     CREAM CUPID HEARTS COAT HANGER'
 '            GOLD MINI TAPE MEASURE '
 '               PORCELAIN ROSE SMALL'
 '            ROMANTIC PINKS RIBBONS '
 '     ASS FLORAL PRINT SPIRIT LEVEL '
 ' TRADITIONAL WOODEN CATCH CUP GAME '
 '             JAM MAKING SET PRINTED'
 '                  TRELLIS COAT RACK'
 '          ALARM CLOCK BAKELIKE RED '
 '        UNION JACK FLAG LUGGAGE TAG'
 '   POCKET BAG BLUE PAISLEY RED SPOT'
 '    PACK OF 72 RETROSPOT CAKE CASES'
 '                SKULLS WRITING SET '
 '            GINGHAM RECIPE BOOK BOX'
 '        SET OF 5 LUCKY CAT MAGNETS '
 '       BICYCLE PUNCTURE REPAIR KIT '
 '            ROLL WRAP VINTAGE SPOT '
 '     72 SWEETHEART FAIRY CAKE CASES'
 '          12 EGG HOUSE PAINTED WOOD'
 '      CHRISTMAS RETROSPOT TREE WOOD'
 '     PLASTERS IN TIN CIRCUS PARADE '
 '              WRAP SUKI AND FRIENDS'
 '              RECIPE BOX RETROSPOT '
 ' BOX OF 6 ASSORTED COLOUR TEASPOONS'
 '     JUMBO  BAG BAROQUE BLACK WHITE'
 '                HOME SWEET HOME MUG'
 '            MOODY GIRL DOOR HANGER '
 '  JUMBO SHOPPER VINTAGE RED PAISLEY'
 '   EMPIRE UNION JACK TV DINNER TRAY'
 '                PHOTO FRAME CORNICE'
 '     TOILET SIGN OCCUPIED OR VACANT'
 '         RETRO COFFEE MUGS ASSORTED'
 '     SET OF 4 NAPKIN CHARMS CROWNS '
 '  SWEETHEART CREAM STEEL TABLE RECT'
 '          HEART FILIGREE DOVE LARGE'
 '              SCOTTIE DOGS BABY BIB'
 '     BOX OF 6 MINI VINTAGE CRACKERS'
 '       BLACK/BLUE POLKADOT UMBRELLA'
 '                      PARTY BUNTING'
 '       SMALL HEART MEASURING SPOONS'
 '     CERAMIC CHERRY CAKE MONEY BANK'
 '                 CARD SUKI BIRTHDAY'
 'SET OF 60 I LOVE LONDON CAKE CASES '
 'COLOUR GLASS T-LIGHT HOLDER HANGING'
 '       MODERN FLORAL STATIONERY SET'
 '            LUNCH BAG PINK POLKADOT'
 'SET3 BOOK BOX GREEN GINGHAM FLOWER '
 '                 VINTAGE SNAP CARDS'
 '   CIRCUS PARADE CHILDRENS EGG CUP '
 '  SKETCHBOOK MAGNETIC SHOPPING LIST'
 '    EASTER DECORATION SITTING BUNNY'
 '        VICTORIAN SEWING BOX SMALL '
 '15CM CHRISTMAS GLASS BALL 20 LIGHTS'
 '     RED GINGHAM ROSE JEWELLERY BOX'
 '             CHOCOLATE BOX RIBBONS '
 '      VINTAGE LEAF MAGNETIC NOTEPAD'
 '                APRON APPLE DELIGHT'
 '                     SANDALWOOD FAN'
 '     SET OF 6 3D KIT CARDS FOR KIDS'
 '            GLITTER BUTTERFLY CLIPS'
 '         RIBBON REEL FLORA + FAUNA '
 '     FELTCRAFT PRINCESS OLIVIA DOLL'
 '            RED SPOT GIFT BAG LARGE'
 ' 3 RAFFIA RIBBONS VINTAGE CHRISTMAS'
 'FOLK ART METAL HEART T-LIGHT HOLDER'
 '      CANDLE HOLDER SILVER MADELINE'
 '           PLASTERS IN TIN SPACEBOY'
 '           COFFEE MUG APPLES DESIGN'
 '    SET 12 RETRO WHITE CHALK STICKS'
 '           JUMBO STORAGE BAG SKULLS'
 '                  RED RETROSPOT MUG'
 '        CHARLOTTE BAG APPLES DESIGN'
 '        4 VANILLA BOTANICAL CANDLES'
 '       SET OF 5 PANCAKE DAY MAGNETS'
 '                  GUMBALL COAT RACK'
 '          CAKES AND BOWS GIFT  TAPE'
 '             HAND WARMER OWL DESIGN'
 '       EGG CUP HENRIETTA HEN CREAM '
 '    CHARLOTTE BAG VINTAGE ALPHABET '
 ' CHILDS BREAKFAST SET CIRCUS PARADE'
 '            MINI PAINT SET VINTAGE '
 '         ASSORTED COLOUR MINI CASES'
 '   RETROSPOT TEA SET CERAMIC 11 PC '
 '                 WRAP DOILEY DESIGN'
 '  MAGNETS PACK OF 4 HOME SWEET HOME'
 '  LUNCH BOX WITH CUTLERY RETROSPOT '
 '      SET/6 RED SPOTTY PAPER PLATES'
 ' METAL DECORATION NAUGHTY CHILDREN '
 '          PLASTERS IN TIN STRONGMAN'
 '          LUNCH BAG DOILEY PATTERN '
 '       ADVENT CALENDAR GINGHAM SACK'
 '        DOORMAT WELCOME TO OUR HOME'
 '        WRAP VINTAGE PETALS  DESIGN'
 '             WOODLAND CHARLOTTE BAG'
 '                            POSTAGE'
 '    GREEN REGENCY TEACUP AND SAUCER'
 '                  WRAP GREEN PEARS '
 '       SPACEBOY ROCKET LOLLY MAKERS'
 '                    WRAP DOLLY GIRL'
 '      SET OF 6 HERB TINS SKETCHBOOK'
 '       200 RED + WHITE BENDY STRAWS'
 '          ENAMEL WATERING CAN CREAM'
 '        PINK HAPPY BIRTHDAY BUNTING'
 '       PACK OF 6 SKULL PAPER PLATES'
 '      3D CHRISTMAS STAMPS STICKERS '
 '         TREASURE TIN BUFFALO BILL '
 '      BLUE SPOT CERAMIC DRAWER KNOB'
 '      CHILDRENS APRON APPLES DESIGN'
 '                   DOORMAT AIRMAIL '
 '           DOLLY GIRL MINI BACKPACK'
 '  HEART WREATH DECORATION WITH BELL'
 '  STRAWBERRY LUNCH BOX WITH CUTLERY'
 '         TRADITIONAL KNITTING NANCY'
 '           JUMBO BAG VINTAGE DOILY '
 '              RAIN PONCHO RETROSPOT'
 '        LARGE CHINESE STYLE SCISSOR'
 'PINK AND WHITE CHRISTMAS TREE 120CM'
 '     FAIRY CAKE BIRTHDAY CANDLE SET'
 '     MINI LIGHTS WOODLAND MUSHROOMS'
 '       PACK 3 BOXES BIRD PANNETONE '
 '           REGENCY CAKESTAND 3 TIER'
 '          MULTICOLOUR HONEYCOMB FAN'
 '           RED RETROSPOT CAKE STAND'
 '       PACK OF 12 WOODLAND TISSUES '
 '     PACK OF 6 PANNETONE GIFT BOXES'
 '            PANTRY WASHING UP BRUSH'
 '        SET/6 RED SPOTTY PAPER CUPS'
 '                  RED BABY BUNTING '
 '           COFFEE MUG PEARS  DESIGN'
 '                   HOLIDAY FUN LUDO'
 '  ANT COPPER TURQ BOUDICCA BRACELET'
 ' ROUND SNACK BOXES SET OF 4 FRUITS '
 '   TRADITIONAL PICK UP STICKS GAME '
 '                     FUNKY DIVA PEN'
 '         BREAD BIN DINER STYLE PINK'
 '              PANTRY CHOPPING BOARD'
 '     SET 2 PANTRY DESIGN TEA TOWELS'
 '            SPACEBOY TV DINNER TRAY'
 '     EMBROIDERED RIBBON REEL DAISY '
 '                 KIDS RAIN MAC BLUE'
 ' WHITE SPOT RED CERAMIC DRAWER KNOB'
 '   CHILDS BREAKFAST SET DOLLY GIRL '
 '                 LUNCH BAG WOODLAND'
 '             LUNCH BAG APPLE DESIGN'
 '     LIGHT GARLAND BUTTERFILES PINK'
 '     CHILDS BREAKFAST SET SPACEBOY '
 '        ROLL WRAP VINTAGE CHRISTMAS'
 '        MINI PLAYING CARDS GYMKHANA'
 ' SET OF 72 RETROSPOT PAPER  DOILIES'
 '    RED KUKUI COCONUT SEED NECKLACE'
 '        HOME SWEET HOME METAL SIGN '
 ' METAL 4 HOOK HANGER FRENCH CHATEAU'
 '        GIFT BAG PSYCHEDELIC APPLES'
 ' ASS FLORAL PRINT MULTI SCREWDRIVER'
 '   ZINC WILLIE WINKIE  CANDLE STICK'
 '  HEART WOODEN CHRISTMAS DECORATION'
 ' SET/10 PINK POLKADOT PARTY CANDLES'
 '             STOOL HOME SWEET HOME '
 '    MAGIC DRAWING SLATE DOLLY GIRL '
 '              CACTI T-LIGHT CANDLES'
 '           SET/6 COLLAGE PAPER CUPS'
 '            EDWARDIAN PARASOL BLACK'
 '       SMALL RED RETROSPOT WINDMILL'
 '              LONDON BUS COFFEE MUG'

In [39]:
# create a txt file that have a data descripe the categorical columns
with open('catagourical_col.txt', 'w') as f:
    for col in cat_cols:
        f.write(f"{col}: {df[col].nunique()}\n")
        f.write(f"{df[col].unique()}\n\n")

In [45]:
'  11/11/11   '.replace('11', '2011', 1)

'  2011/11/11   '

In [46]:
# to get rid of leading and trailing spaces
for col in cat_cols:

    df[col] = df[col].str.strip()

In [47]:
for col in cat_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique(), '\n')

country
5
['United Kingdom' 'Germany' 'France' 'Australia' 'Hong Kong']

invoicedate
240
['7/4/11' '15/11/11' '27/4/11' '31/10/11' '17/12/10' '6/12/11' '26/9/11'
 '12/5/11' '20/9/11' '25/1/11' '15/9/11' '18/4/11' '13/12/10' '12/10/11'
 '8/4/11' '13/7/11' '6/12/10' '24/8/11' '5/8/11' '5/12/10' '10/4/11'
 '30/8/11' '17/1/11' '5/7/11' '7/7/11' '8/3/11' '27/9/11' '13/11/11'
 '7/3/11' '6/1/11' '26/4/11' '19/1/11' '2/12/10' '7/12/11' '5/4/11'
 '28/6/11' '1/2/11' '20/1/11' '4/5/11' '19/5/11' '13/9/11' '10/11/11'
 '24/10/11' '28/3/11' '17/7/11' '1/6/11' '9/12/11' '25/9/11' '9/2/11'
 '21/9/11' '6/11/11' '13/2/11' '29/3/11' '17/11/11' '10/12/10' '8/12/11'
 '10/5/11' '21/3/11' '29/7/11' '29/11/11' '15/7/11' '2/9/11' '1/3/11'
 '21/6/11' '20/10/11' '15/4/11' '4/3/11' '27/1/11' '19/6/11' '18/9/11'
 '27/11/11' '14/6/11' '4/7/11' '10/6/11' '15/2/11' '28/2/11' '23/11/11'
 '18/8/11' '9/8/11' '10/10/11' '26/5/11' '28/11/11' '10/2/11' '4/9/11'
 '8/6/11' '26/7/11' '11/4/11' '12/7/11' '23/9/11' '4/2/11' '7/10/11'
 '16/12/10' '9/11/11' '10/3/11' '2/10/11' '14/1/11' '30/10/11' '7/11/11'
 '2/8/11' '8/7/11' '30/3/11' '11/1/11' '17/3/11' '21/4/11' '24/3/11'
 '19/9/11' '15/8/11' '24/5/11' '10/8/11' '22/11/11' '20/6/11' '21/12/10'
 '8/11/11' '1/11/11' '1/12/10' '3/5/11' '9/3/11' '6/10/11' '14/7/11'
 '24/11/11' '17/10/11' '14/10/11' '2/11/11' '11/9/11' '21/7/11' '20/11/11'
 '28/9/11' '16/6/11' '25/7/11' '14/12/10' '17/8/11' '30/11/11' '14/11/11'
 '25/5/11' '8/5/11' '17/5/11' '14/2/11' '9/12/10' '31/5/11' '22/6/11'
 '30/1/11' '16/11/11' '9/1/11' '2/6/11' '9/10/11' '6/6/11' '20/12/10'
 '15/6/11' '16/5/11' '5/1/11' '26/8/11' '22/3/11' '9/6/11' '24/2/11'
 '23/3/11' '8/9/11' '3/11/11' '3/2/11' '5/6/11' '22/9/11' '1/5/11'
 '1/12/11' '7/12/10' '21/1/11' '7/1/11' '18/11/11' '11/3/11' '3/6/11'
 '30/9/11' '16/10/11' '17/6/11' '17/4/11' '11/11/11' '7/2/11' '13/6/11'
 '31/1/11' '21/10/11' '4/12/11' '19/4/11' '22/8/11' '19/7/11' '19/10/11'
 '23/12/10' '31/8/11' '23/8/11' '27/7/11' '1/8/11' '21/11/11' '10/1/11'
 '13/10/11' '20/7/11' '27/5/11' '6/9/11' '18/10/11' '24/1/11' '21/2/11'
 '16/3/11' '28/10/11' '14/4/11' '22/5/11' '14/3/11' '14/9/11' '25/3/11'
 '3/12/10' '28/1/11' '31/3/11' '4/11/11' '18/2/11' '11/10/11' '5/12/11'
 '15/12/10' '23/2/11' '20/3/11' '11/7/11' '29/9/11' '18/7/11' '25/11/11'
 '13/3/11' '3/3/11' '5/10/11' '7/9/11' '9/9/11' '21/8/11' '4/4/11'
 '12/6/11' '4/8/11' '18/5/11' '11/5/11' '27/2/11' '2/12/11' '25/8/11'
 '20/4/11' '12/1/11' '24/7/11' '1/9/11' '23/5/11' '16/9/11' '12/8/11'
 '13/5/11' '12/4/11']

invoicetime
341
['09:35' '09:26' '10:54' '13:48' '14:49' '12:38' '13:36' '12:01' '12:31'
 '14:33' '14:07' '14:01' '15:45' '10:23' '08:20' '13:14' '12:41' '15:08'
 '10:32' '16:59' '11:49' '15:09' '10:39' '17:57' '12:15' '12:16' '12:53'
 '13:58' '14:03' '09:23' '11:46' '12:17' '17:02' '14:47' '14:43' '12:08'
 '11:44' '11:30' '18:01' '12:32' '14:27' '16:05' '14:16' '14:36' '13:25'
 '08:40' '13:46' '14:54' '17:33' '10:03' '11:22' '12:00' '14:19' '16:52'
 '15:12' '14:06' '15:18' '09:11' '11:26' '15:17' '14:59' '15:29' '19:29'
 '13:00' '15:07' '15:10' '11:58' '09:48' '09:21' '16:33' '16:06' '09:38'
 '17:08' '11:48' '11:41' '11:03' '10:40' '14:41' '15:51' '10:08' '12:23'
 '15:32' '17:25' '09:34' '16:26' '11:11' '13:52' '13:20' '11:19' '16:30'
 '08:59' '13:05' '13:39' '13:01' '11:47' '17:44' '10:46' '17:54' '14:08'
 '17:09' '10:20' '14:13' '12:07' '12:37' '17:15' '15:54' '14:42' '17:00'
 '12:42' '17:47' '15:50' '14:25' '14:28' '16:17' '12:06' '16:39' '08:43'
 '12:27' '15:16' '13:06' '12:02' '09:58' '20:18' '10:51' '14:52' '12:52'
 '14:55' '10:41' '09:46' '13:09' '14:29' '10:58' '17:46' '10:09' '16:02'
 '13:41' '15:19' '10:35' '18:29' '12:48' '16:37' '11:45' '13:26' '15:03'
 '15:36' '12:04' '13:10' '11:42' '11:39' '12:29' '15:44' '12:45' '13:42'
 '12:13' '09:31' '13:27' '14:09' '11:40' '15:06' '11:23' '12:36' '09:17'
 '13:16' '13:57' '13:33' '15:53' '08:23' '15:22' '12:46' '11:12' '16:10'
 '12:12' '13:35' '12:11' '09:41' '14:11' '12:25' '14:20' '14:58' '11:43'
 '10:33' '12:09' '12:50' '09:28' '14:21' '11:32' '10:45' '11:13' '10:48'
 '17:01' '11:37' '10:14' '10:01' '13:34' '17:28' '12:20' '16:50' '14:56'
 '14:45' '14:14' '16:27' '16:55' '14:57' '18:07' '13:59' '10:00' '11:56'
 '16:51' '09:50' '09:30' '14:22' '10:50' '17:18' '12:55' '19:42' '15:31'
 '12:03' '16:19' '15:00' '09:44' '13:55' '11:02' '17:40' '17:11' '14:24'
 '11:53' '08:54' '12:35' '13:51' '11:38' '15:30' '09:05' '15:20' '13:45'
 '13:54' '12:40' '09:37' '09:29' '14:04' '14:46' '10:04' '12:58' '08:15'
 '10:52' '09:54' '11:18' '08:03' '12:28' '10:26' '10:24' '10:22' '10:29'
 '15:28' '15:23' '10:15' '10:47' '11:25' '09:04' '14:38' '13:40' '15:35'
 '13:17' '09:00' '11:52' '13:30' '15:13' '15:42' '16:34' '15:55' '13:08'
 '15:14' '08:56' '13:37' '10:38' '11:04' '10:53' '14:26' '10:19' '17:53'
 '15:43' '13:24' '08:38' '13:28' '09:08' '09:33' '15:47' '08:31' '13:22'
 '16:28' '09:13' '10:10' '14:48' '16:21' '16:44' '09:20' '13:15' '16:07'
 '08:45' '11:20' '15:58' '16:12' '10:42' '13:13' '13:32' '12:26' '14:10'
 '11:51' '10:11' '11:33' '14:18' '09:10' '12:34' '12:44' '09:57' '16:31'
 '14:23' '13:49' '09:43' '14:17' '13:56' '11:59' '10:34' '09:01' '15:52'
 '16:58' '15:01' '11:34' '07:39' '13:12' '15:04' '12:05' '09:47' '09:14'
 '09:52' '10:59' '13:50' '08:51' '09:32' '12:30' '15:41' '10:27']

year-month
13
['2011-04' '2011-11' '2011-10' '2010-12' '2011-12' '2011-09' '2011-05'
 '2011-01' '2011-07' '2011-08' '2011-03' '2011-06' '2011-02']

major_category
4
['Clothes' 'Kitchen' 'Garden' 'Household']

minor_category
17
['Tops' 'Shoes' 'Cutlery' 'Turf' 'Hoses' 'Hats' 'Curtains' 'Lamps'
 'Cooking Knives' 'Rugs' 'Chairs' 'Coasters' 'Scales' 'Plates' 'Seeds'
 'Rakes' 'Bowls']

description
398
['PACK OF 20 NAPKINS PANTRY DESIGN' 'NATURAL SLATE HEART CHALKBOARD'
 '36 PENCILS TUBE SKULLS' 'SET 6 SCHOOL MILK BOTTLES IN CRATE'
 'FINE WICKER HEART' 'SEWING BOX RETROSPOT DESIGN'
 '3 TRADITIONAl BISCUIT CUTTERS  SET' 'BULL DOG BOTTLE OPENER'
 'STRAWBERRY CHARLOTTE BAG' 'FAIRY SOAP SOAP HOLDER'
 'PACK OF 12 VINTAGE DOILY TISSUES' 'PACK OF 60 DINOSAUR CAKE CASES'
 'CAKE STAND 3 TIER MAGIC GARDEN' 'ICE CREAM PEN LIP GLOSS'
 'LUNCH BAG CARS BLUE' '6 RIBBONS RUSTIC CHARM'
 'ROSE 3 WICK MORRIS BOX CANDLE' 'HAND WARMER SCOTTY DOG DESIGN'
 'JAM MAKING SET WITH JARS' '12 PENCILS SMALL TUBE RED RETROSPOT'
 "PAPER CHAIN KIT 50'S CHRISTMAS" 'LAUNDRY 15C METAL SIGN'
 'PANTRY MAGNETIC  SHOPPING LIST' 'SUMMER BUTTERFLIES BAG CHARM'
 'SPOTTY BUNTING' 'PINK BLUE FELT CRAFT TRINKET BOX'
 'QUEENS GUARD COFFEE MUG' 'TRAVEL CARD WALLET SUKI'
 'DOORMAT RED RETROSPOT' '3 PIECE SPACEBOY COOKIE CUTTER SET'
 'DOORMAT NEW ENGLAND' 'SLEEPING CAT ERASERS'
 'SET 12 LAVENDER  BOTANICAL T-LIGHTS' 'PLASTERS IN TIN VINTAGE PAISLEY'
 'HOMEMADE JAM SCENTED CANDLES' 'SCOTTIES CHILDRENS APRON'
 '3D TRADITIONAL CHRISTMAS STICKERS' 'CLOTHES PEGS RETROSPOT PACK 24'
 'AIRLINE BAG VINTAGE TOKYO 78' 'JASMINE VOTIVE CANDLE'
 'ROUND CAKE TIN VINTAGE RED' 'SET OF 6 SPICE TINS PANTRY DESIGN'
 'SET OF SALT AND PEPPER TOADSTOOLS' 'JUMBO BAG VINTAGE LEAF'
 'LETTER "M" BLING KEY RING' 'PLASTERS IN TIN WOODLAND ANIMALS'
 'SET OF 36 PAISLEY FLOWER DOILIES' 'PAPER BUNTING COLOURED LACE'
 'PACK OF 60 PINK PAISLEY CAKE CASES' 'OFFICE MUG WARMER BLACK+SILVER'
 'NUMBER TILE COTTAGE GARDEN 1' 'FOOD COVER WITH BEADS SET 2'
 'GLASS APOTHECARY BOTTLE ELIXIR' 'PAPER CHAIN KIT EMPIRE'
 'GINGHAM HEART  DOORSTOP RED' 'HAND WARMER BABUSHKA DESIGN'
 'PAPER CHAIN KIT RETROSPOT' 'JUMBO BAG SCANDINAVIAN BLUE PAISLEY'
 'VINTAGE SNAKES & LADDERS' 'EASTER TIN CHICKS PINK DAISY'
 'CHARLOTTE BAG SUKI DESIGN' 'HOT WATER BOTTLE KEEP CALM'
 'ABC TREASURE BOOK BOX' 'WOODEN TREE CHRISTMAS SCANDINAVIAN'
 'CARD PARTY GAMES' 'PARISIENNE CURIO CABINET' 'IVORY KITCHEN SCALES'
 'IVORY PILLAR CANDLE SILVER FLOCK' 'OWL DOORSTOP'
 "CHILDREN'S SPACEBOY MUG" 'JUMBO BAG ALPHABET' 'BROWN CHECK CAT DOORSTOP'
 'GLASS JAR DIGESTIVE BISCUITS' 'JUMBO BAG DOILEY PATTERNS'
 'ROSES REGENCY TEACUP AND SAUCER' 'ANTIQUE SILVER TEA GLASS ENGRAVED'
 'RETRO MOD TRAY' 'JUMBO BAG DOLLY GIRL DESIGN'
 'RED RETROSPOT PUDDING BOWL' 'PACK OF 20 SPACEBOY NAPKINS'
 'DOTCOM POSTAGE' 'WRAP ENGLISH ROSE' 'WOOD STAMP SET THANK YOU'
 'CHRISTMAS PUDDING TRINKET POT' 'PIGGY BANK RETROSPOT'
 'STORAGE TIN VINTAGE DOILY' 'BLUE HARMONICA IN BOX'
 'TEA TIME PARTY BUNTING' 'HEART FILIGREE DOVE  SMALL'
 'HEART OF WICKER SMALL' 'JUMBO BAG PINK VINTAGE PAISLEY'
 'GARDENERS KNEELING PAD CUP OF TEA' 'ASSORTED COLOURS SILK FAN'
 '3 STRIPEY MICE FELTCRAFT' 'DOORMAT FANCY FONT HOME SWEET HOME'
 'CLEAR DRAWER KNOB ACRYLIC EDWARDIAN' 'PACK OF 6 LARGE FRUIT STRAWS'
 'RETROSPOT HEART HOT WATER BOTTLE' 'TRADITIONAL MODELLING CLAY'
 'CHOCOLATE HOT WATER BOTTLE' 'SET OF 6 SOLDIER SKITTLES'
 'HAND WARMER BIRD DESIGN' 'GREEN FERN SKETCHBOOK'
 'SWEETHEART WIRE MAGAZINE RACK' 'SET/4 BIRD MIRROR MAGNETS'
 'LUNCH BAG DOLLY GIRL DESIGN' 'BLACK CANDELABRA T-LIGHT HOLDER'
 'BLUE SCANDINAVIAN PAISLEY WRAP' 'DOLLY GIRL LUNCH BOX'
 'GROW A FLYTRAP OR SUNFLOWER IN TIN' "JUMBO BAG 50'S CHRISTMAS"
 'CREAM CUPID HEARTS COAT HANGER' 'GOLD MINI TAPE MEASURE'
 'PORCELAIN ROSE SMALL' 'ROMANTIC PINKS RIBBONS'
 'ASS FLORAL PRINT SPIRIT LEVEL' 'TRADITIONAL WOODEN CATCH CUP GAME'
 'JAM MAKING SET PRINTED' 'TRELLIS COAT RACK' 'ALARM CLOCK BAKELIKE RED'
 'UNION JACK FLAG LUGGAGE TAG' 'POCKET BAG BLUE PAISLEY RED SPOT'
 'PACK OF 72 RETROSPOT CAKE CASES' 'SKULLS WRITING SET'
 'GINGHAM RECIPE BOOK BOX' 'SET OF 5 LUCKY CAT MAGNETS'
 'BICYCLE PUNCTURE REPAIR KIT' 'ROLL WRAP VINTAGE SPOT'
 '72 SWEETHEART FAIRY CAKE CASES' '12 EGG HOUSE PAINTED WOOD'
 'CHRISTMAS RETROSPOT TREE WOOD' 'PLASTERS IN TIN CIRCUS PARADE'
 'WRAP SUKI AND FRIENDS' 'RECIPE BOX RETROSPOT'
 'BOX OF 6 ASSORTED COLOUR TEASPOONS' 'JUMBO  BAG BAROQUE BLACK WHITE'
 'HOME SWEET HOME MUG' 'MOODY GIRL DOOR HANGER'
 'JUMBO SHOPPER VINTAGE RED PAISLEY' 'EMPIRE UNION JACK TV DINNER TRAY'
 'PHOTO FRAME CORNICE' 'TOILET SIGN OCCUPIED OR VACANT'
 'RETRO COFFEE MUGS ASSORTED' 'SET OF 4 NAPKIN CHARMS CROWNS'
 'SWEETHEART CREAM STEEL TABLE RECT' 'HEART FILIGREE DOVE LARGE'
 'SCOTTIE DOGS BABY BIB' 'BOX OF 6 MINI VINTAGE CRACKERS'
 'BLACK/BLUE POLKADOT UMBRELLA' 'PARTY BUNTING'
 'SMALL HEART MEASURING SPOONS' 'CERAMIC CHERRY CAKE MONEY BANK'
 'CARD SUKI BIRTHDAY' 'SET OF 60 I LOVE LONDON CAKE CASES'
 'COLOUR GLASS T-LIGHT HOLDER HANGING' 'MODERN FLORAL STATIONERY SET'
 'LUNCH BAG PINK POLKADOT' 'SET3 BOOK BOX GREEN GINGHAM FLOWER'
 'VINTAGE SNAP CARDS' 'CIRCUS PARADE CHILDRENS EGG CUP'
 'SKETCHBOOK MAGNETIC SHOPPING LIST' 'EASTER DECORATION SITTING BUNNY'
 'VICTORIAN SEWING BOX SMALL' '15CM CHRISTMAS GLASS BALL 20 LIGHTS'
 'RED GINGHAM ROSE JEWELLERY BOX' 'CHOCOLATE BOX RIBBONS'
 'VINTAGE LEAF MAGNETIC NOTEPAD' 'APRON APPLE DELIGHT' 'SANDALWOOD FAN'
 'SET OF 6 3D KIT CARDS FOR KIDS' 'GLITTER BUTTERFLY CLIPS'
 'RIBBON REEL FLORA + FAUNA' 'FELTCRAFT PRINCESS OLIVIA DOLL'
 'RED SPOT GIFT BAG LARGE' '3 RAFFIA RIBBONS VINTAGE CHRISTMAS'
 'FOLK ART METAL HEART T-LIGHT HOLDER' 'CANDLE HOLDER SILVER MADELINE'
 'PLASTERS IN TIN SPACEBOY' 'COFFEE MUG APPLES DESIGN'
 'SET 12 RETRO WHITE CHALK STICKS' 'JUMBO STORAGE BAG SKULLS'
 'RED RETROSPOT MUG' 'CHARLOTTE BAG APPLES DESIGN'
 '4 VANILLA BOTANICAL CANDLES' 'SET OF 5 PANCAKE DAY MAGNETS'
 'GUMBALL COAT RACK' 'CAKES AND BOWS GIFT  TAPE' 'HAND WARMER OWL DESIGN'
 'EGG CUP HENRIETTA HEN CREAM' 'CHARLOTTE BAG VINTAGE ALPHABET'
 'CHILDS BREAKFAST SET CIRCUS PARADE' 'MINI PAINT SET VINTAGE'
 'ASSORTED COLOUR MINI CASES' 'RETROSPOT TEA SET CERAMIC 11 PC'
 'WRAP DOILEY DESIGN' 'MAGNETS PACK OF 4 HOME SWEET HOME'
 'LUNCH BOX WITH CUTLERY RETROSPOT' 'SET/6 RED SPOTTY PAPER PLATES'
 'METAL DECORATION NAUGHTY CHILDREN' 'PLASTERS IN TIN STRONGMAN'
 'LUNCH BAG DOILEY PATTERN' 'ADVENT CALENDAR GINGHAM SACK'
 'DOORMAT WELCOME TO OUR HOME' 'WRAP VINTAGE PETALS  DESIGN'
 'WOODLAND CHARLOTTE BAG' 'POSTAGE' 'GREEN REGENCY TEACUP AND SAUCER'
 'WRAP GREEN PEARS' 'SPACEBOY ROCKET LOLLY MAKERS' 'WRAP DOLLY GIRL'
 'SET OF 6 HERB TINS SKETCHBOOK' '200 RED + WHITE BENDY STRAWS'
 'ENAMEL WATERING CAN CREAM' 'PINK HAPPY BIRTHDAY BUNTING'
 'PACK OF 6 SKULL PAPER PLATES' '3D CHRISTMAS STAMPS STICKERS'
 'TREASURE TIN BUFFALO BILL' 'BLUE SPOT CERAMIC DRAWER KNOB'
 'CHILDRENS APRON APPLES DESIGN' 'DOORMAT AIRMAIL'
 'DOLLY GIRL MINI BACKPACK' 'HEART WREATH DECORATION WITH BELL'
 'STRAWBERRY LUNCH BOX WITH CUTLERY' 'TRADITIONAL KNITTING NANCY'
 'JUMBO BAG VINTAGE DOILY' 'RAIN PONCHO RETROSPOT'
 'LARGE CHINESE STYLE SCISSOR' 'PINK AND WHITE CHRISTMAS TREE 120CM'
 'FAIRY CAKE BIRTHDAY CANDLE SET' 'MINI LIGHTS WOODLAND MUSHROOMS'
 'PACK 3 BOXES BIRD PANNETONE' 'REGENCY CAKESTAND 3 TIER'
 'MULTICOLOUR HONEYCOMB FAN' 'RED RETROSPOT CAKE STAND'
 'PACK OF 12 WOODLAND TISSUES' 'PACK OF 6 PANNETONE GIFT BOXES'
 'PANTRY WASHING UP BRUSH' 'SET/6 RED SPOTTY PAPER CUPS'
 'RED BABY BUNTING' 'COFFEE MUG PEARS  DESIGN' 'HOLIDAY FUN LUDO'
 'ANT COPPER TURQ BOUDICCA BRACELET' 'ROUND SNACK BOXES SET OF 4 FRUITS'
 'TRADITIONAL PICK UP STICKS GAME' 'FUNKY DIVA PEN'
 'BREAD BIN DINER STYLE PINK' 'PANTRY CHOPPING BOARD'
 'SET 2 PANTRY DESIGN TEA TOWELS' 'SPACEBOY TV DINNER TRAY'
 'EMBROIDERED RIBBON REEL DAISY' 'KIDS RAIN MAC BLUE'
 'WHITE SPOT RED CERAMIC DRAWER KNOB' 'CHILDS BREAKFAST SET DOLLY GIRL'
 'LUNCH BAG WOODLAND' 'LUNCH BAG APPLE DESIGN'
 'LIGHT GARLAND BUTTERFILES PINK' 'CHILDS BREAKFAST SET SPACEBOY'
 'ROLL WRAP VINTAGE CHRISTMAS' 'MINI PLAYING CARDS GYMKHANA'
 'SET OF 72 RETROSPOT PAPER  DOILIES' 'RED KUKUI COCONUT SEED NECKLACE'
 'HOME SWEET HOME METAL SIGN' 'METAL 4 HOOK HANGER FRENCH CHATEAU'
 'GIFT BAG PSYCHEDELIC APPLES' 'ASS FLORAL PRINT MULTI SCREWDRIVER'
 'ZINC WILLIE WINKIE  CANDLE STICK' 'HEART WOODEN CHRISTMAS DECORATION'
 'SET/10 PINK POLKADOT PARTY CANDLES' 'STOOL HOME SWEET HOME'
 'MAGIC DRAWING SLATE DOLLY GIRL' 'CACTI T-LIGHT CANDLES'
 'SET/6 COLLAGE PAPER CUPS' 'EDWARDIAN PARASOL BLACK'
 'SMALL RED RETROSPOT WINDMILL' 'LONDON BUS COFFEE MUG'
 'SET OF 6 T-LIGHTS CACTI' 'ROMANTIC IMAGES GIFT WRAP SET'
 'LUNCH BAG PAISLEY PARK' 'WOODEN SKITTLES GARDEN SET'
 'RED RETROSPOT OVEN GLOVE' 'SET OF 6 SNACK LOAF BAKING CASES'
 'FELTCRAFT CUSHION OWL' 'PINK PARTY BAGS'
 'SET/10 RED POLKADOT PARTY CANDLES' 'SET 2 TEA TOWELS I LOVE LONDON'
 'RED RETROSPOT CHILDRENS UMBRELLA' 'CHILDRENS APRON SPACEBOY DESIGN'
 'RED ROCKING HORSE HAND PAINTED' 'CHARLIE & LOLA WASTEPAPER BIN FLORA'
 'SET OF 12 FAIRY CAKE BAKING CASES' 'JAM JAR WITH PINK LID'
 'RED TOADSTOOL LED NIGHT LIGHT' 'WHITE ROCKING HORSE HAND PAINTED'
 'SET OF 3 REGENCY CAKE TINS' 'SOLDIERS EGG CUP'
 'SET/20 RED RETROSPOT PAPER NAPKINS' 'BLUE POLKADOT WRAP'
 '12 PENCILS SMALL TUBE SKULL' 'BLUE ROSE FABRIC MIRROR'
 'RIBBON REEL LACE DESIGN' 'RABBIT NIGHT LIGHT' 'SPACEBOY MINI BACKPACK'
 'PINK BABY BUNTING' 'PACK OF 12 COLOURED PENCILS'
 'PINK FAIRY CAKE CHILDRENS APRON' 'PACK OF 60 MUSHROOM CAKE CASES'
 'WOODLAND PARTY BAG + STICKER SET' 'COFFEE MUG CAT + BIRD DESIGN'
 'MINI JIGSAW SPACEBOY' 'LUNCH BAG SPACEBOY DESIGN'
 'RETROSPOT PARTY BAG + STICKER SET' 'CREAM FELT EASTER EGG BASKET'
 'TREASURE TIN GYMKHANA DESIGN' 'WRAP RED VINTAGE DOILY'
 'REGENCY SUGAR BOWL GREEN' 'GROW YOUR OWN PLANT IN A CAN'
 'CARD DOLLY GIRL' 'PINK POLKADOT BOWL' 'MAGNETS PACK OF 4 SWALLOWS'
 'CHARLOTTE BAG PINK POLKADOT' 'WRAP ALPHABET DESIGN'
 '10 COLOUR SPACEBOY PEN' 'DOORMAT BLACK FLOCK'
 'GYMKHANA TREASURE BOOK BOX' '6 GIFT TAGS VINTAGE CHRISTMAS'
 'RED HEART SHAPE LOVE BUCKET' 'JUNGLE POPSICLES ICE LOLLY MOULDS'
 'BASKET OF TOADSTOOLS' 'SMALL POPCORN HOLDER'
 'CARDHOLDER GINGHAM CHRISTMAS TREE' 'JUMBO STORAGE BAG SUKI'
 '5 HOOK HANGER RED MAGIC TOADSTOOL' 'PINK REGENCY TEACUP AND SAUCER'
 'WHITE HEART CONFETTI IN TUBE' 'LUNCH BAG SUKI  DESIGN'
 'TRADITIONAL WOODEN SKIPPING ROPE' 'DOORMAT UNION FLAG'
 'UNION STRIPE WITH FRINGE  HAMMOCK' 'RED SPOTTY BISCUIT TIN'
 'SET OF 6 TEA TIME BAKING CASES' 'DOLLY HONEYCOMB GARLAND'
 'VINTAGE CHRISTMAS STOCKING' 'SQUARECUSHION COVER PINK UNION FLAG'
 'BLUE POLKADOT PLATE' 'BLUE CHARLIE+LOLA PERSONAL DOORSIGN'
 'FAIRY TALE COTTAGE NIGHT LIGHT' 'SET 3 RETROSPOT TEA,COFFEE,SUGAR'
 'REGENCY MILK JUG PINK' 'CARD CIRCUS PARADE' 'JUMBO BAG SPACEBOY DESIGN'
 'SET 8 CANDLES VINTAGE DOILY' 'REGENCY TEA PLATE PINK'
 'PAPER BUNTING WHITE LACE' 'RED LOVE HEART SHAPE CUP'
 'STAR DECORATION PAINTED ZINC' 'CORONA MEXICAN TRAY'
 'CUSHION COVER PINK UNION JACK' 'COWBOYS AND INDIANS BIRTHDAY CARD'
 'GIRAFFE WOODEN RULER' 'VINTAGE CHRISTMAS GIFT BAG LARGE'
 'FELTCRAFT PRINCESS CHARLOTTE DOLL' 'SET OF 4 KNICK KNACK TINS LEAVES'
 'HEN HOUSE W CHICK STANDING' 'PACK OF 12 CIRCUS PARADE TISSUES'
 'YELLOW GIANT GARDEN THERMOMETER' 'SET OF 6 RIBBONS VINTAGE CHRISTMAS'
 'PINK & WHITE BREAKFAST TRAY' 'BLUE & WHITE BREAKFAST TRAY'
 'PINK BUTTERFLY CUSHION COVER' 'BIRDS MOBILE VINTAGE DESIGN'
 'DINOSAUR KEYRINGS ASSORTED' 'CHILDRENS CUTLERY SPACEBOY'
 'MILK PAN RED RETROSPOT' 'BAKING SET 9 PIECE RETROSPOT'
 'RECYCLED ACAPULCO MAT PINK' 'ASSORTED COLOUR LIZARD SUCTION HOOK'
 'GREEN POLKADOT BOWL' 'TOY TIDY SPACEBOY'
 'PACK OF 60 SPACEBOY CAKE CASES' 'ROUND SNACK BOXES SET OF4 WOODLAND'
 '12 PENCILS TALL TUBE SKULLS' 'ICE CREAM SUNDAE LIP GLOSS'
 'LARGE HEART MEASURING SPOONS' 'PACK OF 72 SKULL CAKE CASES'
 'CLASSIC FRENCH STYLE BASKET NATURAL' 'RED RETROSPOT CHARLOTTE BAG'
 'WATERING CAN GREEN DINOSAUR' 'MEASURING TAPE BABUSHKA BLUE'
 'SET/2 RED RETROSPOT TEA TOWELS' 'MIRRORED WALL ART POPPIES'
 'BLUE 3 PIECE POLKADOT CUTLERY SET' 'APPLE BATH SPONGE'
 'RECYCLED ACAPULCO MAT GREEN' 'RED RETROSPOT CUP'
 '36 PENCILS TUBE WOODLAND' 'BLUE POLKADOT CUP' 'RED RETROSPOT BOWL'
 'PACK OF 60 SPACEBOY CAK']

In [ ]:
# df.invoicedate.str.replace('11 ', '2011').str.replace('10 ', '2010').str.strip()

In [50]:
a_befor = '15/4/11'

a = '15/4/11'

a = a.split('/')

a[-1] = '2011'

a_after = '/'.join(a)
print(f"""
      Before: {a_befor}
      After: {a_after}""")

      Before: 15/4/11
      After: 15/4/2011

In [57]:
a = '15/4/11'

a = a.split('/')
a[-1] = '20' + a[-1]
a_2 = '/'.join(a)
a_2

'15/4/2011'

In [60]:
df.invoicedate[0]

'7/4/11'

In [61]:
def clean_invoicedate(x):

    x = x.split('/')
    x[-1] = '20' + x[-1]
    x = '/'.join(x)
    return x

df.invoicedate = df.invoicedate.apply(clean_invoicedate)
df.invoicedate

0        7/4/2011
1      15/11/2011
2       27/4/2011
3      31/10/2011
4      17/12/2010
          ...
695     23/8/2011
696     13/5/2011
697     23/8/2011
698     13/5/2011
699     23/8/2011
Name: invoicedate, Length: 700, dtype: object

In [ ]:
# df['invoiceDateTime'] = df.invoicedate + ' ' + df.invoicetime
# df['invoiceDateTime']

In [ ]:
# pd.to_datetime(df.invoiceDateTime, format= "%d/%m/%Y %H:%M").dt.minute

In [62]:
df.head()

,invoiceno,unitprice,ordervalue,quantit,country,invoicedate,invoicetime,year-month,major_category,minor_category,description
0,549185,0.85,10.20,12,United Kingdom,7/4/2011,09:35,2011-04,Clothes,Tops,PACK OF 20 NAPKINS PANTRY DESIGN
1,576381,2.95,35.40,12,United Kingdom,15/11/2011,09:26,2011-11,Clothes,Shoes,NATURAL SLATE HEART CHALKBOARD
2,551192,1.25,20.00,16,United Kingdom,27/4/2011,10:54,2011-04,Kitchen,Cutlery,36 PENCILS TUBE SKULLS
3,573553,7.46,7.46,1,United Kingdom,31/10/2011,13:48,2011-10,Garden,Turf,SET 6 SCHOOL MILK BOTTLES IN CRATE
4,539436,2.51,2.51,1,United Kingdom,17/12/2010,14:49,2010-12,Garden,Hoses,FINE WICKER HEART

In [63]:
df.invoicedate = pd.to_datetime(df.invoicedate, format= "%d/%m/%Y")
df.invoicedate

0     2011-04-07
1     2011-11-15
2     2011-04-27
3     2011-10-31
4     2010-12-17
         ...
695   2011-08-23
696   2011-05-13
697   2011-08-23
698   2011-05-13
699   2011-08-23
Name: invoicedate, Length: 700, dtype: datetime64[ns]

In [65]:
df['year'] = df.invoicedate.dt.year
df['year']

0      2011
1      2011
2      2011
3      2011
4      2010
       ...
695    2011
696    2011
697    2011
698    2011
699    2011
Name: year, Length: 700, dtype: int32

In [64]:
df['year'] = df.invoicedate.dt.year

df['month'] = df.invoicedate.dt.month_name()

df['day'] = df.invoicedate.dt.day

In [66]:
df.head()

,invoiceno,unitprice,ordervalue,quantit,country,invoicedate,invoicetime,year-month,major_category,minor_category,description,year,month,day
0,549185,0.85,10.20,12,United Kingdom,2011-04-07,09:35,2011-04,Clothes,Tops,PACK OF 20 NAPKINS PANTRY DESIGN,2011,April,7
1,576381,2.95,35.40,12,United Kingdom,2011-11-15,09:26,2011-11,Clothes,Shoes,NATURAL SLATE HEART CHALKBOARD,2011,November,15
2,551192,1.25,20.00,16,United Kingdom,2011-04-27,10:54,2011-04,Kitchen,Cutlery,36 PENCILS TUBE SKULLS,2011,April,27
3,573553,7.46,7.46,1,United Kingdom,2011-10-31,13:48,2011-10,Garden,Turf,SET 6 SCHOOL MILK BOTTLES IN CRATE,2011,October,31
4,539436,2.51,2.51,1,United Kingdom,2010-12-17,14:49,2010-12,Garden,Hoses,FINE WICKER HEART,2010,December,17

In [67]:
df_1 = df[['invoiceno', 'unitprice', 'ordervalue', 'quantit', 'country','invoicedate']]
df_2 = df[['year', 'month', 'day']]
df_3 = df[['invoicetime', 'year-month', 'major_category', 'minor_category', 'description']]
df_3

,invoicetime,year-month,major_category,minor_category,description
0,09:35,2011-04,Clothes,Tops,PACK OF 20 NAPKINS PANTRY DESIGN
1,09:26,2011-11,Clothes,Shoes,NATURAL SLATE HEART CHALKBOARD
2,10:54,2011-04,Kitchen,Cutlery,36 PENCILS TUBE SKULLS
3,13:48,2011-10,Garden,Turf,SET 6 SCHOOL MILK BOTTLES IN CRATE
4,14:49,2010-12,Garden,Hoses,FINE WICKER HEART
...,...,...,...,...,...
695,09:38,2011-08,Clothes,Tops,WOOD STAMP SET THANK YOU
696,14:09,2011-05,Garden,Hoses,GREEN POLKADOT BOWL
697,09:38,2011-08,Garden,Rakes,TOY TIDY SPACEBOY
698,14:09,2011-05,Kitchen,Cooking Knives,RED RETROSPOT CHILDRENS UMBRELLA
699,09:38,2011-08,Clothes,Tops,PACK OF 60 SPACEBOY CAK

In [68]:
df_new = pd.concat([df_1, df_2, df_3], axis= 1)
df_new

,invoiceno,unitprice,ordervalue,quantit,country,invoicedate,year,month,day,invoicetime,year-month,major_category,minor_category,description
0,549185,0.85,10.20,12,United Kingdom,2011-04-07,2011,April,7,09:35,2011-04,Clothes,Tops,PACK OF 20 NAPKINS PANTRY DESIGN
1,576381,2.95,35.40,12,United Kingdom,2011-11-15,2011,November,15,09:26,2011-11,Clothes,Shoes,NATURAL SLATE HEART CHALKBOARD
2,551192,1.25,20.00,16,United Kingdom,2011-04-27,2011,April,27,10:54,2011-04,Kitchen,Cutlery,36 PENCILS TUBE SKULLS
3,573553,7.46,7.46,1,United Kingdom,2011-10-31,2011,October,31,13:48,2011-10,Garden,Turf,SET 6 SCHOOL MILK BOTTLES IN CRATE
4,539436,2.51,2.51,1,United Kingdom,2010-12-17,2010,December,17,14:49,2010-12,Garden,Hoses,FINE WICKER HEART
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,564087,1.25,20.00,16,Hong Kong,2011-08-23,2011,August,23,09:38,2011-08,Clothes,Tops,WOOD STAMP SET THANK YOU
696,553148,0.55,13.20,24,Hong Kong,2011-05-13,2011,May,13,14:09,2011-05,Garden,Hoses,GREEN POLKADOT BOWL
697,564087,4.95,29.70,6,Hong Kong,2011-08-23,2011,August,23,09:38,2011-08,Garden,Rakes,TOY TIDY SPACEBOY
698,553148,0.85,27.20,32,Hong Kong,2011-05-13,2011,May,13,14:09,2011-05,Kitchen,Cooking Knives,RED RETROSPOT CHILDRENS UMBRELLA
699,564087,1.25,20.00,16,Hong Kong,2011-08-23,2011,August,23,09:38,2011-08,Clothes,Tops,PACK OF 60 SPACEBOY CAK

In [80]:
my_year = list(df_2['year'])
my_year

[2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2010,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2010,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2010,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011]

In [74]:
df.invoicetime[0][0:2]

'09'

In [75]:
df['hour'] = df.invoicetime.apply(lambda x : x[0:2])
df['hour']

0      09
1      09
2      10
3      13
4      14
       ..
695    09
696    14
697    09
698    14
699    09
Name: hour, Length: 700, dtype: object

In [81]:
num_cols = df.select_dtypes(include= ['int', 'float']).columns[1:]

for col in num_cols:
    print(f"this is {col} column")
    px.histogram(df[col], title= col).show()

this is unitprice column

this is ordervalue column

this is quantit column

this is year column

this is day column

In [82]:
df[df.quantit > 200]

,invoiceno,unitprice,ordervalue,quantit,country,invoicedate,invoicetime,year-month,major_category,minor_category,description,year,month,day,hour
263,543057,1.06,445.20,420,United Kingdom,2011-02-03,10:50,2011-02,Household,Curtains,ANT COPPER TURQ BOUDICCA BRACELET,2011,February,3,10
312,552978,0.65,390.00,600,Germany,2011-05-12,14:46,2011-05,Garden,Seeds,ROUND SNACK BOXES SET OF 4 FRUITS,2011,May,12,14
519,564897,1.79,515.52,288,France,2011-08-31,11:22,2011-08,Garden,Turf,12 PENCILS TALL TUBE SKULLS,2011,August,31,11
544,556463,0.19,68.40,360,France,2011-06-12,10:47,2011-06,Garden,Hoses,36 PENCILS TUBE WOODLAND,2011,June,12,10
611,559919,1.04,399.36,384,Australia,2011-07-13,15:30,2011-07,Kitchen,Cutlery,CLASSIC FRENCH STYLE BASKET NATURAL,2011,July,13,15
619,565145,0.55,633.60,1152,Australia,2011-09-01,13:50,2011-09,Garden,Seeds,SET/2 RED RETROSPOT TEA TOWELS,2011,September,1,13
630,556917,0.34,136.00,400,Australia,2011-06-15,13:37,2011-06,Kitchen,Bowls,RETROSPOT HEART HOT WATER BOTTLE,2011,June,15,13
646,545475,0.25,108.00,432,Australia,2011-03-03,10:59,2011-03,Clothes,Tops,WOOD STAMP SET THANK YOU,2011,March,3,10

In [ ]:
# Aggregation functions

# min()
# max()
# sum()
# mean()
# count()

In [83]:
cat_count = df.groupby('major_category')['invoiceno'].count().sort_values(ascending= False).reset_index()
cat_count

  major_category  invoiceno
0         Garden        189
1        Clothes        176
2        Kitchen        172
3      Household        163

In [86]:
px.pie(cat_count, names= 'major_category', values= 'invoiceno', title= 'Total Orders Per Category')

In [87]:
# get the total order value per month

cat_month = df.groupby('month')['ordervalue'].sum().sort_values(ascending= False).reset_index()
cat_month

        month  ordervalue
0    November     2553.74
1         May     2394.34
2   September     2339.75
3      August     2327.19
4       March     2324.19
5     January     2080.25
6        June     1878.89
7    February     1758.76
8        July     1562.23
9     October     1382.54
10   December     1194.22
11      April      588.83

In [90]:
px.bar(cat_month, x = 'month', y= 'ordervalue')

In [91]:
df['major_category'].unique()

array(['Clothes', 'Kitchen', 'Garden', 'Household'], dtype=object)

In [88]:
cat_value = df.groupby('major_category')['ordervalue'].sum().sort_values(ascending= False).reset_index()
cat_value

  major_category  ordervalue
0        Kitchen     6407.90
1         Garden     6040.08
2      Household     4986.58
3        Clothes     4950.37

In [89]:
px.bar(cat_value, x= 'major_category', y= 'ordervalue', title= 'Total Order Value Per Category')