## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Reading Data

In [2]:
df = pd.read_csv('imdb_movies (1).csv')
df

,ranking of movie,movie name,Year,certificate,runtime,genre,RATING,DETAIL ABOUT MOVIE,DIRECTOR,ACTOR 1,ACTOR 2,ACTOR 3,ACTOR 4,votes,metascore,GROSS COLLECTION
0,1,Jai Bhim,-2021,TV-MA,164 min,"Crime, Drama",9.4,When a tribal man is arrested for a case of al...,T.J. Gnanavel,Suriya,Lijo Mol Jose,Manikandan,Rajisha Vijayan,163431,NaN,NaN
1,2,The Shawshank Redemption,-1994,R,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2515762,80.0,$28.34M
2,3,The Godfather,-1972,R,175 min,"Crime, Drama",9.2,"The Godfather follows Vito Corleone, Don of th...",Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1732749,100.0,$134.97M
3,4,The Dark Knight,-2008,PG-13,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2466041,84.0,$534.86M
4,5,The Godfather: Part II,-1974,R,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1202401,90.0,$57.30M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,Mr. Smith Goes to Washington,-1939,Passed,129 min,"Comedy, Drama",8.1,A naive youth leader is appointed to fill a va...,Frank Capra,James Stewart,Jean Arthur,Claude Rains,Edward Arnold,112642,73.0,$9.60M
246,247,Gone with the Wind,-1939,Passed,238 min,"Drama, History, Romance",8.1,The manipulative daughter of a Georgia plantat...,Victor Fleming,George Cukor,Sam Wood,Clark Gable,Vivien Leigh,304725,97.0,$198.68M
247,248,It Happened One Night,-1934,Passed,105 min,"Comedy, Romance",8.1,A renegade reporter trailing a young runaway h...,Frank Capra,Clark Gable,Claudette Colbert,Walter Connolly,Roscoe Karns,100198,87.0,$4.36M
248,249,The Passion of Joan of Arc,-1928,Passed,114 min,"Biography, Drama, History",8.1,"In 1431, Jeanne d'Arc is placed on trial on ch...",Carl Theodor Dreyer,Maria Falconetti,Eugene Silvain,André Berley,Maurice Schutz,52264,NaN,$0.02M
249,250,The General,-1926,Passed,67 min,"Action, Adventure, Comedy",8.1,After being rejected by the Confederate milita...,Clyde Bruckman,Buster Keaton,Buster Keaton,Marion Mack,Glen Cavender,88022,NaN,$1.03M

### Data Understanding

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ranking of movie    250 non-null    int64
 1   movie name          250 non-null    object
 2   Year                250 non-null    object
 3   certificate         250 non-null    object
 4   runtime             250 non-null    object
 5   genre               250 non-null    object
 6   RATING              250 non-null    float64
 7   DETAIL ABOUT MOVIE  250 non-null    object
 8   DIRECTOR            250 non-null    object
 9   ACTOR 1             250 non-null    object
 10  ACTOR 2             250 non-null    object
 11  ACTOR 3             250 non-null    object
 12  ACTOR 4             250 non-null    object
 13  votes               250 non-null    int64
 14  metascore           218 non-null    float64
 15  GROSS COLLECTION    214 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 31.4+ KB

In [3]:
False + True

1

In [4]:
df.shape[0]

250

In [5]:
(df.isna().sum() / df.shape[0]) * 100

ranking of movie       0.0
movie name             0.0
Year                   0.0
certificate            0.0
runtime                0.0
genre                  0.0
RATING                 0.0
DETAIL ABOUT MOVIE     0.0
DIRECTOR               0.0
ACTOR 1                0.0
ACTOR 2                0.0
ACTOR 3                0.0
ACTOR 4                0.0
votes                  0.0
metascore             12.8
GROSS COLLECTION      14.4
dtype: float64

In [6]:
# For Numerical Columns
df.describe()

       ranking of movie      RATING         votes   metascore
count        250.000000  250.000000  2.500000e+02  218.000000
mean         125.500000    8.308400  5.785299e+05   82.449541
std           72.312977    0.234669  4.951304e+05   10.822392
min            1.000000    8.100000  2.653800e+04   55.000000
25%           63.250000    8.100000  1.688628e+05   75.000000
50%          125.500000    8.200000  4.313355e+05   84.000000
75%          187.750000    8.400000  8.854255e+05   90.000000
max          250.000000    9.400000  2.515762e+06  100.000000

In [7]:
# For Categorical Columns
df.describe(include= 'object')

,movie name,Year,certificate,runtime,genre,DETAIL ABOUT MOVIE,DIRECTOR,ACTOR 1,ACTOR 2,ACTOR 3,ACTOR 4,GROSS COLLECTION
count,250,250,250,250,250,250,250,250,250,250,250,214
unique,250,90,11,102,109,250,154,185,233,241,242,204
top,Jai Bhim,-1995,R,130 min,Drama,When a tribal man is arrested for a case of al...,Christopher Nolan,Robert De Niro,Robert De Niro,Joe Pesci,Michael Caine,$4.36M
freq,1,8,106,9,22,1,7,6,3,3,2,3

## Drop Unnecessary Columns

In [8]:
df.drop('DETAIL ABOUT MOVIE', axis= 1, inplace= True)
df

,ranking of movie,movie name,Year,certificate,runtime,genre,RATING,DIRECTOR,ACTOR 1,ACTOR 2,ACTOR 3,ACTOR 4,votes,metascore,GROSS COLLECTION
0,1,Jai Bhim,-2021,TV-MA,164 min,"Crime, Drama",9.4,T.J. Gnanavel,Suriya,Lijo Mol Jose,Manikandan,Rajisha Vijayan,163431,NaN,NaN
1,2,The Shawshank Redemption,-1994,R,142 min,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2515762,80.0,$28.34M
2,3,The Godfather,-1972,R,175 min,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1732749,100.0,$134.97M
3,4,The Dark Knight,-2008,PG-13,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2466041,84.0,$534.86M
4,5,The Godfather: Part II,-1974,R,202 min,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1202401,90.0,$57.30M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,Mr. Smith Goes to Washington,-1939,Passed,129 min,"Comedy, Drama",8.1,Frank Capra,James Stewart,Jean Arthur,Claude Rains,Edward Arnold,112642,73.0,$9.60M
246,247,Gone with the Wind,-1939,Passed,238 min,"Drama, History, Romance",8.1,Victor Fleming,George Cukor,Sam Wood,Clark Gable,Vivien Leigh,304725,97.0,$198.68M
247,248,It Happened One Night,-1934,Passed,105 min,"Comedy, Romance",8.1,Frank Capra,Clark Gable,Claudette Colbert,Walter Connolly,Roscoe Karns,100198,87.0,$4.36M
248,249,The Passion of Joan of Arc,-1928,Passed,114 min,"Biography, Drama, History",8.1,Carl Theodor Dreyer,Maria Falconetti,Eugene Silvain,André Berley,Maurice Schutz,52264,NaN,$0.02M
249,250,The General,-1926,Passed,67 min,"Action, Adventure, Comedy",8.1,Clyde Bruckman,Buster Keaton,Buster Keaton,Marion Mack,Glen Cavender,88022,NaN,$1.03M

## Rename Columns in a suitable form

In [9]:
df.columns = df.columns.str.lower()
df.columns

Index(['ranking of movie', 'movie name ', 'year', 'certificate', 'runtime',
       'genre', 'rating', 'director ', 'actor 1', 'actor 2', 'actor 3',
       'actor 4', 'votes', 'metascore', 'gross collection'],
      dtype='object')

In [10]:
df.columns = df.columns.str.strip().str.replace(' ', '_')
df.columns

Index(['ranking_of_movie', 'movie_name', 'year', 'certificate', 'runtime',
       'genre', 'rating', 'director', 'actor_1', 'actor_2', 'actor_3',
       'actor_4', 'votes', 'metascore', 'gross_collection'],
      dtype='object')

In [11]:
df

,ranking_of_movie,movie_name,year,certificate,runtime,genre,rating,director,actor_1,actor_2,actor_3,actor_4,votes,metascore,gross_collection
0,1,Jai Bhim,-2021,TV-MA,164 min,"Crime, Drama",9.4,T.J. Gnanavel,Suriya,Lijo Mol Jose,Manikandan,Rajisha Vijayan,163431,NaN,NaN
1,2,The Shawshank Redemption,-1994,R,142 min,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2515762,80.0,$28.34M
2,3,The Godfather,-1972,R,175 min,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1732749,100.0,$134.97M
3,4,The Dark Knight,-2008,PG-13,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2466041,84.0,$534.86M
4,5,The Godfather: Part II,-1974,R,202 min,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1202401,90.0,$57.30M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,Mr. Smith Goes to Washington,-1939,Passed,129 min,"Comedy, Drama",8.1,Frank Capra,James Stewart,Jean Arthur,Claude Rains,Edward Arnold,112642,73.0,$9.60M
246,247,Gone with the Wind,-1939,Passed,238 min,"Drama, History, Romance",8.1,Victor Fleming,George Cukor,Sam Wood,Clark Gable,Vivien Leigh,304725,97.0,$198.68M
247,248,It Happened One Night,-1934,Passed,105 min,"Comedy, Romance",8.1,Frank Capra,Clark Gable,Claudette Colbert,Walter Connolly,Roscoe Karns,100198,87.0,$4.36M
248,249,The Passion of Joan of Arc,-1928,Passed,114 min,"Biography, Drama, History",8.1,Carl Theodor Dreyer,Maria Falconetti,Eugene Silvain,André Berley,Maurice Schutz,52264,NaN,$0.02M
249,250,The General,-1926,Passed,67 min,"Action, Adventure, Comedy",8.1,Clyde Bruckman,Buster Keaton,Buster Keaton,Marion Mack,Glen Cavender,88022,NaN,$1.03M

In [12]:
int('1990')

1990

In [13]:
if 'I' in '(I) (2020)':
    print('There is a bracket')

There is a bracket

In [14]:
def clean_year(x):

    if 'I' in x:
        return int(x.split()[1].replace('(', '').replace(')', ''))
        
    else:
        return int(x.replace('-', ''))

df['year'] = df['year'].apply(clean_year)
df['year']

0      2021
1      1994
2      1972
3      2008
4      1974
       ...
245    1939
246    1939
247    1934
248    1928
249    1926
Name: year, Length: 250, dtype: int64

In [15]:
df['year'].unique()

array([2021, 1994, 1972, 2008, 1974, 1957, 2003, 1993, 2010, 1999, 2001,
       1966, 2002, 1990, 1980, 1975, 2019, 2014, 1998, 1997, 1995, 1991,
       1977, 1962, 1954, 1946, 2011, 2006, 2000, 1988, 1985, 1968, 1960,
       1942, 1936, 1931, 2020, 2018, 2016, 2017, 2012, 2009, 2007, 1981,
       1979, 1963, 1964, 1955, 1950, 1940, 2004, 1992, 1987, 1986, 1984,
       1983, 1973, 1971, 1959, 1958, 1952, 1948, 1944, 1941, 1927, 1921,
       2013, 2005, 1996, 1989, 1978, 1976, 1969, 1965, 1961, 1953, 1925,
       1924, 2015, 1982, 1967, 1949, 1939, 1934, 1928, 1926])

In [16]:
df

,ranking_of_movie,movie_name,year,certificate,runtime,genre,rating,director,actor_1,actor_2,actor_3,actor_4,votes,metascore,gross_collection
0,1,Jai Bhim,2021,TV-MA,164 min,"Crime, Drama",9.4,T.J. Gnanavel,Suriya,Lijo Mol Jose,Manikandan,Rajisha Vijayan,163431,NaN,NaN
1,2,The Shawshank Redemption,1994,R,142 min,Drama,9.3,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2515762,80.0,$28.34M
2,3,The Godfather,1972,R,175 min,"Crime, Drama",9.2,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1732749,100.0,$134.97M
3,4,The Dark Knight,2008,PG-13,152 min,"Action, Crime, Drama",9.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2466041,84.0,$534.86M
4,5,The Godfather: Part II,1974,R,202 min,"Crime, Drama",9.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1202401,90.0,$57.30M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,246,Mr. Smith Goes to Washington,1939,Passed,129 min,"Comedy, Drama",8.1,Frank Capra,James Stewart,Jean Arthur,Claude Rains,Edward Arnold,112642,73.0,$9.60M
246,247,Gone with the Wind,1939,Passed,238 min,"Drama, History, Romance",8.1,Victor Fleming,George Cukor,Sam Wood,Clark Gable,Vivien Leigh,304725,97.0,$198.68M
247,248,It Happened One Night,1934,Passed,105 min,"Comedy, Romance",8.1,Frank Capra,Clark Gable,Claudette Colbert,Walter Connolly,Roscoe Karns,100198,87.0,$4.36M
248,249,The Passion of Joan of Arc,1928,Passed,114 min,"Biography, Drama, History",8.1,Carl Theodor Dreyer,Maria Falconetti,Eugene Silvain,André Berley,Maurice Schutz,52264,NaN,$0.02M
249,250,The General,1926,Passed,67 min,"Action, Adventure, Comedy",8.1,Clyde Bruckman,Buster Keaton,Buster Keaton,Marion Mack,Glen Cavender,88022,NaN,$1.03M

In [17]:
df['runtime'] = df['runtime'].apply(lambda x : int(x.replace(' min', '')))
df['runtime']

0      164
1      142
2      175
3      152
4      202
      ...
245    129
246    238
247    105
248    114
249     67
Name: runtime, Length: 250, dtype: int64

## What is the minimum and maximum ratings ?

In [18]:
df.rating.min()

8.1

In [19]:
df.rating.max()

9.4

## What are the movies with rating > 9 ?

In [20]:
df[df.rating > 9]['movie_name']

0                    Jai Bhim
1    The Shawshank Redemption
2               The Godfather
Name: movie_name, dtype: object

## Top 10 movies per metascore and user rating

In [21]:
df.columns

Index(['ranking_of_movie', 'movie_name', 'year', 'certificate', 'runtime',
       'genre', 'rating', 'director', 'actor_1', 'actor_2', 'actor_3',
       'actor_4', 'votes', 'metascore', 'gross_collection'],
      dtype='object')

In [22]:
df[['movie_name', 'rating', 'metascore']].sort_values(by= 'metascore', ascending= False).head(10)

              movie_name  rating  metascore
2          The Godfather     9.2      100.0
50            Casablanca     8.5      100.0
49           Rear Window     8.5      100.0
109   Lawrence of Arabia     8.3      100.0
117         Citizen Kane     8.3      100.0
112              Vertigo     8.3      100.0
224  Fanny and Alexander     8.1      100.0
52           City Lights     8.5       99.0
113  Singin' in the Rain     8.3       99.0
31         Seven Samurai     8.6       98.0

## Top 10 genres

In [23]:
df.groupby('genre')['genre'].count().sort_values(ascending= False).head(10)

genre
Drama                           22
Crime, Drama                    14
Biography, Drama, History        9
Crime, Drama, Mystery            8
Animation, Adventure, Comedy     8
Drama, War                       8
Action, Crime, Drama             7
Drama, Romance                   7
Action, Adventure, Drama         6
Crime, Drama, Thriller           5
Name: genre, dtype: int64

## Top 10 Directories

In [24]:
df.groupby('director')['director'].count().sort_values(ascending= False).head(10)

director
Akira Kurosawa       7
Christopher Nolan    7
Stanley Kubrick      7
Martin Scorsese      7
Alfred Hitchcock     6
Steven Spielberg     6
Hayao Miyazaki       5
Billy Wilder         5
Charles Chaplin      5
Ingmar Bergman       5
Name: director, dtype: int64

## Top 10 First Actors

In [25]:
df.groupby('actor_1')['actor_1'].count().sort_values(ascending= False).head(10)

actor_1
Robert De Niro       6
Leonardo DiCaprio    5
Tom Hanks            5
Charles Chaplin      5
Christian Bale       4
James Stewart        4
Clint Eastwood       4
Toshirô Mifune       4
Elijah Wood          3
Harrison Ford        3
Name: actor_1, dtype: int64

## Top 10 Second Actors

In [26]:
df.groupby('actor_2')['actor_2'].count().sort_values(ascending= False).head(10)

actor_2
Harrison Ford     3
Robert De Niro    3
Matt Damon        3
Brad Pitt         2
Grace Kelly       2
Ian McKellen      2
Liv Ullmann       2
Ed Harris         2
Alec Guinness     2
Joseph Cotten     2
Name: actor_2, dtype: int64