In [1]:
import numpy as np
import pandas as pd

In [2]:
task_1 = pd.DataFrame({'Scores' : ['56', '74', '63', '63', '72', '50', '63', '44', '80'],
                   'Rank' : [8, 3, 6, 2, 1, 13, 5, 13, 1],
                   'Years': ['2019', '2019', '2019', '2017', '2017', '2017', '2018', '2018', '2018'],
                   'Teams' : ['Corinthians', 'Palmeiras', 'So Paulo', 'Palmeiras', 'Corinthians', 'Sao Paulo', 'Sao Paulo', 'Corinthians', 'Palmeiras']})
task_1

  Scores  Rank Years        Teams
0     56     8  2019  Corinthians
1     74     3  2019    Palmeiras
2     63     6  2019     So Paulo
3     63     2  2017    Palmeiras
4     72     1  2017  Corinthians
5     50    13  2017    Sao Paulo
6     63     5  2018    Sao Paulo
7     44    13  2018  Corinthians
8     80     1  2018    Palmeiras

### Applting Functions on Dataframes

In [3]:
df = pd.DataFrame({'col1':[1,5,3,2,4],'col2':[444,222,666,444,555],'col3':['abc','xyz','ijklmn','xyz', 'defgh']})
df

   col1  col2    col3
0     1   444     abc
1     5   222     xyz
2     3   666  ijklmn
3     2   444     xyz
4     4   555   defgh

In [4]:
# Create Radius column from (col1 + 20)

df['radius'] = df['col1'] + 20
df

   col1  col2    col3  radius
0     1   444     abc      21
1     5   222     xyz      25
2     3   666  ijklmn      23
3     2   444     xyz      22
4     4   555   defgh      24

In [5]:
# Create Circle Area column

def circ_area(x):

    return 3.14 * (x ** 2)

df['circ_area'] = df['radius'].apply(circ_area)

In [6]:
# Create multiple columns from function

def circ_area_perimeter(x):

    return pd.Series([3.14 * (x ** 2), 2 * 3.14 * x])

In [7]:
df[['new_rea', 'new_permieter']] = df['radius'].apply(circ_area_perimeter)

In [8]:
df

   col1  col2    col3  radius  circ_area  new_rea  new_permieter
0     1   444     abc      21    1384.74  1384.74         131.88
1     5   222     xyz      25    1962.50  1962.50         157.00
2     3   666  ijklmn      23    1661.06  1661.06         144.44
3     2   444     xyz      22    1519.76  1519.76         138.16
4     4   555   defgh      24    1808.64  1808.64         150.72

In [9]:
# Create Circle Area column (Using lambda)

df['circ_area2'] = df['radius'].apply(lambda x : 3.14 * (x ** 2))

In [10]:
df

   col1  col2    col3  radius  circ_area  new_rea  new_permieter  circ_area2
0     1   444     abc      21    1384.74  1384.74         131.88     1384.74
1     5   222     xyz      25    1962.50  1962.50         157.00     1962.50
2     3   666  ijklmn      23    1661.06  1661.06         144.44     1661.06
3     2   444     xyz      22    1519.76  1519.76         138.16     1519.76
4     4   555   defgh      24    1808.64  1808.64         150.72     1808.64

In [11]:
# Apply built in functions with apply()

df['col3'].apply(len)

0    3
1    3
2    6
3    3
4    5
Name: col3, dtype: int64

In [12]:
df

   col1  col2    col3  radius  circ_area  new_rea  new_permieter  circ_area2
0     1   444     abc      21    1384.74  1384.74         131.88     1384.74
1     5   222     xyz      25    1962.50  1962.50         157.00     1962.50
2     3   666  ijklmn      23    1661.06  1661.06         144.44     1661.06
3     2   444     xyz      22    1519.76  1519.76         138.16     1519.76
4     4   555   defgh      24    1808.64  1808.64         150.72     1808.64

### Group By

In [13]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Sam','Sarah'],
       'Sales':[200,120,340,124,243,350],
       'Calls': [60,190,2,100,700,423]}

data = pd.DataFrame(data)
data

  Company   Person  Sales  Calls
0    GOOG      Sam    200     60
1    GOOG  Charlie    120    190
2    MSFT      Amy    340      2
3    MSFT  Vanessa    124    100
4      FB      Sam    243    700
5      FB    Sarah    350    423

In [14]:
data['Sales'].mean()

np.float64(229.5)

In [15]:
data

  Company   Person  Sales  Calls
0    GOOG      Sam    200     60
1    GOOG  Charlie    120    190
2    MSFT      Amy    340      2
3    MSFT  Vanessa    124    100
4      FB      Sam    243    700
5      FB    Sarah    350    423

In [16]:
data.groupby('Company').describe().T

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000
Calls count    2.000000    2.000000    2.000000
      mean   561.500000  125.000000   51.000000
      std    195.868578   91.923882   69.296465
      min    423.000000   60.000000    2.000000
      25%    492.250000   92.500000   26.500000
      50%    561.500000  125.000000   51.000000
      75%    630.750000  157.500000   75.500000
      max    700.000000  190.000000  100.000000

In [17]:
data.groupby('Company')['Sales'].mean().sort_values(ascending= False).head(2)

Company
FB      296.5
MSFT    232.0
Name: Sales, dtype: float64

### Task 1
##### The dataset below stores information about the Brazilian football championship, series A, between 2017 and 2019. Based on these data, answer:
* what is the average score of each team between 2017-2018?
* how many teams have been in the Top 5 each year?

In [39]:
df = pd.read_csv('C:/Users/hp/Desktop/01-Pandas/Tasks/Task_1.csv', index_col= 0)
df

   Scores  Rank  Years        Teams
0      56     8   2019  Corinthians
1      74     3   2019    Palmeiras
2      63     6   2019     So Paulo
3      63     2   2017    Palmeiras
4      72     1   2017  Corinthians
5      50    13   2017    Sao Paulo
6      63     5   2018    Sao Paulo
7      44    13   2018  Corinthians
8      80     1   2018    Palmeiras

In [45]:
df[df['Years'] <= 2018].groupby('Teams')['Scores'].mean().sort_values(ascending= False)

Teams
Palmeiras      71.5
Corinthians    58.0
Sao Paulo      56.5
Name: Scores, dtype: float64

In [47]:
df[df['Rank'] <= 5]

   Scores  Rank  Years        Teams
1      74     3   2019    Palmeiras
3      63     2   2017    Palmeiras
4      72     1   2017  Corinthians
6      63     5   2018    Sao Paulo
8      80     1   2018    Palmeiras

In [53]:
df[df['Rank'] <= 5].groupby(['Years', 'Teams', 'Rank'])['Teams'].count()

Years  Teams        Rank
2017   Corinthians  1       1
       Palmeiras    2       1
2018   Palmeiras    1       1
       Sao Paulo    5       1
2019   Palmeiras    3       1
Name: Teams, dtype: int64

### Concatenation

In [18]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [19]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [20]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [21]:
pd.concat([df1, df2, df3], axis= 0)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [22]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [23]:
df2 = pd.DataFrame({'E': ['A4', 'A5', 'A6', 'A7'],
                        'F': ['B4', 'B5', 'B6', 'B7'],
                        'G': ['C4', 'C5', 'C6', 'C7'],
                        'H': ['D4', 'D5', 'D6', 'D7']},
                         index=[0, 1, 2, 3]) 
df2

    E   F   G   H
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [24]:
df3 = pd.DataFrame({'I': ['A8', 'A9', 'A10', 'A11', 'A12'],
                        'J': ['B8', 'B9', 'B10', 'B11', 'B12'],
                        'K': ['C8', 'C9', 'C10', 'C11', 'C12'],
                        'L': ['D8', 'D9', 'D10', 'D11', 'D12'],},
                        index=[0, 1, 2, 3, 4])
df3

     I    J    K    L
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11
4  A12  B12  C12  D12

In [25]:
pd.concat([df1, df2, df3], axis= 1)

     A    B    C    D    E    F    G    H    I    J    K    L
0   A0   B0   C0   D0   A4   B4   C4   D4   A8   B8   C8   D8
1   A1   B1   C1   D1   A5   B5   C5   D5   A9   B9   C9   D9
2   A2   B2   C2   D2   A6   B6   C6   D6  A10  B10  C10  D10
3   A3   B3   C3   D3   A7   B7   C7   D7  A11  B11  C11  D11
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A12  B12  C12  D12

### Merge

In [26]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3', 'k4'],
                          'C': ['C0', 'C1', 'C2', 'C3', 'C4'],
                          'D': ['D0', 'D1', 'D2', 'D3', 'D4']})

In [27]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [28]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3
4  k4  C4  D4

In [29]:
pd.merge(left, right, on= 'key', how= 'outer')

  key    A    B   C   D
0  K0   A0   B0  C0  D0
1  K1   A1   B1  C1  D1
2  K2   A2   B2  C2  D2
3  K3   A3   B3  C3  D3
4  k4  NaN  NaN  C4  D4

### Joining

In [30]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [31]:
df2 = pd.DataFrame({'E': ['A4', 'A5', 'A6', 'A7'],
                        'F': ['B4', 'B5', 'B6', 'B7'],
                        'G': ['C4', 'C5', 'C6', 'C7'],
                        'H': ['D4', 'D5', 'D6', 'D7']},
                         index=[0, 1, 2, 3])
df2

    E   F   G   H
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [32]:
df3 = pd.DataFrame({'I': ['A8', 'A9', 'A10', 'A11'],
                        'J': ['B8', 'B9', 'B10', 'B11'],
                        'K': ['C8', 'C9', 'C10', 'C11'],
                        'L': ['D8', 'D9', 'D10', 'D11']},
                        index=[0, 1, 2, 3])
df3

     I    J    K    L
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [33]:
df3.index

Index([0, 1, 2, 3], dtype='int64')

In [34]:
final_df = df1.join(df2, how= 'inner').join(df3, how='inner')
final_df

    A   B   C   D   E   F   G   H    I    J    K    L
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11