### Load Necessary Libraries

In [63]:
import numpy as np
import pandas as pd
import plotly.express as px

### Data Loading

In [64]:
df = pd.read_csv('Sales.csv')
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,295665,Macbook Pro Laptop,1,1700$,12/30/19 00:01,"136 Church St, New York City, NY 10001"
1,295666,LG Washing Machine,1,600.0$,12/29/19 07:03,"562 2nd St, New York City, NY 10001"
2,295667,USB-C Charging Cable,1,11.95$,12/12/19 18:21,"277 Main St, New York City, NY 10001"
3,295668,27in FHD Monitor,1,149.99$,12/22/19 15:13,"410 6th St, San Francisco, CA 94016"
4,295669,USB-C Charging Cable,1,11.95$,12/18/19 12:38,"43 Hill St, Atlanta, GA 30301"
...,...,...,...,...,...,...
25112,319666,Lightning Charging Cable,1,14.95$,12/11/19 20:58,"14 Madison St, San Francisco, CA 94016"
25113,319667,AA Batteries (4-pack),2,3.84$,12/01/19 12:01,"549 Willow St, Los Angeles, CA 90001"
25114,319668,Vareebadd Phone,1,400$,12/09/19 06:43,"273 Wilson St, Seattle, WA 98101"
25115,319669,Wired Headphones,1,11.99$,12/03/19 10:39,"778 River St, Dallas, TX 75001"
25116,319670,Bose SoundSport Headphones,1,99.99$,12/21/19 21:45,"747 Chestnut St, Los Angeles, CA 90001"

# Data Exploration

In [65]:
# Check datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25117 entries, 0 to 25116
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          25037 non-null  object
 1   Product           25037 non-null  object
 2   Quantity Ordered  25037 non-null  object
 3   Price Each        25117 non-null  object
 4   Order Date        25037 non-null  object
 5   Purchase Address  25037 non-null  object
dtypes: object(6)
memory usage: 1.1+ MB

In [66]:
# Check summary statistics

df.describe(include= 'O')

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
count,25037,25037,25037,25117,25037,25037
unique,24007,20,8,20,17306,23215
top,Order ID,USB-C Charging Cable,1,11.95$,Order Date,Purchase Address
freq,48,2981,22641,2981,48,48

In [67]:
# Check dupicates
df.duplicated().sum()

166

In [68]:
df.drop_duplicates(inplace= True, ignore_index= True)

In [69]:
df.duplicated().sum()

0

In [70]:
# Check Missing Values
df.isna().sum()

Order ID            1
Product             1
Quantity Ordered    1
Price Each          0
Order Date          1
Purchase Address    1
dtype: int64

In [71]:
df.isna()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
24946,False,False,False,False,False,False
24947,False,False,False,False,False,False
24948,False,False,False,False,False,False
24949,False,False,False,False,False,False
24950,False,False,False,False,False,False

In [72]:
df[df['Order ID'].isna()]

    Order ID Product Quantity Ordered Price Each Order Date Purchase Address
264      NaN     NaN              NaN       nan$        NaN              NaN

In [73]:
df.dropna(inplace= True, ignore_index= True)

In [74]:
df.isna().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

# Data Cleaning

In [75]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,295665,Macbook Pro Laptop,1,1700$,12/30/19 00:01,"136 Church St, New York City, NY 10001"
1,295666,LG Washing Machine,1,600.0$,12/29/19 07:03,"562 2nd St, New York City, NY 10001"
2,295667,USB-C Charging Cable,1,11.95$,12/12/19 18:21,"277 Main St, New York City, NY 10001"
3,295668,27in FHD Monitor,1,149.99$,12/22/19 15:13,"410 6th St, San Francisco, CA 94016"
4,295669,USB-C Charging Cable,1,11.95$,12/18/19 12:38,"43 Hill St, Atlanta, GA 30301"

In [76]:
for col in df.columns:

    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 100)

Order ID
24007
['295665' '295666' '295667' ... '319668' '319669' '319670']
----------------------------------------------------------------------------------------------------
Product
20
['Macbook Pro Laptop' 'LG Washing Machine' 'USB-C Charging Cable'
 '27in FHD Monitor' 'AA Batteries (4-pack)' 'Bose SoundSport Headphones'
 'AAA Batteries (4-pack)' 'ThinkPad Laptop' 'Lightning Charging Cable'
 'Google Phone' 'Wired Headphones' 'Apple Airpods Headphones'
 'Vareebadd Phone' 'iPhone' '20in Monitor' '34in Ultrawide Monitor'
 'Flatscreen TV' '27in 4K Gaming Monitor' 'Product' 'LG Dryer']
----------------------------------------------------------------------------------------------------
Quantity Ordered
8
['1' '2' '4' '3' 'Quantity Ordered' '7' '5' '6']
----------------------------------------------------------------------------------------------------
Price Each
19
['1700$' '600.0$' '11.95$' '149.99$' '3.84$' '99.99$' '2.99$' '999.99$'
 '14.95$' '600$' '11.99$' '150$' '400$' '700$' '109.99$' '379.99$' '300$'
 '389.99$' 'Price Each$']
----------------------------------------------------------------------------------------------------
Order Date
17306
['12/30/19 00:01' '12/29/19 07:03' '12/12/19 18:21' ... '12/01/19 12:01'
 '12/09/19 06:43' '12/03/19 10:39']
----------------------------------------------------------------------------------------------------
Purchase Address
23215
['136 Church St, New York City, NY 10001'
 '562 2nd St, New York City, NY 10001'
 '277 Main St, New York City, NY 10001' ...
 '273 Wilson St, Seattle, WA 98101' '778 River St, Dallas, TX 75001'
 '747 Chestnut St, Los Angeles, CA 90001']
----------------------------------------------------------------------------------------------------

In [77]:
# pd.to_datetime(df['Order Date'])

In [78]:
df.iloc[253:255]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
253,295901,20in Monitor,1,109.99$,12/05/19 20:02,"67 12th St, San Francisco, CA 94016"
254,Order ID,Product,Quantity Ordered,Price Each$,Order Date,Purchase Address

In [79]:
df.drop(254, axis= 0, inplace= True)

df.reset_index(inplace= True, drop= True)

In [80]:
'12/30/19 00:01'.split('/')[2].split()[0]

'19'

In [81]:
df['Order Date']

0        12/30/19 00:01
1        12/29/19 07:03
2        12/12/19 18:21
3        12/22/19 15:13
4        12/18/19 12:38
              ...
24944    12/11/19 20:58
24945    12/01/19 12:01
24946    12/09/19 06:43
24947    12/03/19 10:39
24948    12/21/19 21:45
Name: Order Date, Length: 24949, dtype: object

In [82]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Order Date']

C:\Users\hp\AppData\Local\Temp\ipykernel_2260\4255972949.py:1: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

0       2019-12-30 00:01:00
1       2019-12-29 07:03:00
2       2019-12-12 18:21:00
3       2019-12-22 15:13:00
4       2019-12-18 12:38:00
                ...
24944   2019-12-11 20:58:00
24945   2019-12-01 12:01:00
24946   2019-12-09 06:43:00
24947   2019-12-03 10:39:00
24948   2019-12-21 21:45:00
Name: Order Date, Length: 24949, dtype: datetime64[ns]

In [83]:
df['Price Each'] = df['Price Each'].str.replace('$', '').astype(float)
df['Price Each']

0        1700.00
1         600.00
2          11.95
3         149.99
4          11.95
          ...
24944      14.95
24945       3.84
24946     400.00
24947      11.99
24948      99.99
Name: Price Each, Length: 24949, dtype: float64

In [84]:
df['Quantity Ordered'] = df['Quantity Ordered'].astype(int)
df['Quantity Ordered']

0        1
1        1
2        1
3        1
4        1
        ..
24944    1
24945    2
24946    1
24947    1
24948    1
Name: Quantity Ordered, Length: 24949, dtype: int32

In [85]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001"
1,295666,LG Washing Machine,1,600.00,2019-12-29 07:03:00,"562 2nd St, New York City, NY 10001"
2,295667,USB-C Charging Cable,1,11.95,2019-12-12 18:21:00,"277 Main St, New York City, NY 10001"
3,295668,27in FHD Monitor,1,149.99,2019-12-22 15:13:00,"410 6th St, San Francisco, CA 94016"
4,295669,USB-C Charging Cable,1,11.95,2019-12-18 12:38:00,"43 Hill St, Atlanta, GA 30301"

In [86]:
df[df['Purchase Address'] == 'Purchase Address']

Empty DataFrame
Columns: [Order ID, Product, Quantity Ordered, Price Each, Order Date, Purchase Address]
Index: []

In [87]:
df.describe(include= 'O')

       Order ID               Product                     Purchase Address
count     24949                 24949                                24949
unique    24006                    19                                23214
top      296353  USB-C Charging Cable  146 5th St, San Francisco, CA 94016
freq          4                  2980                                    5

In [88]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001"
1,295666,LG Washing Machine,1,600.00,2019-12-29 07:03:00,"562 2nd St, New York City, NY 10001"
2,295667,USB-C Charging Cable,1,11.95,2019-12-12 18:21:00,"277 Main St, New York City, NY 10001"
3,295668,27in FHD Monitor,1,149.99,2019-12-22 15:13:00,"410 6th St, San Francisco, CA 94016"
4,295669,USB-C Charging Cable,1,11.95,2019-12-18 12:38:00,"43 Hill St, Atlanta, GA 30301"

### In depth check for numerical columns

In [89]:
num_cols = df.select_dtypes(include= 'number').columns
num_cols

Index(['Quantity Ordered', 'Price Each'], dtype='object')

In [90]:
for col in num_cols:

    px.histogram(data_frame= df, x= col, title= col).show()

# Feature Engineering

In [91]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001"
1,295666,LG Washing Machine,1,600.00,2019-12-29 07:03:00,"562 2nd St, New York City, NY 10001"
2,295667,USB-C Charging Cable,1,11.95,2019-12-12 18:21:00,"277 Main St, New York City, NY 10001"
3,295668,27in FHD Monitor,1,149.99,2019-12-22 15:13:00,"410 6th St, San Francisco, CA 94016"
4,295669,USB-C Charging Cable,1,11.95,2019-12-18 12:38:00,"43 Hill St, Atlanta, GA 30301"

In [92]:
df['year'] = df['Order Date'].dt.year

df['month'] = df['Order Date'].dt.month_name()

df['day'] = df['Order Date'].dt.day_name()

In [93]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,year,month,day
0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001",2019,December,Monday
1,295666,LG Washing Machine,1,600.00,2019-12-29 07:03:00,"562 2nd St, New York City, NY 10001",2019,December,Sunday
2,295667,USB-C Charging Cable,1,11.95,2019-12-12 18:21:00,"277 Main St, New York City, NY 10001",2019,December,Thursday
3,295668,27in FHD Monitor,1,149.99,2019-12-22 15:13:00,"410 6th St, San Francisco, CA 94016",2019,December,Sunday
4,295669,USB-C Charging Cable,1,11.95,2019-12-18 12:38:00,"43 Hill St, Atlanta, GA 30301",2019,December,Wednesday

In [94]:
'136 Church St, New York City, NY 10001'.split(',')[2].strip().split()[0]

'NY'

In [95]:
df['state'] = df['Purchase Address'].apply(lambda x : x.split(',')[2].strip().split()[0])
df['state']

0        NY
1        NY
2        NY
3        CA
4        GA
         ..
24944    CA
24945    CA
24946    WA
24947    TX
24948    CA
Name: state, Length: 24949, dtype: object

In [96]:
'136 Church St, New York City, NY 10001'.split(',')[1].strip()

'New York City'

In [97]:
def extract_city(x):

    return x.split(',')[1].strip()

In [98]:
df['city'] = df['Purchase Address'].apply(extract_city)
df['city']

0        New York City
1        New York City
2        New York City
3        San Francisco
4              Atlanta
             ...
24944    San Francisco
24945      Los Angeles
24946          Seattle
24947           Dallas
24948      Los Angeles
Name: city, Length: 24949, dtype: object

### Data Analysis

In [99]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,year,month,day,state,city
0,295665,Macbook Pro Laptop,1,1700.00,2019-12-30 00:01:00,"136 Church St, New York City, NY 10001",2019,December,Monday,NY,New York City
1,295666,LG Washing Machine,1,600.00,2019-12-29 07:03:00,"562 2nd St, New York City, NY 10001",2019,December,Sunday,NY,New York City
2,295667,USB-C Charging Cable,1,11.95,2019-12-12 18:21:00,"277 Main St, New York City, NY 10001",2019,December,Thursday,NY,New York City
3,295668,27in FHD Monitor,1,149.99,2019-12-22 15:13:00,"410 6th St, San Francisco, CA 94016",2019,December,Sunday,CA,San Francisco
4,295669,USB-C Charging Cable,1,11.95,2019-12-18 12:38:00,"43 Hill St, Atlanta, GA 30301",2019,December,Wednesday,GA,Atlanta

### What is the number of orders per state ?

In [100]:
state_count = df.state.value_counts().reset_index()
state_count

  state  count
0    CA   9893
1    NY   3405
2    TX   3351
3    MA   2695
4    GA   1986
5    WA   1974
6    OR   1330
7    ME    315

In [101]:
px.bar(state_count, x= 'state', y= 'count')

### What is the total revenue per City ?

In [102]:
rev_city = df.groupby('city')['Price Each'].sum().sort_values(ascending= False).reset_index()
rev_city

            city  Price Each
0  San Francisco  1101679.34
1    Los Angeles   677355.78
2  New York City   644160.69
3         Boston   507702.77
4        Seattle   384963.77
5         Dallas   379869.56
6        Atlanta   358302.13
7       Portland   302459.16
8         Austin   232478.11

In [103]:
px.bar(rev_city, x= 'city', y= 'Price Each', labels= {'Price Each' : 'Total Revenue'},
        text_auto= True, title= 'What is the total revenue per City ?')

In [104]:
df.state.value_counts(normalize= True).round(4) * 100

state
CA    39.65
NY    13.65
TX    13.43
MA    10.80
GA     7.96
WA     7.91
OR     5.33
ME     1.26
Name: proportion, dtype: float64

In [105]:
px.pie(data_frame= df, names= 'state')

In [106]:
df['Price Each'].cumsum().round(2)

0           1700.00
1           2300.00
2           2311.95
3           2461.94
4           2473.89
            ...
24944    4588455.49
24945    4588459.33
24946    4588859.33
24947    4588871.32
24948    4588971.31
Name: Price Each, Length: 24949, dtype: float64

In [107]:
df['Price Each']

0        1700.00
1         600.00
2          11.95
3         149.99
4          11.95
          ...
24944      14.95
24945       3.84
24946     400.00
24947      11.99
24948      99.99
Name: Price Each, Length: 24949, dtype: float64

In [108]:
df_sorted = df.sort_values(by= 'Order Date')
df_sorted.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,year,month,day,state,city
6366,301778,USB-C Charging Cable,1,11.95,2019-12-01 02:50:00,"920 Highland St, Seattle, WA 98101",2019,December,Sunday,WA,Seattle
14094,309213,Google Phone,1,600.00,2019-12-01 03:10:00,"694 11th St, Portland, OR 97035",2019,December,Sunday,OR,Portland
19668,314587,34in Ultrawide Monitor,1,379.99,2019-12-01 04:06:00,"746 North St, Dallas, TX 75001",2019,December,Sunday,TX,Dallas
20622,315501,Wired Headphones,1,11.99,2019-12-01 04:10:00,"588 Lincoln St, Boston, MA 02215",2019,December,Sunday,MA,Boston
17419,312424,AAA Batteries (4-pack),1,2.99,2019-12-01 04:24:00,"226 Elm St, New York City, NY 10001",2019,December,Sunday,NY,New York City

In [109]:
df_sorted['cum_rev'] = df_sorted['Price Each'].cumsum().round(2)
df_sorted['cum_rev']

6366          11.95
14094        611.95
19668        991.94
20622       1003.93
17419       1006.92
            ...
8854     4588744.43
3611     4588756.38
10596    4588856.37
5068     4588871.32
5067     4588971.31
Name: cum_rev, Length: 24949, dtype: float64

In [110]:
px.line(data_frame= df_sorted, x= 'Order Date', y= 'cum_rev')

In [113]:
import streamlit as st

In [115]:
df.to_csv('cleaned_df.csv')

### Deployment

In [128]:
%%writefile sales.py

import pandas as pd
import streamlit as st
import plotly.express as px

st.set_page_config(layout= 'wide', page_title= 'Sales EDA')

df = pd.read_csv('cleaned_df.csv', index_col= 0)

st.title('What is the percentage of each City in the Data ?')
st.plotly_chart(px.pie(df, names= 'city'))

st.title('What is the total number of order per State ?')
state_count = df.state.value_counts().reset_index()
st.plotly_chart(px.bar(state_count, x= 'state', y= 'count'))

st.title('What is the cumulative revenue from start date till end date ?')
df_sorted = df.sort_values(by= 'Order Date')
df_sorted['cum_rev'] = df_sorted['Price Each'].cumsum().round(2)
st.plotly_chart(px.line(data_frame= df_sorted, x= 'Order Date', y= 'cum_rev'))

Overwriting sales.py

In [127]:
! streamlit run sales.py

^C

In [124]:
%mkdir pages

In [151]:
%%writefile pages/report.py

import pandas as pd
import streamlit as st
import plotly.express as px

st.set_page_config(layout= 'wide', page_title= 'Sales EDA')

df = pd.read_csv('cleaned_df.csv', index_col= 0)

state = st.sidebar.selectbox('State', df.state.unique())
city = st.sidebar.selectbox('City', df.city.unique())
start_date = st.sidebar.date_input('Start Date', min_value= df['Order Date'].min(), max_value= df['Order Date'].max(), value= df['Order Date'].min())
end_date = st.sidebar.date_input('End Date', min_value= df['Order Date'].min(), max_value= df['Order Date'].max(), value= df['Order Date'].max())
top_n = st.sidebar.slider('Top N', min_value= 1, max_value= df['Product'].nunique(), step= 1, value= 5)

df_2 = df[(df.state == state) & (df.city == city) & (df['Order Date'] >= str(start_date)) & (df['Order Date'] <= str(end_date))]

st.dataframe(df_2)

prod_count = df_2['Product'].value_counts().reset_index().head(top_n)

st.plotly_chart(px.bar(data_frame=prod_count, x= 'Product', y= 'count',
                        title = f'The Most popular {top_n} Products'))

Overwriting pages/report.py

In [ ]:
# ! pip install pipreqs

In [153]:
import pipreqs

In [154]:
! pipreqs

WARNING: Import named "pandas" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "pandas" was resolved to "pandas:2.2.3" package (https://pypi.org/project/pandas/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in c:\Users\hp\Desktop\Sales Products\requirements.txt