# you have a data set called shopping cart it consist of four datasets 
- 1- customers.csv
- 2- orders.csv
- 3- products.csv
- 4- sales.csv
# your task in this project is: 
- 1- combine this data together
- 2- check messing values
- 3- show summary statistics
- 4- deal with date time and extract features from dates
- 5- answer at least three questions from this data

## Import libraries

In [1]:
import pandas as pd
import numpy as np

## Load data

In [2]:
customers = pd.read_csv('./Shopping Cart Dataset/customers.csv')
customers

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia
1,2,Zabrina Harrowsmith,Genderfluid,69,8327 Kirlin SummitApt. 461,8223,New Zacharyfort,South Australia,Australia
2,3,Shina Dullaghan,Polygender,59,269 Gemma SummitSuite 109,5661,Aliburgh,Australian Capital Territory,Australia
3,4,Hewet McVitie,Bigender,67,743 Bailey GroveSuite 141,1729,South Justinhaven,Queensland,Australia
4,5,Rubia Ashleigh,Polygender,30,48 Hyatt ManorSuite 375,4032,Griffithsshire,Queensland,Australia
...,...,...,...,...,...,...,...,...,...
995,996,Elvira Sarfati,Agender,59,0433 Armstrong HillSuite 974,7613,Lake Danielland,Tasmania,Australia
996,997,Dickie Grushin,Non-binary,30,04 Howell PassSuite 209,6950,Ellaborough,Tasmania,Australia
997,998,Rebecka Fabler,Polygender,32,72 Annabelle PassApt. 446,52,Kohlerberg,Queensland,Australia
998,999,Carita Vynarde,Polygender,30,170 Wilson AvenueApt. 577,7849,East Oscarfurt,Western Australia,Australia
999,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia

In [3]:
orders = pd.read_csv('./Shopping Cart Dataset/orders.csv')
orders

     order_id  customer_id  payment order_date delivery_date
0           1           64    30811  2021-8-30    2021-09-24
1           2          473    50490   2021-2-3    2021-02-13
2           3          774    46763  2021-10-8    2021-11-03
3           4          433    39782   2021-5-6    2021-05-19
4           5          441    14719  2021-3-23    2021-03-24
..        ...          ...      ...        ...           ...
995       996          345    37843  2021-1-13    2021-02-02
996       997          346    53831  2021-1-18    2021-01-31
997       998          407    53308   2021-5-5    2021-05-21
998       999          428    31643  2021-6-15    2021-07-12
999      1000          896    27836   2021-4-7    2021-04-24

[1000 rows x 5 columns]

In [4]:
products = pd.read_csv('./Shopping Cart Dataset/products.csv')
products

,product_ID,product_type,product_name,size,colour,price,quantity,description
0,0,Shirt,Oxford Cloth,XS,red,114,66,"A red coloured, XS sized, Oxford Cloth Shirt"
1,1,Shirt,Oxford Cloth,S,red,114,53,"A red coloured, S sized, Oxford Cloth Shirt"
2,2,Shirt,Oxford Cloth,M,red,114,54,"A red coloured, M sized, Oxford Cloth Shirt"
3,3,Shirt,Oxford Cloth,L,red,114,69,"A red coloured, L sized, Oxford Cloth Shirt"
4,4,Shirt,Oxford Cloth,XL,red,114,47,"A red coloured, XL sized, Oxford Cloth Shirt"
...,...,...,...,...,...,...,...,...
1255,1255,Trousers,Tracksuit Bottoms,XS,violet,91,67,"A violet coloured, XS sized, Tracksuit Bottoms..."
1256,1256,Trousers,Tracksuit Bottoms,S,violet,91,48,"A violet coloured, S sized, Tracksuit Bottoms ..."
1257,1257,Trousers,Tracksuit Bottoms,M,violet,91,73,"A violet coloured, M sized, Tracksuit Bottoms ..."
1258,1258,Trousers,Tracksuit Bottoms,L,violet,91,45,"A violet coloured, L sized, Tracksuit Bottoms ..."
1259,1259,Trousers,Tracksuit Bottoms,XL,violet,91,60,"A violet coloured, XL sized, Tracksuit Bottoms..."

In [5]:
sales = pd.read_csv('./Shopping Cart Dataset/sales.csv')
sales

      sales_id  order_id  product_id  price_per_unit  quantity  total_price
0            0         1         218             106         2          212
1            1         1         481             118         1          118
2            2         1           2              96         3          288
3            3         1        1002             106         2          212
4            4         1         691             113         3          339
...        ...       ...         ...             ...       ...          ...
4995      4995       998         321             109         2          218
4996      4996       998         251              95         3          285
4997      4997       999         872             113         1          113
4998      4998       999         998             106         2          212
4999      4999       999        1105             115         1          115

[5000 rows x 6 columns]

## Merge the data

In [6]:
df = pd.merge(customers, orders, how= 'inner', on= 'customer_id')
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,payment,order_date,delivery_date
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-4-4,2021-04-06
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,729,35593,2021-2-18,2021-03-01
3,7,Winslow Ewbanck,Bigender,76,92 Hills Station StApt. 683,793,Masonfurt,Queensland,Australia,465,48935,2021-5-21,2021-05-23
4,10,Susanetta Wilshin,Bigender,70,615 Hayley KnollSuite 454,2118,Joelburgh,Western Australia,Australia,595,45626,2021-3-9,2021-03-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,998,Rebecka Fabler,Polygender,32,72 Annabelle PassApt. 446,52,Kohlerberg,Queensland,Australia,286,18840,2021-1-5,2021-01-08
996,998,Rebecka Fabler,Polygender,32,72 Annabelle PassApt. 446,52,Kohlerberg,Queensland,Australia,404,45215,2021-3-3,2021-03-09
997,998,Rebecka Fabler,Polygender,32,72 Annabelle PassApt. 446,52,Kohlerberg,Queensland,Australia,586,15870,2021-2-27,2021-03-22
998,998,Rebecka Fabler,Polygender,32,72 Annabelle PassApt. 446,52,Kohlerberg,Queensland,Australia,773,21349,2021-7-19,2021-08-07
999,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13

In [7]:
df = pd.merge(df, sales, how= 'inner', on= 'order_id')
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-4-4,2021-04-06,2245,211,106,3,318
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-4-4,2021-04-06,2246,783,91,2,182
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3324,525,98,2,196
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3325,792,91,2,182
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3326,179,98,1,98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4478,1117,115,3,345
4996,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4479,1070,93,3,279
4997,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4480,1177,99,2,198
4998,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4481,1239,112,1,112
4999,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4482,109,92,3,276

In [8]:
df = pd.merge(df, products, how= 'inner', left_on= 'product_id', right_on= 'product_ID')
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,...,quantity_x,total_price,product_ID,product_type,product_name,size,colour,price,quantity_y,description
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,...,3,318,211,Shirt,Chambray,S,red,105,72,"A red coloured, S sized, Chambray Shirt"
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,...,2,182,783,Jacket,Pullover,L,yellow,114,43,"A yellow coloured, L sized, Pullover Jacket"
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,...,2,196,525,Jacket,Leather,XS,red,113,67,"A red coloured, XS sized, Leather Jacket"
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,...,2,182,792,Jacket,Pullover,M,blue,114,44,"A blue coloured, M sized, Pullover Jacket"
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,...,1,98,179,Shirt,Camp Collared,XL,red,112,79,"A red coloured, XL sized, Camp Collared Shirt"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,...,3,345,1117,Trousers,Cropped,M,violet,99,47,"A violet coloured, M sized, Cropped Trousers"
4996,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,...,3,279,1070,Trousers,Joggers,XS,blue,94,67,"A blue coloured, XS sized, Joggers Trousers"
4997,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,...,2,198,1177,Trousers,High-Waisted,M,blue,98,52,"A blue coloured, M sized, High-Waisted Trousers"
4998,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,...,1,112,1239,Trousers,Tracksuit Bottoms,XL,yellow,91,59,"A yellow coloured, XL sized, Tracksuit Bottoms..."
4999,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,...,3,276,109,Shirt,Denim,XL,red,115,63,"A red coloured, XL sized, Denim Shirt"

In [9]:
pd.set_option('display.max_columns', None)

In [10]:
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity_x,total_price,product_ID,product_type,product_name,size,colour,price,quantity_y,description
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-4-4,2021-04-06,2245,211,106,3,318,211,Shirt,Chambray,S,red,105,72,"A red coloured, S sized, Chambray Shirt"
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-4-4,2021-04-06,2246,783,91,2,182,783,Jacket,Pullover,L,yellow,114,43,"A yellow coloured, L sized, Pullover Jacket"
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3324,525,98,2,196,525,Jacket,Leather,XS,red,113,67,"A red coloured, XS sized, Leather Jacket"
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3325,792,91,2,182,792,Jacket,Pullover,M,blue,114,44,"A blue coloured, M sized, Pullover Jacket"
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3326,179,98,1,98,179,Shirt,Camp Collared,XL,red,112,79,"A red coloured, XL sized, Camp Collared Shirt"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4478,1117,115,3,345,1117,Trousers,Cropped,M,violet,99,47,"A violet coloured, M sized, Cropped Trousers"
4996,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4479,1070,93,3,279,1070,Trousers,Joggers,XS,blue,94,67,"A blue coloured, XS sized, Joggers Trousers"
4997,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4480,1177,99,2,198,1177,Trousers,High-Waisted,M,blue,98,52,"A blue coloured, M sized, High-Waisted Trousers"
4998,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4481,1239,112,1,112,1239,Trousers,Tracksuit Bottoms,XL,yellow,91,59,"A yellow coloured, XL sized, Tracksuit Bottoms..."
4999,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4482,109,92,3,276,109,Shirt,Denim,XL,red,115,63,"A red coloured, XL sized, Denim Shirt"

## Data Understanding

In [11]:
df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity_x,total_price,product_ID,product_type,product_name,size,colour,price,quantity_y,description
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-4-4,2021-04-06,2245,211,106,3,318,211,Shirt,Chambray,S,red,105,72,"A red coloured, S sized, Chambray Shirt"
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-4-4,2021-04-06,2246,783,91,2,182,783,Jacket,Pullover,L,yellow,114,43,"A yellow coloured, L sized, Pullover Jacket"
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3324,525,98,2,196,525,Jacket,Leather,XS,red,113,67,"A red coloured, XS sized, Leather Jacket"
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3325,792,91,2,182,792,Jacket,Pullover,M,blue,114,44,"A blue coloured, M sized, Pullover Jacket"
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3326,179,98,1,98,179,Shirt,Camp Collared,XL,red,112,79,"A red coloured, XL sized, Camp Collared Shirt"

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     5000 non-null   int64
 1   customer_name   5000 non-null   object
 2   gender          5000 non-null   object
 3   age             5000 non-null   int64
 4   home_address    5000 non-null   object
 5   zip_code        5000 non-null   int64
 6   city            5000 non-null   object
 7   state           5000 non-null   object
 8   country         5000 non-null   object
 9   order_id        5000 non-null   int64
 10  payment         5000 non-null   int64
 11  order_date      5000 non-null   object
 12  delivery_date   5000 non-null   object
 13  sales_id        5000 non-null   int64
 14  product_id      5000 non-null   int64
 15  price_per_unit  5000 non-null   int64
 16  quantity_x      5000 non-null   int64
 17  total_price     5000 non-null   int64
 18  product_ID      5000 non-null   int64
 19  product_type    5000 non-null   object
 20  product_name    5000 non-null   object
 21  size            5000 non-null   object
 22  colour          5000 non-null   object
 23  price           5000 non-null   int64
 24  quantity_y      5000 non-null   int64
 25  description     5000 non-null   object
dtypes: int64(13), object(13)
memory usage: 1015.8+ KB

In [13]:
df.describe()

,customer_id,age,zip_code,order_id,payment,sales_id,product_id,price_per_unit,quantity_x,total_price,product_ID,price,quantity_y
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,504.563000,48.760400,4912.355600,503.038200,33976.785000,2499.500000,634.053200,103.501600,1.99240,206.360000,634.053200,105.665400,60.083400
std,276.504896,17.577519,2907.367939,285.964418,14612.706539,1443.520003,363.255794,9.195004,0.80751,86.357457,363.255794,9.735564,11.682523
min,1.000000,20.000000,52.000000,1.000000,10043.000000,0.000000,1.000000,90.000000,1.00000,90.000000,1.000000,90.000000,40.000000
25%,276.000000,34.000000,2273.000000,258.000000,20627.000000,1249.750000,323.000000,95.000000,1.00000,112.000000,323.000000,95.000000,50.000000
50%,509.000000,48.000000,4750.000000,504.500000,34259.000000,2499.500000,635.000000,102.000000,2.00000,204.000000,635.000000,108.000000,60.000000
75%,733.000000,63.000000,7460.250000,749.000000,46608.000000,3749.250000,951.000000,112.000000,3.00000,285.000000,951.000000,114.000000,70.000000
max,1000.000000,80.000000,9998.000000,999.000000,59910.000000,4999.000000,1259.000000,119.000000,3.00000,357.000000,1259.000000,119.000000,80.000000

In [16]:
df.describe(include= 'object')

,customer_name,gender,home_address,city,state,country,order_date,delivery_date,product_type,product_name,size,colour,description
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,616,8,616,604,8,1,291,304,3,35,5,7,1233
top,Kristofor Roos,Female,5567 Clarke MallApt. 756,Jordanside,South Australia,Australia,2021-6-21,2021-09-12,Trousers,Denim,M,blue,"A orange coloured, L sized, Flannel Shirt"
freq,37,712,37,37,718,5000,51,49,1683,273,1022,762,13

In [17]:
df.shape

(5000, 26)

In [18]:
(df.isna().sum() / df.shape[0]) * 100

customer_id       0.0
customer_name     0.0
gender            0.0
age               0.0
home_address      0.0
zip_code          0.0
city              0.0
state             0.0
country           0.0
order_id          0.0
payment           0.0
order_date        0.0
delivery_date     0.0
sales_id          0.0
product_id        0.0
price_per_unit    0.0
quantity_x        0.0
total_price       0.0
product_ID        0.0
product_type      0.0
product_name      0.0
size              0.0
colour            0.0
price             0.0
quantity_y        0.0
description       0.0
dtype: float64

In [20]:
# Another way to get percentage of missing values
df.isna().mean()

customer_id       0.0
customer_name     0.0
gender            0.0
age               0.0
home_address      0.0
zip_code          0.0
city              0.0
state             0.0
country           0.0
order_id          0.0
payment           0.0
order_date        0.0
delivery_date     0.0
sales_id          0.0
product_id        0.0
price_per_unit    0.0
quantity_x        0.0
total_price       0.0
product_ID        0.0
product_type      0.0
product_name      0.0
size              0.0
colour            0.0
price             0.0
quantity_y        0.0
description       0.0
dtype: float64

In [21]:
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity_x,total_price,product_ID,product_type,product_name,size,colour,price,quantity_y,description
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-4-4,2021-04-06,2245,211,106,3,318,211,Shirt,Chambray,S,red,105,72,"A red coloured, S sized, Chambray Shirt"
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-4-4,2021-04-06,2246,783,91,2,182,783,Jacket,Pullover,L,yellow,114,43,"A yellow coloured, L sized, Pullover Jacket"
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3324,525,98,2,196,525,Jacket,Leather,XS,red,113,67,"A red coloured, XS sized, Leather Jacket"
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3325,792,91,2,182,792,Jacket,Pullover,M,blue,114,44,"A blue coloured, M sized, Pullover Jacket"
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-3-6,2021-04-01,3326,179,98,1,98,179,Shirt,Camp Collared,XL,red,112,79,"A red coloured, XL sized, Camp Collared Shirt"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4478,1117,115,3,345,1117,Trousers,Cropped,M,violet,99,47,"A violet coloured, M sized, Cropped Trousers"
4996,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4479,1070,93,3,279,1070,Trousers,Joggers,XS,blue,94,67,"A blue coloured, XS sized, Joggers Trousers"
4997,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4480,1177,99,2,198,1177,Trousers,High-Waisted,M,blue,98,52,"A blue coloured, M sized, High-Waisted Trousers"
4998,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4481,1239,112,1,112,1239,Trousers,Tracksuit Bottoms,XL,yellow,91,59,"A yellow coloured, XL sized, Tracksuit Bottoms..."
4999,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia,894,35622,2021-10-11,2021-10-13,4482,109,92,3,276,109,Shirt,Denim,XL,red,115,63,"A red coloured, XL sized, Denim Shirt"

### Data Cleaning

In [22]:
df.columns

Index(['customer_id', 'customer_name', 'gender', 'age', 'home_address',
       'zip_code', 'city', 'state', 'country', 'order_id', 'payment',
       'order_date', 'delivery_date', 'sales_id', 'product_id',
       'price_per_unit', 'quantity_x', 'total_price', 'product_ID',
       'product_type', 'product_name', 'size', 'colour', 'price', 'quantity_y',
       'description'],
      dtype='object')

In [23]:
# convert to datetime format
df['order_date'] = pd.to_datetime(df['order_date'])

df['delivery_date'] = pd.to_datetime(df['delivery_date'])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     5000 non-null   int64
 1   customer_name   5000 non-null   object
 2   gender          5000 non-null   object
 3   age             5000 non-null   int64
 4   home_address    5000 non-null   object
 5   zip_code        5000 non-null   int64
 6   city            5000 non-null   object
 7   state           5000 non-null   object
 8   country         5000 non-null   object
 9   order_id        5000 non-null   int64
 10  payment         5000 non-null   int64
 11  order_date      5000 non-null   datetime64[ns]
 12  delivery_date   5000 non-null   datetime64[ns]
 13  sales_id        5000 non-null   int64
 14  product_id      5000 non-null   int64
 15  price_per_unit  5000 non-null   int64
 16  quantity_x      5000 non-null   int64
 17  total_price     5000 non-null   int64
 18  product_ID      5000 non-null   int64
 19  product_type    5000 non-null   object
 20  product_name    5000 non-null   object
 21  size            5000 non-null   object
 22  colour          5000 non-null   object
 23  price           5000 non-null   int64
 24  quantity_y      5000 non-null   int64
 25  description     5000 non-null   object
dtypes: datetime64[ns](2), int64(13), object(11)
memory usage: 1015.8+ KB

In [25]:
df['order_quantity'] = df.quantity_x

df['stock_quantity'] = df.quantity_y

df = df.drop(['quantity_x', 'quantity_y'], axis= 1)
df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,total_price,product_ID,product_type,product_name,size,colour,price,description,order_quantity,stock_quantity
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-04-04,2021-04-06,2245,211,106,318,211,Shirt,Chambray,S,red,105,"A red coloured, S sized, Chambray Shirt",3,72
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-04-04,2021-04-06,2246,783,91,182,783,Jacket,Pullover,L,yellow,114,"A yellow coloured, L sized, Pullover Jacket",2,43
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-03-06,2021-04-01,3324,525,98,196,525,Jacket,Leather,XS,red,113,"A red coloured, XS sized, Leather Jacket",2,67
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-03-06,2021-04-01,3325,792,91,182,792,Jacket,Pullover,M,blue,114,"A blue coloured, M sized, Pullover Jacket",2,44
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-03-06,2021-04-01,3326,179,98,98,179,Shirt,Camp Collared,XL,red,112,"A red coloured, XL sized, Camp Collared Shirt",1,79

In [26]:
# Another way to rename columns
# df.rename(columns= {'quantity_x': 'order_quantity'}, inplace= True)

# df.rename(columns= {'quantity_y': 'stock_quantity'}, inplace= True)

In [27]:
df.head()

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,total_price,product_ID,product_type,product_name,size,colour,price,description,order_quantity,stock_quantity
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-04-04,2021-04-06,2245,211,106,318,211,Shirt,Chambray,S,red,105,"A red coloured, S sized, Chambray Shirt",3,72
1,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,455,24550,2021-04-04,2021-04-06,2246,783,91,182,783,Jacket,Pullover,L,yellow,114,"A yellow coloured, L sized, Pullover Jacket",2,43
2,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-03-06,2021-04-01,3324,525,98,196,525,Jacket,Leather,XS,red,113,"A red coloured, XS sized, Leather Jacket",2,67
3,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-03-06,2021-04-01,3325,792,91,182,792,Jacket,Pullover,M,blue,114,"A blue coloured, M sized, Pullover Jacket",2,44
4,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia,670,10246,2021-03-06,2021-04-01,3326,179,98,98,179,Shirt,Camp Collared,XL,red,112,"A red coloured, XL sized, Camp Collared Shirt",1,79

In [28]:
# what is the unique values in each categorical column
categorical_columns = df.select_dtypes(include= 'object').columns
categorical_columns

Index(['customer_name', 'gender', 'home_address', 'city', 'state', 'country',
       'product_type', 'product_name', 'size', 'colour', 'description'],
      dtype='object')

In [31]:
with open('categorical_columns.txt', 'w') as f:
    for col in categorical_columns:
        f.write(f'{col} :\n{df[col].nunique()}\n{df[col].unique()}\n\n')
# Another way to get unique values in each categorical column
for col in categorical_columns:
    print(f'{col} :\n{df[col].nunique()}\n{df[col].unique()}')

customer_name :
616
['Leanna Busson' 'Winslow Ewbanck' 'Susanetta Wilshin'
 'Michaeline McIndrew' 'Fedora Dmych' 'Marabel Swinfon' 'Avril Rossiter'
 'Gabbie Aldwinckle' 'Chan Duchesne' 'Chadwick Cruddas' 'Gigi Kalaher'
 'Seana Hearons' 'Blayne Sabatier' 'Alair Grimwad' 'Ernaline Luce'
 'Timothy Compston' 'Jayme Turvie' 'Hadley Baddam' 'Ninon Corteney'
 'Adamo Saddington' 'Regan Gronaller' 'Hana Stitch' 'Horatius Genever'
 'Avivah Chipchase' 'Vicki Stockwell' 'Meris Twitty' 'Jarrett Brumby'
 'Shanna Pietrzyk' 'Moore Oolahan' 'Kayley Brosoli' 'Marena Lockhart'
 'Tore Caras' 'Giles Kyne' 'Aurie Margett' 'Hyacinth Pepper' 'Lin Avraam'
 'Denice Ledrane' 'Annabella Devote' 'Willa Gaisford' 'Tiphany Peacop'
 'Dulcea Shrawley' 'Marinna Heal' 'Jehanna Water' 'Katinka Currier'
 'Chandra Carine' 'Angela Kester' 'Jethro Pollak' 'Persis Spiteri'
 'Lanny Wardale' 'Kayne Fraczkiewicz' 'Minta Loble' 'Cornie Virr'
 'Corinna Maystone' 'Barbara-anne Salerg' 'Kendall Jakubski'
 'Matthiew Hinckes' 'Hillary Guiness' 'Law Foker' 'Otha Skein'
 'Pierre Rockwill' 'Garvy Davioud' 'Dean McLarty' 'Benji Vineall'
 'Wilhelm Blaber' 'Hurleigh Sieb' 'Monica Teodorski' 'Nanny Franey'
 'Rachel Colebrook' 'Sandy Yushachkov' 'Merrill Care' 'Giralda Trewin'
 'Eada Viccary' 'Hadlee Douthwaite' 'Hew Cardinal' 'Erik Osgar'
 'Alexei Hurburt' 'Meghan Simic' 'Didi Garton' 'Yardley Dreamer'
 'Pate De Ambrosis' 'Lesli Pitfield' 'Merl Gayforth' 'Daisy Camillo'
 'Beatrisa Winterscale' 'Bette-ann Harteley' 'Raul Pockey' 'Mycah Rodie'
 'Vida Matchitt' "Valerie D'Errico" 'Elaina Agate' 'Lawry Mannooch'
 'Ikey Spohr' 'Biddy Devanney' 'Myrle Kelby' 'Cosmo Leys'
 'Ann-marie Sinden' 'Christi Reston' 'Katalin Tellesson'
 'Harrietta Burchatt' 'Alayne Ipplett' 'Wald Kaine' 'Mariellen Medendorp'
 'Curtis McCarroll' 'Gunner Murdie' 'Leeann Gowdie' 'Nelli Engall'
 'Puff Newbury' "Martin O'Mailey" 'Darrelle Padson' 'Trenton Lydiard'
 'Deedee Pashe' 'Isis Doel' 'Tommy Ebunoluwa' 'Tobye De Caville'
 'Erroll Michelle' 'Yevette Weekes' 'Clayson Mealing' 'Loni Tort'
 'Angil Crunden' 'Bird McGarvie' 'Crin Johnikin' 'Brade Caught'
 'Shaylyn Musla' 'Lauryn Deport' 'Rowena Doe' 'Evelyn Chevolleau'
 'Whitaker Pashen' 'Worthington Knapton' 'Jerald MacMeeking'
 'Araldo Washtell' 'Saxe Stormonth' 'Shelbi Impson' 'Monty Gowen'
 'Isaak Ferrarone' 'Zaria Garken' 'Bourke Pembery' 'Kaitlyn Pinare'
 'Beverlie Blance' 'Duncan Walliker' 'Anders Couvert' 'Cassaundra Sliman'
 'Hilda Peter' 'Daria Embleton' 'Brian Finnes' 'Valentine Marley'
 'Faunie Cooney' 'Lucias Forsythe' 'Atlante McGrotty' 'Lavina Dartnell'
 'Jeanne Pringer' 'Scot Billany' 'Dulcia Gawthorpe' 'Trista Aspray'
 'Mira Heinonen' 'Whitney Scarman' 'Ringo Sollars' 'Vite Durrant'
 'Ianthe Magowan' 'Sheff Ruoss' 'Lionel Mansel' 'Muire Ashtonhurst'
 'Rutger Hugonnet' 'Kendre Etherton' 'Dag Schiefersten' 'Silas Chaman'
 'Michele Osmant' 'Wren Helgass' 'Jaymee Dalrymple' 'Gert Brackstone'
 'Matilde Yanuk' 'Rafferty Fronek' 'Alia Rapinett' 'Brodie Hedin'
 'Aldin Moline' 'Roobbie Persich' 'Anny Midden' 'Darren Karpenko'
 'Elga Corgenvin' 'De Lourens' 'Meryl Kender' 'Silas Stephens'
 'Zeb Shipton' 'Ulla Crombie' 'Sharyl Royl' 'Constantino Langworthy'
 'Courtnay Cornewell' 'Jeff Curness' 'Sadella Goodsall' 'Gates Torrance'
 'Glyn Tieman' 'Dani Pinches' 'Jena Kelling' 'Ellerey Kaesmakers'
 'Robinetta Deners' 'Meade Yglesia' 'Lynda Seydlitz' 'Wadsworth Olivier'
 'Valery Pache' 'Barclay Kinsella' 'Binnie Gonzales' 'Carla Walework'
 'Con Pressdee' 'Udale Ripping' 'Julian Sponer' 'Milton Otson'
 'Eve Stutard' 'Cherlyn Asmus' 'Tymothy Linsay' 'Violet Alwen'
 'Merrielle Piken' 'Kerianne Parris' 'Lyn Bouts' 'Thorny Nornable'
 'Dani Hawtin' 'Justin Marden' 'Crawford Bolden' 'Jermaine Goranov'
 'Augustin Brandenberg' 'Iain Fellnee' 'Persis Linch' 'Konstantin Kuhlmey'
 'Tammie Gavrielli' 'Geraldine Naulty' "Hildagarde Dell 'Orto"
 'Mady Greenleaf' 'Ephrem Hambers' 'Hildegarde Bamlett' 'Etan Peirazzi'
 'Griffy Wenger' 'Ninetta Phizakarley' 'Emanuele Deesly'
 'Nathanil Runchman' 'Alameda Fincke' 'Dame Popov' 'Caroljean Elstob'
 'Bee Mazonowicz' 'Reed Churchlow' 'Eba Bauser' 'Collie Jakel'
 'Damiano Leyborne' 'Ailene McKeller' 'Waylen Swallwell' 'Zak Titterton'
 'Teddy Gell' 'Murdock Bulfit' 'Alis MacCulloch' 'Alphonse Galego'
 'Chandal Fransinelli' 'Alexis Maps' 'Ansel Chittem' 'Ashley Gant'
 'Leonore Yakunikov' 'Bay Kraut' 'Luelle Fernanando' 'Chaddie Fawlkes'
 'Kellyann Stening' 'Farah Schukert' 'Datha Vicary' 'Augusto Ackrill'
 'Tomaso Mullin' 'Jammal Varcoe' 'Ronni Gruszczak' 'Ettie Gonnely'
 'Candis Roswarne' 'Marci Borrett' 'Aldridge Tesh' 'Meredith Canniffe'
 'Daren Airs' 'Artemas Vasilischev' 'Hobie Anfusso' 'Melodee Spencley'
 'Margret Yeabsley' 'Benny Songist' 'Shena Solomonides' 'Ashely Inmett'
 'Devonne Martinetto' 'Toddie Snow' 'Guthry Ure' 'Abey Bampforth'
 'Wash Kyneton' 'Joelynn Remington' 'North Diamond' 'Romy Cuberley'
 'Frederich Duigenan' 'Alina Strotton' 'Francklyn Willeman'
 'Iago Jedrzaszkiewicz' 'Mallory Castellani' 'Vinnie Feaver'
 'Cacilie Forrestill' 'Maegan Ashton' 'Faber Purcell' 'Trudey Betteridge'
 'Hayyim Trewhella' 'Hal Saker' 'Lori Briars' 'Clem Margetts'
 'Orton Heigl' 'Krystle Boyce' 'Dunc Swynley' 'Stanley Kolakowski'
 'Gayleen Brookes' 'Alexis Cheake' 'Isahella Enrique' 'Bank Sargeaunt'
 'Jolee Stailey' 'Andrew Renn' 'John Panchen' 'Claudio Archibould'
 'Henrietta Briatt' 'Carlen Kelway' 'Archibaldo Taffurelli'
 'Neilla Halladey' 'Marilyn Rontree' 'Eddie Elcott' 'Brooks Sayers'
 'Jan Isenor' 'Kinny Roget' 'Corri Womack' 'Joannes Pandie' 'Malcolm Paal'
 'Margalo Cousen' 'Ailina Kynan' 'Grissel Harteley' 'Beverlie Bansal'
 'Ellyn Collacombe' 'Cad Dominichetti' 'Leroi Weal' 'Fanchette Polak'
 'Kerry Luto' 'Beverly Burbridge' 'Sonny Tremollet' 'Jakob Munks'
 'Nicky Giuron' 'Barclay Beswick' 'Marna Lammerts' 'Theodor Skipton'
 'Niels Loadsman' 'Lisetta Griffin' 'Kalil Thal' 'Nessy Kildea'
 'Kyle Lowbridge' 'Lizette Lindro' 'Joy Mirrlees' 'Shoshana Redsell'
 'Hoebart Edger' 'Melissa Partkya' 'Andi Kettleson' 'Gallard Mangan'
 'Henryetta Sheffield' 'Kristofor Roos' 'Raquela Swinnard'
 'Atlante Dissman' 'Ranna Paolillo' 'Hillier Seward' 'Riordan Goreway'
 'Fabian Gostage' 'Prissie Dumelow' 'Alicea Momford' 'Wenona Stuck'
 'Carmita Grundey' 'Nicole Cheel' 'Calhoun Raphael' 'Salomo Shuttell'
 'Thomasine Baudet' 'Hi Simenel' 'Sol Adhams' 'Kip Cantwell'
 'Stanleigh Hazelton' 'Averyl Atthow' 'Angie O Mullen' 'Vin Rubenovic'
 'Sadye Pes' 'Conny Chowne' 'Leann Kittow' 'Sherwynd Batsford'
 'Jacquelin Santostefano.' 'Phillipe Gatecliffe' 'Hort Ridding'
 'Zorina Rabl' 'Tann Scothron' 'Codie Everly' 'Frayda Simonini'
 'Sigismundo Basek' 'Nicholle Coom' 'Wanids Cudby' 'Darby Jeffries'
 'Channa Powley' 'Nara Legerwood' 'Morie Woodfield' 'Olympia Stobbs'
 'Tobin Jeffryes' 'Uriel Cottingham' 'Zebulon Rousel' 'Pietro Duling'
 'Ashlie Godwyn' 'Malory Emmison' 'Jaquelyn Dow' 'Willey Tolley'
 'Beckie Nasey' 'Roley Cassedy' 'Pieter Bruton' 'Gareth Bindon'
 'Jillene Goodbanne' 'Orran Skip' 'Ira Dafforne' 'Slade Villaret'
 'Engracia Abilowitz' 'Nerita Peotz' 'Dannie Fidler' 'Jedidiah Sydall'
 'Annice Kelcey' 'Bobbi Pickerill' 'Carlynn McCabe' 'Marthena Matterson'
 'Haslett Edwins' 'Nady Buston' 'Dare Andrich' 'Osgood Percifer'
 'Camellia Heatherington' 'Shermy Mulbry' 'Alon Abramsky'
 'Esteban Hensmans' 'Camala Llywarch' 'Elbertina Gaish' 'Amalia Eallis'
 'Arlie Bowman' 'Silvie Bortol' 'Perceval Umbers' 'Hetti Fibbens'
 'Miner Craddock' 'Antonia Yeardsley' 'Cary Boaler' 'Diann Grieger'
 'Stephen MacAleese' 'Debee Lording' 'Lilli Bavester' 'Avivah Roddick'
 'Lin Norville' 'Marnie Dennington' 'Lindsey McCuthais' 'Mellisent Druhan'
 'Drusi Eagell' 'Etheline Bahde' 'Bucky Cragell' 'Rey Grasner'
 'Herschel Verdey' 'Kellie Curbishley' 'Gerri McCarle' 'Olimpia Tankus'
 'Gorden Seago' 'Otto Matyasik' 'Valentino Branney' 'Delia Mably'
 'Zebulen Zannotti' 'Lilyan Pirt' 'Kristel Klaaassen' 'Meryl Neeson'
 'Selestina Dauber' 'Lindy Saltrese' 'Cristen Hagley' 'Mirabelle Vaney'
 'Ninnetta Lammin' 'Herbert Rock' 'Taffy Quimby' 'Mallissa Lawdham'
 'Jan Gligori' 'Eloise Ondrusek' 'Brod Phifer' 'Marni Figiovanni'
 'Waylin Gasson' 'Aida Warsap' 'Sigmund Bothen' 'Thorsten Sowrey'
 'Paul McGavigan' 'Marlee Edser' "Paxon O'Shiel" 'Ellynn Korba'
 'Edee Wildt' 'Felice Dumbleton' 'Chastity Daniaud' 'Cinda Alleyne'
 'Denny Parlour' 'Gusty Smallacombe' 'Jillana Blankau' 'Lorine McLugish'
 'Sharl Izzett' 'Gwenette Kahen' 'Bone Perche' 'Drake Ivanilov'
 'Jojo Toffanini' 'Tressa Cunnane' 'Elizabet Pippin' "Berri O' Clovan"
 'Perry McAless' 'Rachelle Jelf' 'Gibbie Beardall' 'Katusha Ceney'
 'Morgana Weymouth' 'Amaleta Beange' 'Gertrude Harriott' 'Dena Banbrick'
 'Marvin Van Hault' 'Winn Siemandl' 'Charles Duffitt' 'Else Bicheno'
 'Saul Franklyn' 'Edithe Yitshak' 'Joella Tiddeman' 'Nathaniel McCandless'
 'Normy Anlay' 'Errol Berkley' 'Judith Plimmer' 'Eryn Harcus'
 'Tucky Kitchaside' 'Marget Kells' 'Gertrudis Pergens' 'Hilliard Papes'
 'Glenn Keri' 'Randell Shorte' 'Nixie Fraczak' 'Ellene Dedam' 'Rorie Hof'
 'Millicent Stedson' 'Sheela Dovey' 'Lorelle Lancastle'
 'Isidore Bleasdille' 'Rowena Soall' 'Gina Pollen' 'Worthy Pardoe'
 'Lucas Cromly' 'Brenden Roast' 'Lisle Worthing' 'Dianemarie Neicho'
 'Ondrea Apark' 'Hunfredo Peyto' 'Berry Rosiello' 'Vladimir Jandourek'
 'Lorenzo Dutch' 'Calypso Ellaway' 'Brendis Blackboro' 'Cecilla Pigford'
 'Prissie Kondratovich' 'Glynda Dodshon' 'Elianore Syphas'
 'Bartel Clemendet' 'Noel Siviour' 'Frederique Hopkins' 'Emylee Buscher'
 'Killie Wigzell' 'Kaitlin Jeanes' 'Jania Sailes' 'Angelle Huby'
 'Robena Gilbert' 'Thoma Seaking' 'Jillian Sauven' 'Shelden Tinline'
 'Sutherlan Stepto' 'Vincent Kiledal' 'Aindrea Franzetti' 'Kakalina Ragge'
 'Patin Circuit' 'Chancey Iacovozzo' 'Emmalee Camin' 'Gabriella Nutman'
 'Tracie Okey' 'Curcio Kiffin' 'Cindi McCague' 'Adena Venn'
 'Cherie Fairhead' 'Deirdre Burle' 'Vittorio Rosenstengel' 'Joby Law'
 'Hughie Trelease' 'Reba Crauford' 'Lenna Beau' 'Pen Andrzejczak'
 'Mart Naismith' 'Judy Mesias' 'Jamesy Rennles' 'Egon Figliovanni'
 'Lacee Denyukin' 'Peri Pilsworth' 'Lorilyn Vittet' 'Raul Crilly'
 'Dulsea Collet' 'Eustacia Andreassen' 'Cy Sabbins' 'Geri Renton'
 'Timmie Kelshaw' 'Dolph Arrow' 'Camile Haveline' 'Felic Marrian'
 'Albina Disdel' 'Terri Lunny' 'Bunni Poundsford' 'Ginnie Glasheen'
 'Delcine Pickthorn' 'Constance Piddington' 'Lars Stading' 'Tally Rubel'
 'Michell Lappine' 'Sharleen Langworthy' 'Darby Aistrop' 'Devin Lindmark'
 'Theodosia Postins' 'Grady Wipper' 'Tommie Benoy' 'Sauncho Boosey'
 'Cristina Jowling' 'Orella Singyard' 'Vanna Densham' 'Leandra Derks'
 'Elvira Sarfati' 'Rebecka Fabler' 'Mandel Fairbanks']
gender :
8
['Female' 'Bigender' 'Agender' 'Male' 'Genderfluid' 'Genderqueer'
 'Non-binary' 'Polygender']
home_address :
616
['8606 Victoria TerraceSuite 560' '92 Hills Station StApt. 683'
 '615 Hayley KnollSuite 454' '96 Daniel PlaceSuite 898'
 '66 Kayla MewsSuite 951' '16 Kuhn LoopSuite 442' '254 Ali RidgeApt. 350'
 '424 Mason PlaceApt. 181' '13 Bailey ManorApt. 848'
 '002 Beau PlazaApt. 308' '2069 Phoebe MallApt. 543'
 '93 Doherty MewsSuite 649' '292 Casper IslandSuite 778'
 '682 Rose CircleApt. 514' '02 Gabriella PlazaApt. 474'
 '499 Darcy CrestApt. 192' '6578 Kayla AvenueSuite 812'
 '360 Heller DriveApt. 052' '09 Robinson SquareApt. 647'
 '3168 Bartoletti CrescentSuite 878' '9484 Amelia View RdApt. 760'
 '647 Violet Estate DrSuite 364' '778 Wilkinson RidgeSuite 101'
 '6308 Amelie MeadowSuite 634' '3101 Thomson ManorApt. 600'
 '708 Daniel MeadowSuite 246' '59 Wood DriveSuite 806'
 '30 Watson WayApt. 179' '13 Stokes SummitApt. 125'
 '59 Hand ManorApt. 544' '012 Cooper MallApt. 259'
 '2912 Adams JunctionSuite 740' '91 Angelina RidgeApt. 435'
 '260 Lily PassSuite 549' '8095 Kuhlman StreetApt. 657'
 '00 Zachary AvenueApt. 781' '049 Imogen StreetSuite 299'
 '4927 Alice MeadowApt. 960' '373 Little JunctionApt. 299'
 '473 Leo CourtSuite 784' "026 D'amore RunSuite 187"
 '95 Justin PlaceApt. 441' '672 Graham MewsApt. 407'
 '96 Caitlin HillSuite 366' '1805 Harry RoadApt. 445'
 '63 Tremblay BoulevardApt. 688' '7812 Towne GroveSuite 233'
 '844 Alana LaneApt. 225' '4870 Jackson SummitApt. 538'
 '9662 Isaac MallSuite 490' '195 Wilson HillApt. 597'
 '41 Feeney ParkwaySuite 074' '040 Savannah GroveSuite 967'
 '384 Hayley View RdSuite 949' '331 Leah Station StSuite 445'
 '1290 Koch GroveApt. 799' '74 Eva TerraceSuite 247'
 '4715 Hand View RdSuite 955' '368 Morrison MeadowApt. 117'
 '09 Doyle MallApt. 066' '461 Nader LaneApt. 460'
 '6303 Nate BoulevardSuite 368' '468 Shields CircleApt. 480'
 '093 Jessica AvenueSuite 154' '1737 Schroeder LoopSuite 349'
 '100 Stokes ParkwayApt. 307' '9268 Swift SummitSuite 218'
 '6553 Gibson AvenueSuite 245' '20 Morrison RoadSuite 781'
 '7285 Mason BoulevardSuite 754' '656 Abigail KnollApt. 083'
 '72 George CourtApt. 482' '19 Lola View RdApt. 937'
 '29 David JunctionApt. 733' '6022 Jonathan TrackSuite 607'
 '0544 Zoe CourtSuite 153' '164 Fisher RidgeSuite 516'
 '13 Ivy BoulevardSuite 234' '8083 Paterson RoadApt. 211'
 '65 Eli AvenueApt. 473' '617 Scarlett BoulevardApt. 858'
 '769 Gibson TrailApt. 359' '5310 Lewis TrailApt. 715'
 '74 Ryan CircleSuite 426' "051 O'conner Station StSuite 626"
 '178 Smitham GroveSuite 638' '3087 Victoria DriveApt. 454'
 '69 Aiden ParkwaySuite 721' '607 Parisian AvenueSuite 494'
 '596 Martin BoulevardApt. 367' '348 Johnston RoadSuite 155'
 '338 Mckenzie PlaceSuite 622' '42 Michael RoadApt. 405'
 '85 Charles MallSuite 424' '012 Eli RidgeSuite 727'
 '017 Doherty DriveSuite 350' '70 Phoenix DriveApt. 109'
 '286 Chase IslandSuite 443' '8125 Durgan BoulevardSuite 068'
 '1952 Collins StreetSuite 930' '5135 Leah RoadSuite 306'
 '16 Boyer WaySuite 018' '4036 Thompson StreetApt. 565'
 '7504 Phoebe RoadApt. 552' '8183 Alexis JunctionApt. 634'
 '58 Jett RoadApt. 448' '35 Fahey CircuitSuite 014'
 '639 Griffiths ParkwayApt. 162' '22 Aaron LoopApt. 324'
 '30 Williamson SummitApt. 594' '96 Bartoletti StreetApt. 671'
 '540 Schmitt ParkwaySuite 102' '56 Wolf TerraceSuite 373'
 '987 Charlotte MewsApt. 591' '694 Isabella WaySuite 054'
 '6369 Patrick HillApt. 508' '94 Hannah LoopSuite 177'
 '76 Zac KnollSuite 031' '765 Christiansen ParkwaySuite 557'
 '889 Hermann Station StApt. 026' '09 Kiehn View RdApt. 209'
 '38 Baumbach Estate DrApt. 545' '814 Jayden MewsSuite 958'
 '47 Green ParkwayApt. 868' '9388 Bauch TrailSuite 439'
 '385 Jayden View RdApt. 459' '62 Mcdermott HillSuite 903'
 '88 Walsh WaySuite 074' '5040 Isabel TerraceSuite 158'
 '9173 Maya SummitApt. 856' '028 Elijah TrailApt. 268'
 '20 Xavier RidgeApt. 805' '651 Garden CourtApt. 769'
 '074 Hackett ParadeApt. 191' '53 Jake CourtSuite 337'
 '599 Campbell CrestApt. 125' "8982 O'reilly PlazaSuite 007"
 '1604 Olivia CrestApt. 164' '861 Thomas LoopApt. 385'
 '64 Phillips RunApt. 722' '3679 Kiehn ParkwaySuite 444'
 "4435 O'hara TerraceSuite 232" '39 Wilkinson CrestApt. 257'
 '069 Claire GroveSuite 234' '31 Aaron WayApt. 752'
 '36 Christian PlaceApt. 409' '122 Riley TrailSuite 946'
 '2352 Luca JunctionApt. 067' '0380 Bartell StreetSuite 585'
 '786 Mackenzie StreetApt. 660' '4966 Lilly Estate DrApt. 570'
 '7204 Toby SummitApt. 845' '9347 Morrison RoadSuite 865'
 '2719 Dietrich KnollApt. 175' "01 D'amore ManorSuite 692"
 '75 Kovacek KnollSuite 417' '31 King LoopSuite 647'
 '35 Baumbach HillApt. 244' '269 Cartwright ParadeSuite 150'
 '03 Spencer MewsSuite 726' '25 Mikayla MewsApt. 558'
 '13 Hammes CircuitApt. 503' '3627 Chloe Estate DrSuite 963'
 '199 Amber MallSuite 954' '410 Ryan CrescentApt. 461'
 '370 Koch SummitApt. 142' '2634 Ward CrescentSuite 361'
 '812 Corwin Estate DrSuite 687' '89 Schmitt PlazaSuite 421'
 '17 Jade AvenueApt. 646' '068 Logan CourtSuite 319'
 '7299 Madeline MeadowApt. 450' '6428 Boyle MallApt. 711'
 '7210 Farrell HillApt. 735' '42 Mackenzie CourtApt. 934'
 '810 Jasper CircleSuite 777' '73 Amelie LoopApt. 987'
 '0462 Fisher TrackSuite 627' '334 Olivia MeadowSuite 855'
 '0052 Benjamin MewsApt. 635' '344 Addison PlazaApt. 998'
 '970 Khan RidgeApt. 056' '5302 Ava TerraceApt. 295'
 '29 Caitlin CrestSuite 875' '316 Violet LaneApt. 212'
 '533 Archie StreetApt. 007' '86 Christiansen HillSuite 955'
 '49 Klein DriveSuite 199' '26 Willow CourtApt. 822'
 '37 White Station StApt. 524' '83 Reynolds ParadeSuite 974'
 '52 Savannah LaneApt. 519' '56 Marcus SquareSuite 361'
 '32 Chase JunctionSuite 463' '624 Bode TrailSuite 795'
 '246 Waters CrescentSuite 947' '4309 Nguyen KnollApt. 851'
 '3203 Jackson TerraceSuite 580' '698 Doyle RoadSuite 219'
 '5756 Savannah DriveApt. 644' '011 Hamilton PlaceSuite 215'
 '2797 Corkery KnollApt. 001' "313 O'hara Estate DrSuite 414"
 '745 Jack CourtApt. 737' '88 Olson GroveApt. 120'
 '899 Lynch LaneSuite 349' '003 Bruen DriveApt. 633'
 '38 Charli SquareSuite 502' '339 Hermann ParadeSuite 489'
 '9182 Hermann MallApt. 890' '59 Bergstrom GroveSuite 260'
 '16 Maddison MewsSuite 093' '4070 Nathan CircuitSuite 296'
 '41 Brown Estate DrSuite 039' "813 O'reilly View RdSuite 466"
 '63 Charlie LaneSuite 463' '9937 Oliver CircleApt. 655'
 '20 Skye RunApt. 868' '476 Corwin ParkwayApt. 441'
 '102 Mitchell IslandSuite 599' '3463 Joshua SummitApt. 971'
 '06 Eve RunApt. 689' '491 Fisher IslandSuite 745'
 '59 Henry PlaceSuite 781' '8756 Tremblay RunSuite 034'
 '6502 Abbey ParadeSuite 954' '47 Stanton GroveSuite 963'
 '8162 James TrackApt. 724' '8649 Phillips KnollSuite 008'
 '716 Max IslandSuite 824' '83 Jordan DriveApt. 011'
 '831 Ava SquareApt. 776' '6239 Kreiger HillApt. 899'
 '46 Spencer MeadowSuite 241' '5990 John View RdApt. 812'
 "806 O'connell CrestApt. 665" '4592 Isabella BoulevardApt. 793'
 '984 Boyer KnollApt. 699' '40 Mitchell CrestSuite 035'
 '6166 Durgan WayApt. 693' '9444 Casper RidgeApt. 537'
 '254 Layla AvenueSuite 506' '017 Maddison KnollSuite 875'
 '29 Bruen TrailSuite 288' '5233 Lara AvenueSuite 291'
 '8142 Jackson ParkwaySuite 475' '553 Alexander TrailSuite 694'
 '7048 Barrows CrescentSuite 562' '591 Sarah PassSuite 334'
 '22 Eve CrescentApt. 357' '458 Imogen Station StSuite 799'
 '59 Gibson MeadowApt. 565' '688 Campbell RoadSuite 011'
 '855 Beahan IslandSuite 560' '31 Towne SummitSuite 671'
 '35 Robinson Station StSuite 547' '58 Heaney SquareApt. 870'
 '587 Dooley AvenueSuite 138' '89 Charles GroveApt. 955'
 '51 Gabriel KnollApt. 819' '80 Hermiston WaySuite 403'
 '535 Angelina CourtSuite 875' '6172 Andrew AvenueApt. 194'
 '5777 Mayer PassApt. 881' '53 Lucy CrescentSuite 222'
 '1649 Owen JunctionApt. 523' '120 Eli PlazaApt. 906'
 '378 John MallSuite 835' '33 Richards JunctionApt. 478'
 '5157 Feil RoadApt. 633' '033 Mitchell IslandApt. 732'
 '543 Nader CrestSuite 019' '165 Hermiston LoopSuite 403'
 "82 O'hara LoopSuite 558" '625 Anthony MewsApt. 730'
 '655 Max TrailSuite 049' '19 Young IslandSuite 543'
 '400 Beau PlaceSuite 439' '3543 Jack GroveApt. 595'
 '539 Towne CrescentSuite 935' '94 Archie CourtSuite 659'
 '85 Mitchell StreetSuite 398' '06 Toby KnollApt. 679'
 '85 Cooper CrescentApt. 819' '2501 Hackett ManorSuite 051'
 '22 Ellie View RdApt. 141' '00 Lockman TrackSuite 564'
 '115 Wilkinson CrestSuite 858' '18 Jack JunctionSuite 575'
 '0189 Anna KnollSuite 703' '06 Ebert CrestSuite 385'
 '783 Olivia CrescentSuite 877' '2115 Henry GroveSuite 788'
 '8662 Maya PlaceApt. 834' '64 Aiden View RdSuite 085'
 '531 Schmitt BoulevardApt. 010' '6744 Joshua RoadApt. 554'
 '01 Piper ManorApt. 376' '16 Thomson PlazaSuite 403'
 '621 Eve View RdApt. 900' '7295 Champlin CrestApt. 519'
 '18 Lachlan CourtApt. 781' '60 Nolan LaneSuite 078'
 '43 Oscar LoopSuite 946' '74 King SummitSuite 021'
 '046 Leah RidgeSuite 190' '761 Mckenzie BoulevardSuite 489'
 '35 Barrows RunApt. 970' '0487 Jordan TerraceSuite 509'
 '708 Cole PlazaSuite 178' '74 Aaron HillSuite 794'
 '457 Evans View RdApt. 385' '95 Grimes ParkwaySuite 469'
 '9100 Kovacek GroveSuite 577' '26 Levi CrestSuite 002'
 '64 Champlin ParkwayApt. 832' '6863 Tremblay KnollSuite 290'
 '2684 Tillman ParadeApt. 492' '051 White WayApt. 392'
 '5778 Chloe CourtApt. 365' '622 Hamish CourtSuite 367'

In [32]:
categorical_columns

Index(['customer_name', 'gender', 'home_address', 'city', 'state', 'country',
       'product_type', 'product_name', 'size', 'colour', 'description'],
      dtype='object')

In [33]:
df.drop(['country', 'customer_name', 'description', 'home_address'], axis= 1, inplace= True)

In [34]:
df.head()

,customer_id,gender,age,zip_code,city,state,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,total_price,product_ID,product_type,product_name,size,colour,price,order_quantity,stock_quantity
0,1,Female,30,5464,Johnstonhaven,Northern Territory,455,24550,2021-04-04,2021-04-06,2245,211,106,318,211,Shirt,Chambray,S,red,105,3,72
1,1,Female,30,5464,Johnstonhaven,Northern Territory,455,24550,2021-04-04,2021-04-06,2246,783,91,182,783,Jacket,Pullover,L,yellow,114,2,43
2,1,Female,30,5464,Johnstonhaven,Northern Territory,670,10246,2021-03-06,2021-04-01,3324,525,98,196,525,Jacket,Leather,XS,red,113,2,67
3,1,Female,30,5464,Johnstonhaven,Northern Territory,670,10246,2021-03-06,2021-04-01,3325,792,91,182,792,Jacket,Pullover,M,blue,114,2,44
4,1,Female,30,5464,Johnstonhaven,Northern Territory,670,10246,2021-03-06,2021-04-01,3326,179,98,98,179,Shirt,Camp Collared,XL,red,112,1,79

In [35]:
# Check duplicates
df.duplicated().sum()

np.int64(0)

In [36]:
# drop duplicates
# df = df.drop_duplicates()
df.drop_duplicates(inplace= True, ignore_index= True)

In [37]:
df

,customer_id,gender,age,zip_code,city,state,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,total_price,product_ID,product_type,product_name,size,colour,price,order_quantity,stock_quantity
0,1,Female,30,5464,Johnstonhaven,Northern Territory,455,24550,2021-04-04,2021-04-06,2245,211,106,318,211,Shirt,Chambray,S,red,105,3,72
1,1,Female,30,5464,Johnstonhaven,Northern Territory,455,24550,2021-04-04,2021-04-06,2246,783,91,182,783,Jacket,Pullover,L,yellow,114,2,43
2,1,Female,30,5464,Johnstonhaven,Northern Territory,670,10246,2021-03-06,2021-04-01,3324,525,98,196,525,Jacket,Leather,XS,red,113,2,67
3,1,Female,30,5464,Johnstonhaven,Northern Territory,670,10246,2021-03-06,2021-04-01,3325,792,91,182,792,Jacket,Pullover,M,blue,114,2,44
4,1,Female,30,5464,Johnstonhaven,Northern Territory,670,10246,2021-03-06,2021-04-01,3326,179,98,98,179,Shirt,Camp Collared,XL,red,112,1,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1000,Male,71,9012,Lake Audreyborough,Tasmania,894,35622,2021-10-11,2021-10-13,4478,1117,115,345,1117,Trousers,Cropped,M,violet,99,3,47
4996,1000,Male,71,9012,Lake Audreyborough,Tasmania,894,35622,2021-10-11,2021-10-13,4479,1070,93,279,1070,Trousers,Joggers,XS,blue,94,3,67
4997,1000,Male,71,9012,Lake Audreyborough,Tasmania,894,35622,2021-10-11,2021-10-13,4480,1177,99,198,1177,Trousers,High-Waisted,M,blue,98,2,52
4998,1000,Male,71,9012,Lake Audreyborough,Tasmania,894,35622,2021-10-11,2021-10-13,4481,1239,112,112,1239,Trousers,Tracksuit Bottoms,XL,yellow,91,1,59
4999,1000,Male,71,9012,Lake Audreyborough,Tasmania,894,35622,2021-10-11,2021-10-13,4482,109,92,276,109,Shirt,Denim,XL,red,115,3,63

In [38]:
df.delivery_date

0      2021-04-06
1      2021-04-06
2      2021-04-01
3      2021-04-01
4      2021-04-01
          ...
4995   2021-10-13
4996   2021-10-13
4997   2021-10-13
4998   2021-10-13
4999   2021-10-13
Name: delivery_date, Length: 5000, dtype: datetime64[ns]

In [39]:
df[['delivery_date', 'order_date']]

     delivery_date order_date
0       2021-04-06 2021-04-04
1       2021-04-06 2021-04-04
2       2021-04-01 2021-03-06
3       2021-04-01 2021-03-06
4       2021-04-01 2021-03-06
...            ...        ...
4995    2021-10-13 2021-10-11
4996    2021-10-13 2021-10-11
4997    2021-10-13 2021-10-11
4998    2021-10-13 2021-10-11
4999    2021-10-13 2021-10-11

[5000 rows x 2 columns]

In [40]:
# what is the maximum number of days between the order and delivery
df['difference_days'] = df.delivery_date - df.order_date
df['difference_days']

0       2 days
1       2 days
2      26 days
3      26 days
4      26 days
         ...
4995    2 days
4996    2 days
4997    2 days
4998    2 days
4999    2 days
Name: difference_days, Length: 5000, dtype: timedelta64[ns]

In [42]:
df['difference_days'].sort_values(ascending= False).head(10)

4360   27 days
1237   27 days
1343   27 days
1342   27 days
1341   27 days
1340   27 days
1339   27 days
1338   27 days
1337   27 days
1336   27 days
Name: difference_days, dtype: timedelta64[ns]

In [43]:
df.head()

,customer_id,gender,age,zip_code,city,state,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,total_price,product_ID,product_type,product_name,size,colour,price,order_quantity,stock_quantity,difference_days
0,1,Female,30,5464,Johnstonhaven,Northern Territory,455,24550,2021-04-04,2021-04-06,2245,211,106,318,211,Shirt,Chambray,S,red,105,3,72,2 days
1,1,Female,30,5464,Johnstonhaven,Northern Territory,455,24550,2021-04-04,2021-04-06,2246,783,91,182,783,Jacket,Pullover,L,yellow,114,2,43,2 days
2,1,Female,30,5464,Johnstonhaven,Northern Territory,670,10246,2021-03-06,2021-04-01,3324,525,98,196,525,Jacket,Leather,XS,red,113,2,67,26 days
3,1,Female,30,5464,Johnstonhaven,Northern Territory,670,10246,2021-03-06,2021-04-01,3325,792,91,182,792,Jacket,Pullover,M,blue,114,2,44,26 days
4,1,Female,30,5464,Johnstonhaven,Northern Territory,670,10246,2021-03-06,2021-04-01,3326,179,98,98,179,Shirt,Camp Collared,XL,red,112,1,79,26 days

In [44]:
# df.order_date.dt.year
# df.order_date.dt.month
# df.order_date.dt.month_name()
# df.order_date.dt.day
# df.order_date.dt.day_name()
# df.order_date.dt.weekday
# df.order_date.dt.day_of_year

In [45]:
# extract year , month and day name for order data
df['order_year'] = df.order_date.dt.year

df['order_month'] = df.order_date.dt.month

df['order_day'] = df.order_date.dt.day_name()

df.head(1)

,customer_id,gender,age,zip_code,city,state,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,total_price,product_ID,product_type,product_name,size,colour,price,order_quantity,stock_quantity,difference_days,order_year,order_month,order_day
0,1,Female,30,5464,Johnstonhaven,Northern Territory,455,24550,2021-04-04,2021-04-06,2245,211,106,318,211,Shirt,Chambray,S,red,105,3,72,2 days,2021,4,Sunday

In [46]:
df.order_date.dt.day_name()

0         Sunday
1         Sunday
2       Saturday
3       Saturday
4       Saturday
          ...
4995      Monday
4996      Monday
4997      Monday
4998      Monday
4999      Monday
Name: order_date, Length: 5000, dtype: object

In [47]:
# extract year , month and day name for delivery data
df['delivery_year'] = df.delivery_date.dt.year

df['delivery_month'] = df.delivery_date.dt.month

df['delivery_day'] = df.delivery_date.dt.day_name()

df.head(1)

,customer_id,gender,age,zip_code,city,state,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,total_price,product_ID,product_type,product_name,size,colour,price,order_quantity,stock_quantity,difference_days,order_year,order_month,order_day,delivery_year,delivery_month,delivery_day
0,1,Female,30,5464,Johnstonhaven,Northern Territory,455,24550,2021-04-04,2021-04-06,2245,211,106,318,211,Shirt,Chambray,S,red,105,3,72,2 days,2021,4,Sunday,2021,4,Tuesday

In [48]:
# what is the total money that each gendre spent
df.groupby('gender')['payment'].sum().sort_values(ascending= False)

gender
Female         24921476
Genderfluid    24720908
Male           22608847
Polygender     21701530
Genderqueer    20568185
Non-binary     20421074
Agender        18240827
Bigender       16701078
Name: payment, dtype: int64

In [49]:
# what is the most day that get highest revenue
df.groupby('order_day')['payment'].sum().sort_values(ascending= False)

order_day
Sunday       29090660
Wednesday    26434750
Tuesday      24205904
Thursday     23793643
Monday       22515824
Friday       22021604
Saturday     21821540
Name: payment, dtype: int64

In [50]:
df.head(1)

,customer_id,gender,age,zip_code,city,state,order_id,payment,order_date,delivery_date,sales_id,product_id,price_per_unit,total_price,product_ID,product_type,product_name,size,colour,price,order_quantity,stock_quantity,difference_days,order_year,order_month,order_day,delivery_year,delivery_month,delivery_day
0,1,Female,30,5464,Johnstonhaven,Northern Territory,455,24550,2021-04-04,2021-04-06,2245,211,106,318,211,Shirt,Chambray,S,red,105,3,72,2 days,2021,4,Sunday,2021,4,Tuesday

In [51]:
# what is the highest month that get the highest sales?
df.groupby('order_month')['order_id'].count().sort_values(ascending= False)

order_month
3     635
1     577
7     567
8     505
6     501
4     478
2     467
9     458
5     417
10    395
Name: order_id, dtype: int64

In [52]:
# what is the highest state achieve the highest salees
df.groupby('state')['order_id'].count().sort_values(ascending= False)

state
South Australia                 718
Queensland                      687
New South Wales                 647
Australian Capital Territory    638
Western Australia               604
Victoria                        591
Tasmania                        586
Northern Territory              529
Name: order_id, dtype: int64

In [53]:
# what is the highest state per gender achieve the highest sales
df.groupby(['state', 'gender'])['order_id'].count().head(20)

state                         gender
Australian Capital Territory  Agender        116
                              Bigender        61
                              Female          96
                              Genderfluid    106
                              Genderqueer     43
                              Male           106
                              Non-binary      44
                              Polygender      66
New South Wales               Agender         59
                              Bigender        56
                              Female          97
                              Genderfluid    111
                              Genderqueer     53
                              Male           105
                              Non-binary     104
                              Polygender      62
Northern Territory            Agender         62
                              Bigender        48
                              Female          76
                              Genderfluid     73
Name: order_id, dtype: int64

In [54]:
df.pivot_table('order_id', index= 'state', columns= 'gender', aggfunc= 'count')

gender,Agender,Bigender,Female,Genderfluid,Genderqueer,Male,Non-binary,Polygender
state,,,,,,,,
Australian Capital Territory,116,61,96,106,43,106,44,66
New South Wales,59,56,97,111,53,105,104,62
Northern Territory,62,48,76,73,82,53,76,59
Queensland,79,57,83,101,118,79,37,133
South Australia,74,85,92,64,121,99,76,107
Tasmania,30,88,102,41,98,76,105,46
Victoria,38,54,106,106,48,128,50,61
Western Australia,68,73,60,85,84,26,106,102

In [56]:
# what is the average age per state
df.groupby('state')['age'].mean().sort_values(ascending= False)

state
New South Wales                 53.593509
Queensland                      51.152838
Northern Territory              48.882798
South Australia                 48.594708
Tasmania                        48.187713
Australian Capital Territory    48.021944
Western Australia               46.804636
Victoria                        44.143824
Name: age, dtype: float64

In [57]:
# what is the average age per state per each gender
df.groupby(['state', 'gender'])['age'].mean().head(20)

state                         gender
Australian Capital Territory  Agender        43.879310
                              Bigender       48.934426
                              Female         56.666667
                              Genderfluid    47.311321
                              Genderqueer    42.976744
                              Male           46.000000
                              Non-binary     48.500000
                              Polygender     49.242424
New South Wales               Agender        48.457627
                              Bigender       55.267857
                              Female         58.000000
                              Genderfluid    46.774775
                              Genderqueer    54.660377
                              Male           55.685714
                              Non-binary     57.528846
                              Polygender     51.225806
Northern Territory            Agender        49.838710
                              Bigender       42.750000
                              Female         47.052632
                              Genderfluid    49.821918
Name: age, dtype: float64

In [58]:
df.pivot_table(values= 'age', index= 'state', columns= 'gender')

gender,Agender,Bigender,Female,Genderfluid,Genderqueer,Male,Non-binary,Polygender
state,,,,,,,,
Australian Capital Territory,43.879310,48.934426,56.666667,47.311321,42.976744,46.000000,48.500000,49.242424
New South Wales,48.457627,55.267857,58.000000,46.774775,54.660377,55.685714,57.528846,51.225806
Northern Territory,49.838710,42.750000,47.052632,49.821918,49.865854,45.754717,54.223684,48.627119
Queensland,43.835443,52.631579,50.819277,55.405941,48.237288,57.987342,70.405405,45.015038
South Australia,44.743243,57.070588,43.902174,50.562500,53.702479,49.777778,51.355263,38.551402
Tasmania,45.333333,49.931818,41.107843,33.756098,60.224490,47.855263,47.980952,50.652174
Victoria,42.973684,50.277778,47.650943,43.188679,42.625000,42.765625,32.900000,48.311475
Western Australia,44.970588,47.054795,33.816667,35.517647,43.154762,47.923077,62.254717,51.558824

In [59]:
# what is the product type that have the highest revenue
df.groupby('product_type')['payment'].max().sort_values(ascending= False)

product_type
Jacket      59910
Trousers    59910
Shirt       59876
Name: payment, dtype: int64

In [60]:
# what is the color of the product type that have highest sales?
df.groupby(['product_type', 'colour'])['payment'].max()

product_type  colour
Jacket        blue      59910
              green     59748
              indigo    59414
              orange    59708
              red       59910
              violet    59558
              yellow    59558
Shirt         blue      59554
              green     58886
              indigo    59828
              orange    59055
              red       59828
              violet    59876
              yellow    59708
Trousers      blue      59876
              green     59414
              indigo    59876
              orange    59828
              red       59910
              violet    59554
              yellow    59910
Name: payment, dtype: int64