# Introduction

The dataset is from kaggle you can view it and understand columns from this link
https://www.kaggle.com/lava18/google-play-store-apps


## Questions

- What is the most expensive app on the store.
- Which Genre has more apps.
- What is the average size of the free apps & paid apps.
- What is the 5 top expenisve apps that has rate of 5.
- How many apps that has more than 50K reviews.
- What is the average price of the apps for each genre with each installs numbers.
- How many apps have rating > 4.7 and what is thier avg price.
- How much google earned from the 5,000,000+ installed apps
- What is the max and min size for free and paid apps.
- is there a correlation between rating, Reviews, Size with the price of the app
- How many apps for each type for each content reading.
- How many apps that can work on android version 4

# Import necessary Libraries

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

# Load Dataset

In [2]:
df = pd.read_csv('googleplaystore.csv')
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

# Data Exploration

In [3]:
# Check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [4]:
# Check summary statistics fro numerical
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [5]:
# Check summary statistics for categorical
df.describe(include= 'object')

,App,Category,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,596,1695,1579,10039,10040,8714,842,326,1459,2451

In [6]:
# check missing values
df.isna().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [7]:
# check missing values percentage
(df.isna().mean() * 100).round(2)

App                0.00
Category           0.00
Rating            13.60
Reviews            0.00
Size               0.00
Installs           0.00
Type               0.01
Price              0.00
Content Rating     0.01
Genres             0.00
Last Updated       0.00
Current Ver        0.07
Android Ver        0.03
dtype: float64

In [8]:
# Check duplicates
df.duplicated().sum()

483

In [9]:
df[df.App == 'Quick PDF Scanner + OCR FREE']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
222,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
285,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80804,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up

In [10]:
df[df.duplicated()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,Varies with device,"10,000,000+",Free,0,Everyone,Productivity,"April 6, 2018",Varies with device,Varies with device
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,Varies with device,"1,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,Varies with device,"100,000,000+",Free,0,Everyone,Productivity,"June 27, 2018",Varies with device,Varies with device
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86M,"10,000+",Free,0,Everyone,Medical,"June 1, 2018",0.6.88,5.0 and up
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

In [11]:
df.drop_duplicates(inplace= True, ignore_index= True)

In [12]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10353,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10354,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10355,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10356,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10357,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [13]:
# check missing values percentage
(df.isna().mean() * 100).round(2)

App                0.00
Category           0.00
Rating            14.14
Reviews            0.00
Size               0.00
Installs           0.00
Type               0.01
Price              0.00
Content Rating     0.01
Genres             0.00
Last Updated       0.00
Current Ver        0.08
Android Ver        0.03
dtype: float64

# Data Cleaning

### For Numerical Columns

In [14]:
px.histogram(data_frame= df, x= 'Rating')

In [15]:
drop_index = df[df.Rating == 19].index
drop_index

Index([9990], dtype='int64')

In [16]:
df.drop(drop_index, inplace= True)

In [17]:
df.reset_index(drop= True, inplace= True)

In [18]:
px.histogram(data_frame= df, x= 'Rating')

### For Categorical Columns

In [19]:
cat_cols = df.select_dtypes(include= 'object').columns
cat_cols

Index(['App', 'Category', 'Reviews', 'Size', 'Installs', 'Type', 'Price',
       'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [20]:
for col in cat_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 100)

App
9659
['Photo Editor & Candy Camera & Grid & ScrapBook' 'Coloring book moana'
 'U Launcher Lite – FREE Live Cool Themes, Hide Apps' ...
 'Parkinson Exercices FR' 'The SCP Foundation DB fr nn5n'
 'iHoroscope - 2018 Daily Horoscope & Astrology']
----------------------------------------------------------------------------------------------------
Category
33
['ART_AND_DESIGN' 'AUTO_AND_VEHICLES' 'BEAUTY' 'BOOKS_AND_REFERENCE'
 'BUSINESS' 'COMICS' 'COMMUNICATION' 'DATING' 'EDUCATION' 'ENTERTAINMENT'
 'EVENTS' 'FINANCE' 'FOOD_AND_DRINK' 'HEALTH_AND_FITNESS' 'HOUSE_AND_HOME'
 'LIBRARIES_AND_DEMO' 'LIFESTYLE' 'GAME' 'FAMILY' 'MEDICAL' 'SOCIAL'
 'SHOPPING' 'PHOTOGRAPHY' 'SPORTS' 'TRAVEL_AND_LOCAL' 'TOOLS'
 'PERSONALIZATION' 'PRODUCTIVITY' 'PARENTING' 'WEATHER' 'VIDEO_PLAYERS'
 'NEWS_AND_MAGAZINES' 'MAPS_AND_NAVIGATION']
----------------------------------------------------------------------------------------------------
Reviews
6001
['159' '967' '87510' ... '603' '1195' '398307']
----------------------------------------------------------------------------------------------------
Size
461
['19M' '14M' '8.7M' '25M' '2.8M' '5.6M' '29M' '33M' '3.1M' '28M' '12M'
 '20M' '21M' '37M' '2.7M' '5.5M' '17M' '39M' '31M' '4.2M' '7.0M' '23M'
 '6.0M' '6.1M' '4.6M' '9.2M' '5.2M' '11M' '24M' 'Varies with device'
 '9.4M' '15M' '10M' '1.2M' '26M' '8.0M' '7.9M' '56M' '57M' '35M' '54M'
 '201k' '3.6M' '5.7M' '8.6M' '2.4M' '27M' '2.5M' '16M' '3.4M' '8.9M'
 '3.9M' '2.9M' '38M' '32M' '5.4M' '18M' '1.1M' '2.2M' '4.5M' '9.8M' '52M'
 '9.0M' '6.7M' '30M' '2.6M' '7.1M' '3.7M' '22M' '7.4M' '6.4M' '3.2M'
 '8.2M' '9.9M' '4.9M' '9.5M' '5.0M' '5.9M' '13M' '73M' '6.8M' '3.5M'
 '4.0M' '2.3M' '7.2M' '2.1M' '42M' '7.3M' '9.1M' '55M' '23k' '6.5M' '1.5M'
 '7.5M' '51M' '41M' '48M' '8.5M' '46M' '8.3M' '4.3M' '4.7M' '3.3M' '40M'
 '7.8M' '8.8M' '6.6M' '5.1M' '61M' '66M' '79k' '8.4M' '118k' '44M' '695k'
 '1.6M' '6.2M' '18k' '53M' '1.4M' '3.0M' '5.8M' '3.8M' '9.6M' '45M' '63M'
 '49M' '77M' '4.4M' '4.8M' '70M' '6.9M' '9.3M' '10.0M' '8.1M' '36M' '84M'
 '97M' '2.0M' '1.9M' '1.8M' '5.3M' '47M' '556k' '526k' '76M' '7.6M' '59M'
 '9.7M' '78M' '72M' '43M' '7.7M' '6.3M' '334k' '34M' '93M' '65M' '79M'
 '100M' '58M' '50M' '68M' '64M' '67M' '60M' '94M' '232k' '99M' '624k'
 '95M' '8.5k' '41k' '292k' '11k' '80M' '1.7M' '74M' '62M' '69M' '75M'
 '98M' '85M' '82M' '96M' '87M' '71M' '86M' '91M' '81M' '92M' '83M' '88M'
 '704k' '862k' '899k' '378k' '266k' '375k' '1.3M' '975k' '980k' '4.1M'
 '89M' '696k' '544k' '525k' '920k' '779k' '853k' '720k' '713k' '772k'
 '318k' '58k' '241k' '196k' '857k' '51k' '953k' '865k' '251k' '930k'
 '540k' '313k' '746k' '203k' '26k' '314k' '239k' '371k' '220k' '730k'
 '756k' '91k' '293k' '17k' '74k' '14k' '317k' '78k' '924k' '902k' '818k'
 '81k' '939k' '169k' '45k' '475k' '965k' '90M' '545k' '61k' '283k' '655k'
 '714k' '93k' '872k' '121k' '322k' '1.0M' '976k' '172k' '238k' '549k'
 '206k' '954k' '444k' '717k' '210k' '609k' '308k' '705k' '306k' '904k'
 '473k' '175k' '350k' '383k' '454k' '421k' '70k' '812k' '442k' '842k'
 '417k' '412k' '459k' '478k' '335k' '782k' '721k' '430k' '429k' '192k'
 '200k' '460k' '728k' '496k' '816k' '414k' '506k' '887k' '613k' '243k'
 '569k' '778k' '683k' '592k' '319k' '186k' '840k' '647k' '191k' '373k'
 '437k' '598k' '716k' '585k' '982k' '222k' '219k' '55k' '948k' '323k'
 '691k' '511k' '951k' '963k' '25k' '554k' '351k' '27k' '82k' '208k' '913k'
 '514k' '551k' '29k' '103k' '898k' '743k' '116k' '153k' '209k' '353k'
 '499k' '173k' '597k' '809k' '122k' '411k' '400k' '801k' '787k' '237k'
 '50k' '643k' '986k' '97k' '516k' '837k' '780k' '961k' '269k' '20k' '498k'
 '600k' '749k' '642k' '881k' '72k' '656k' '601k' '221k' '228k' '108k'
 '940k' '176k' '33k' '663k' '34k' '942k' '259k' '164k' '458k' '245k'
 '629k' '28k' '288k' '775k' '785k' '636k' '916k' '994k' '309k' '485k'
 '914k' '903k' '608k' '500k' '54k' '562k' '847k' '957k' '688k' '811k'
 '270k' '48k' '329k' '523k' '921k' '874k' '981k' '784k' '280k' '24k'
 '518k' '754k' '892k' '154k' '860k' '364k' '387k' '626k' '161k' '879k'
 '39k' '970k' '170k' '141k' '160k' '144k' '143k' '190k' '376k' '193k'
 '246k' '73k' '658k' '992k' '253k' '420k' '404k' '470k' '226k' '240k'
 '89k' '234k' '257k' '861k' '467k' '157k' '44k' '676k' '67k' '552k' '885k'
 '1020k' '582k' '619k']
----------------------------------------------------------------------------------------------------
Installs
21
['10,000+' '500,000+' '5,000,000+' '50,000,000+' '100,000+' '50,000+'
 '1,000,000+' '10,000,000+' '5,000+' '100,000,000+' '1,000,000,000+'
 '1,000+' '500,000,000+' '50+' '100+' '500+' '10+' '1+' '5+' '0+' '0']
----------------------------------------------------------------------------------------------------
Type
2
['Free' 'Paid' nan]
----------------------------------------------------------------------------------------------------
Price
92
['0' '$4.99' '$3.99' '$6.99' '$1.49' '$2.99' '$7.99' '$5.99' '$3.49'
 '$1.99' '$9.99' '$7.49' '$0.99' '$9.00' '$5.49' '$10.00' '$24.99'
 '$11.99' '$79.99' '$16.99' '$14.99' '$1.00' '$29.99' '$12.99' '$2.49'
 '$10.99' '$1.50' '$19.99' '$15.99' '$33.99' '$74.99' '$39.99' '$3.95'
 '$4.49' '$1.70' '$8.99' '$2.00' '$3.88' '$25.99' '$399.99' '$17.99'
 '$400.00' '$3.02' '$1.76' '$4.84' '$4.77' '$1.61' '$2.50' '$1.59' '$6.49'
 '$1.29' '$5.00' '$13.99' '$299.99' '$379.99' '$37.99' '$18.99' '$389.99'
 '$19.90' '$8.49' '$1.75' '$14.00' '$4.85' '$46.99' '$109.99' '$154.99'
 '$3.08' '$2.59' '$4.80' '$1.96' '$19.40' '$3.90' '$4.59' '$15.46' '$3.04'
 '$4.29' '$2.60' '$3.28' '$4.60' '$28.99' '$2.95' '$2.90' '$1.97'
 '$200.00' '$89.99' '$2.56' '$30.99' '$3.61' '$394.99' '$1.26' '$1.20'
 '$1.04']
----------------------------------------------------------------------------------------------------
Content Rating
6
['Everyone' 'Teen' 'Everyone 10+' 'Mature 17+' 'Adults only 18+' 'Unrated']
----------------------------------------------------------------------------------------------------
Genres
119
['Art & Design' 'Art & Design;Pretend Play' 'Art & Design;Creativity'
 'Art & Design;Action & Adventure' 'Auto & Vehicles' 'Beauty'
 'Books & Reference' 'Business' 'Comics' 'Comics;Creativity'
 'Communication' 'Dating' 'Education;Education' 'Education'
 'Education;Creativity' 'Education;Music & Video'
 'Education;Action & Adventure' 'Education;Pretend Play'
 'Education;Brain Games' 'Entertainment' 'Entertainment;Music & Video'
 'Entertainment;Brain Games' 'Entertainment;Creativity' 'Events' 'Finance'
 'Food & Drink' 'Health & Fitness' 'House & Home' 'Libraries & Demo'
 'Lifestyle' 'Lifestyle;Pretend Play' 'Adventure;Action & Adventure'
 'Arcade' 'Casual' 'Card' 'Casual;Pretend Play' 'Action' 'Strategy'
 'Puzzle' 'Sports' 'Music' 'Word' 'Racing' 'Casual;Creativity'
 'Casual;Action & Adventure' 'Simulation' 'Adventure' 'Board' 'Trivia'
 'Role Playing' 'Simulation;Education' 'Action;Action & Adventure'
 'Casual;Brain Games' 'Simulation;Action & Adventure'
 'Educational;Creativity' 'Puzzle;Brain Games' 'Educational;Education'
 'Card;Brain Games' 'Educational;Brain Games' 'Educational;Pretend Play'
 'Entertainment;Education' 'Casual;Education' 'Music;Music & Video'
 'Racing;Action & Adventure' 'Arcade;Pretend Play'
 'Role Playing;Action & Adventure' 'Simulation;Pretend Play'
 'Puzzle;Creativity' 'Sports;Action & Adventure'
 'Educational;Action & Adventure' 'Arcade;Action & Adventure'
 'Entertainment;Action & Adventure' 'Puzzle;Action & Adventure'
 'Strategy;Action & Adventure' 'Music & Audio;Music & Video'
 'Health & Fitness;Education' 'Adventure;Education' 'Board;Brain Games'
 'Board;Action & Adventure' 'Board;Pretend Play' 'Casual;Music & Video'
 'Role Playing;Pretend Play' 'Entertainment;Pretend Play'
 'Video Players & Editors;Creativity' 'Card;Action & Adventure' 'Medical'
 'Social' 'Shopping' 'Photography' 'Travel & Local'
 'Travel & Local;Action & Adventure' 'Tools' 'Tools;Education'
 'Personalization' 'Productivity' 'Parenting' 'Parenting;Music & Video'
 'Parenting;Education' 'Parenting;Brain Games' 'Weather'
 'Video Players & Editors' 'Video Players & Editors;Music & Video'
 'News & Magazines' 'Maps & Navigation'
 'Health & Fitness;Action & Adventure' 'Educational' 'Casino'
 'Adventure;Brain Games' 'Trivia;Education' 'Lifestyle;Education'
 'Books & Reference;Creativity' 'Books & Reference;Education'
 'Puzzle;Education' 'Role Playing;Education' 'Role Playing;Brain Games'
 'Strategy;Education' 'Racing;Pretend Play' 'Communication;Creativity'
 'Strategy;Creativity']
----------------------------------------------------------------------------------------------------
Last Updated
1377
['January 7, 2018' 'January 15, 2018' 'August 1, 2018' ...
 'January 20, 2014' 'February 16, 2014' 'March 23, 2014']
----------------------------------------------------------------------------------------------------
Current Ver
2831
['1.0.0' '2.0.0' '1.2.4' ... '1.0.612928' '0.3.4' '2.0.148.0']
----------------------------------------------------------------------------------------------------
Android Ver
33
['4.0.3 and up' '4.2 and up' '4.4 and up' '2.3 and up' '3.0 and up'
 '4.1 and up' '4.0 and up' '2.3.3 and up' 'Varies with device'
 '2.2 and up' '5.0 and up' '6.0 and up' '1.6 and up' '1.5 and up'
 '2.1 and up' '7.0 and up' '5.1 and up' '4.3 and up' '4.0.3 - 7.1.1'
 '2.0 and up' '3.2 and up' '4.4W and up' '7.1 and up' '7.0 - 7.1.1'
 '8.0 and up' '5.0 - 8.0' '3.1 and up' '2.0.1 and up' '4.1 - 7.1.1' nan
 '5.0 - 6.0' '1.0 and up' '2.2 - 7.1.1' '5.0 - 7.1.1']
----------------------------------------------------------------------------------------------------

In [21]:
df[df['Size'] == 'Varies with device']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
37,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,Varies with device,"5,000,000+",Free,0,Everyone,Art & Design,"July 14, 2018",Varies with device,2.3.3 and up
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,Varies with device,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device
52,Used Cars and Trucks for Sale,AUTO_AND_VEHICLES,4.6,17057,Varies with device,"1,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device
67,Ulysse Speedometer,AUTO_AND_VEHICLES,4.3,40211,Varies with device,"5,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device
68,REPUVE,AUTO_AND_VEHICLES,3.9,356,Varies with device,"100,000+",Free,0,Everyone,Auto & Vehicles,"May 25, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10230,My Earthquake Alerts - US & Worldwide Earthquakes,WEATHER,4.4,3471,Varies with device,"100,000+",Free,0,Everyone,Weather,"July 24, 2018",Varies with device,Varies with device
10242,Posta App,MAPS_AND_NAVIGATION,3.6,8,Varies with device,"1,000+",Free,0,Everyone,Maps & Navigation,"September 27, 2017",Varies with device,4.4 and up
10282,Chat For Strangers - Video Chat,SOCIAL,3.4,622,Varies with device,"100,000+",Free,0,Mature 17+,Social,"May 23, 2018",Varies with device,Varies with device
10342,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486,Varies with device,"5,000,000+",Free,0,Mature 17+,Social,"March 23, 2018",Varies with device,Varies with device
10355,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device

In [22]:
df.Reviews = df.Reviews.astype('int')
df.Reviews

0           159
1           967
2         87510
3        215644
4           967
          ...
10352        38
10353         4
10354         3
10355       114
10356    398307
Name: Reviews, Length: 10357, dtype: int32

In [23]:
df['Size']

0                       19M
1                       14M
2                      8.7M
3                       25M
4                      2.8M
                ...
10352                   53M
10353                  3.6M
10354                  9.5M
10355    Varies with device
10356                   19M
Name: Size, Length: 10357, dtype: object

In [24]:
def clean_size(x):

    if type(x) == float:
        return x
    
    elif x == 'Varies with device':
        return x
    
    elif 'M' in x:
        return x
    
    elif 'k' in x:
        return str(round(float(x[:-1]) / 1024, 1)) + 'M'
    
    else:
        return x
    
df['Size'] = df['Size'].apply(clean_size)
df['Size']

0                       19M
1                       14M
2                      8.7M
3                       25M
4                      2.8M
                ...
10352                   53M
10353                  3.6M
10354                  9.5M
10355    Varies with device
10356                   19M
Name: Size, Length: 10357, dtype: object

In [25]:
str(round(float('498k'[:-1]) / 1024, 1)) + 'M'

'0.5M'

In [26]:
df.Installs.unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0'], dtype=object)

In [27]:
def clean_installs(x):

    if x in ['10+', '1+', '5+', '0+', '0', '50+', '100+', '500+']:
        return '< 1000'
    
    elif x in ['1,000+', '5,000+', '50,000+', '10,000+']:
        return '< 100000'
    
    elif x in ['100,000+', '500,000+']:
        return '< 1000000'
    
    else:
        return '>= 1000000'
    
df.Installs = df.Installs.apply(clean_installs)
df.Installs

0          < 100000
1         < 1000000
2        >= 1000000
3        >= 1000000
4         < 1000000
            ...
10352      < 100000
10353        < 1000
10354      < 100000
10355      < 100000
10356    >= 1000000
Name: Installs, Length: 10357, dtype: object

In [28]:
df.Price = df.Price.str.replace('$', '').astype(float)
df.Price

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
10352    0.0
10353    0.0
10354    0.0
10355    0.0
10356    0.0
Name: Price, Length: 10357, dtype: float64

In [29]:
df.Price.unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

In [30]:
df['last_updated_year'] = df['Last Updated'].str[-4 : ].astype(int)
df['last_updated_year']

0        2018
1        2018
2        2018
3        2018
4        2018
         ...
10352    2017
10353    2018
10354    2017
10355    2015
10356    2018
Name: last_updated_year, Length: 10357, dtype: int32

In [31]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'last_updated_year'],
      dtype='object')

In [32]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,last_updated_year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,< 100000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,< 1000000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,>= 1000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,>= 1000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,< 1000000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2018

In [33]:
df[['Type', 'Current Ver', 'Content Rating', 'Android Ver']].isna().sum()

Type              1
Current Ver       8
Content Rating    0
Android Ver       2
dtype: int64

In [34]:
df.dropna(subset= ['Type', 'Current Ver', 'Android Ver'], inplace= True, ignore_index= True)

In [35]:
df[['Type', 'Current Ver', 'Content Rating', 'Android Ver']].isna().sum()

Type              0
Current Ver       0
Content Rating    0
Android Ver       0
dtype: int64

In [36]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,last_updated_year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,< 100000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,< 1000000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,>= 1000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,>= 1000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,< 1000000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2018

In [37]:
df.dropna(subset= 'Rating', ignore_index= True, inplace= True)

In [38]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,last_updated_year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,< 100000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,< 1000000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,>= 1000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,>= 1000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,< 1000000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8881,FR Calculator,FAMILY,4.0,7,2.6M,< 1000,Free,0.0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up,2017
8882,Sya9a Maroc - FR,FAMILY,4.5,38,53M,< 100000,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,2017
8883,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,< 1000,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,2018
8884,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,< 100000,Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,2015
8885,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,>= 1000000,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,2018

# Univariate Analysis

In [39]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,last_updated_year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,< 100000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,< 1000000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,>= 1000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,>= 1000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,< 1000000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8881,FR Calculator,FAMILY,4.0,7,2.6M,< 1000,Free,0.0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up,2017
8882,Sya9a Maroc - FR,FAMILY,4.5,38,53M,< 100000,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,2017
8883,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,< 1000,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,2018
8884,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,< 100000,Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,2015
8885,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,>= 1000000,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,2018

### What is the percetnage of application types ?

In [40]:
px.pie(data_frame= df, names= 'Type')

### Bivariate Analysis

### What is the average number of Reviews per Content Rating ?

In [41]:
reviews_per_content = df.groupby('Content Rating')['Reviews'].mean().sort_values(ascending= False).reset_index()
reviews_per_content

    Content Rating       Reviews
0     Everyone 10+  1.638459e+06
1             Teen  9.777754e+05
2       Mature 17+  3.683880e+05
3         Everyone  3.474793e+05
4  Adults only 18+  2.711600e+04
5          Unrated  1.186000e+03

In [42]:
px.bar(data_frame= reviews_per_content, x= 'Content Rating', y= 'Reviews', 
       labels= {'Reviews' : 'Average No of Reviews'}, title= 'Average Reviews per Content Rating',
       text_auto= True)

### Multivariate

### What is the average number of Reviews per Content Rating per App Type ?

In [43]:
content_type_review = df.groupby(['Content Rating', 'Type'])['Reviews'].mean().reset_index()
content_type_review

    Content Rating  Type       Reviews
0  Adults only 18+  Free  2.711600e+04
1         Everyone  Free  3.744727e+05
2         Everyone  Paid  5.059403e+03
3     Everyone 10+  Free  1.782626e+06
4     Everyone 10+  Paid  1.607546e+05
5       Mature 17+  Free  3.813284e+05
6       Mature 17+  Paid  4.892219e+04
7             Teen  Free  1.022243e+06
8             Teen  Paid  1.233758e+04
9          Unrated  Free  1.186000e+03

In [44]:
px.bar(data_frame= content_type_review, x= 'Content Rating', y= 'Reviews', 
       labels= {'Reviews' : 'Average No of Reviews'}, title= 'Average Reviews per Content Rating per Type',
       text_auto= True, color= 'Type', barmode= 'group')

In [45]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,last_updated_year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,< 100000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,< 1000000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,>= 1000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,>= 1000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,< 1000000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2018

### Data Preprocessing

In [46]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,last_updated_year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,< 100000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,2018
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,< 1000000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,>= 1000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,>= 1000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,< 1000000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,2018

In [47]:
def convert_rating(x):

    if x >= 3.5:
        return 'Good Rate'
    
    else:
        return 'Bad Rate'
    
df.Rating = df.Rating.apply(convert_rating)
df.Rating

0       Good Rate
1       Good Rate
2       Good Rate
3       Good Rate
4       Good Rate
          ...
8881    Good Rate
8882    Good Rate
8883    Good Rate
8884    Good Rate
8885    Good Rate
Name: Rating, Length: 8886, dtype: object

In [48]:
df.select_dtypes(include= 'object').drop(['App', 'Last Updated', 'Current Ver', 'Android Ver'], axis= 1)

,Category,Rating,Size,Installs,Type,Content Rating,Genres
0,ART_AND_DESIGN,Good Rate,19M,< 100000,Free,Everyone,Art & Design
1,ART_AND_DESIGN,Good Rate,14M,< 1000000,Free,Everyone,Art & Design;Pretend Play
2,ART_AND_DESIGN,Good Rate,8.7M,>= 1000000,Free,Everyone,Art & Design
3,ART_AND_DESIGN,Good Rate,25M,>= 1000000,Free,Teen,Art & Design
4,ART_AND_DESIGN,Good Rate,2.8M,< 1000000,Free,Everyone,Art & Design;Creativity
...,...,...,...,...,...,...,...
8881,FAMILY,Good Rate,2.6M,< 1000,Free,Everyone,Education
8882,FAMILY,Good Rate,53M,< 100000,Free,Everyone,Education
8883,FAMILY,Good Rate,3.6M,< 1000,Free,Everyone,Education
8884,BOOKS_AND_REFERENCE,Good Rate,Varies with device,< 100000,Free,Mature 17+,Books & Reference
8885,LIFESTYLE,Good Rate,19M,>= 1000000,Free,Everyone,Lifestyle

In [49]:
df.drop(['Last Updated', 'Current Ver', 'Android Ver'], axis= 1, inplace=True)

In [50]:
df.duplicated().sum()

2

In [51]:
df.drop_duplicates(inplace= True, ignore_index= True)

In [52]:
df.duplicated().sum()

0

In [53]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,last_updated_year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,Good Rate,159,19M,< 100000,Free,0.0,Everyone,Art & Design,2018
1,Coloring book moana,ART_AND_DESIGN,Good Rate,967,14M,< 1000000,Free,0.0,Everyone,Art & Design;Pretend Play,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,Good Rate,87510,8.7M,>= 1000000,Free,0.0,Everyone,Art & Design,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,Good Rate,215644,25M,>= 1000000,Free,0.0,Teen,Art & Design,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,Good Rate,967,2.8M,< 1000000,Free,0.0,Everyone,Art & Design;Creativity,2018

In [54]:
df.to_csv('cleaned_df.csv')

In [55]:
import streamlit as st

In [104]:
%%writefile app.py

import pandas as pd
import streamlit as st
import plotly.express as px

st.set_page_config(layout= 'wide', page_title= 'Goodle Play EDA')

# st.title('Google Play Exploratory Data Analysis')

st.markdown("<h1 style='text-align: center; color: white;'>Google Play Exploratory Data Analysis</h1>", unsafe_allow_html=True)

st.image('https://cdn.freebiesupply.com/logos/large/2x/google-play-badge-1-logo-png-transparent.png')

df = pd.read_csv('cleaned_df.csv', index_col= 0)

page = st.sidebar.radio('Pages', ['Introduction', 'Analysis Questions', 'Reporting'])

if page == 'Introduction':

    st.dataframe(df.head())

    st.header('Data Description')

    st.write('''Category : Category the app belongs to

Rating : Overall user rating of the app (as when scraped)


Reviews : Number of user reviews for the app (as when scraped)


Size : Size of the app (as when scraped)


Installs : Number of user downloads/installs for the app (as when scraped)


Type : Paid or Free


Price : Price of the app (as when scraped)


Content Rating : Age group the app is targeted at - Children / Mature 21+ / Adult


Genres : An app can belong to multiple genres (apart from its main category). For eg, a musical family game will belong to Music, Game, Family genres.''')

elif page == 'Analysis Questions':

    st.header('What is the most expensive App on the store ?')
    st.write(df.sort_values(by= 'Price', ascending= False)[['App', 'Price']].head(1))

    st.header('How many applications that has more than 50k reviews')

    if st.button('Check answer'):
        st.write(df[df.Reviews > 50000]['App'].nunique())

    st.header('What is the Average Reviews per Content Rating per Type ?')
    content_type_review = df.groupby(['Content Rating', 'Type'])['Reviews'].mean().reset_index()
    st.plotly_chart(px.bar(data_frame= content_type_review, x= 'Content Rating', y= 'Reviews', 
       labels= {'Reviews' : 'Average No of Reviews'}, title= 'Average Reviews per Content Rating per Type',
       text_auto= True, color= 'Type', barmode= 'group'))

elif page == 'Reporting':

    year = st.sidebar.selectbox('Year', df['last_updated_year'].unique())

    category = st.sidebar.selectbox('Category', df['Category'].unique())

    df_2 = df[(df['last_updated_year'] == year) & (df['Category'] == category)]

    st.dataframe(df_2)

Overwriting app.py

In [108]:
df['Genres'].value_counts()

Genres
Tools                          731
Entertainment                  498
Education                      446
Action                         349
Productivity                   334
                              ...
Casual;Music & Video             1
Board;Pretend Play               1
Health & Fitness;Education       1
Music & Audio;Music & Video      1
Strategy;Creativity              1
Name: count, Length: 115, dtype: int64

In [111]:
df_2 = df[(df['last_updated_year'] == 2018) & (df['Category'] == 'BEAUTY')]
df_2

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,last_updated_year
96,Hush - Beauty for Everyone,BEAUTY,Good Rate,18900,17M,< 1000000,Free,0.0,Everyone,Beauty,2018
98,Natural recipes for your beauty,BEAUTY,Good Rate,1150,9.8M,< 1000000,Free,0.0,Everyone,Beauty,2018
99,"BestCam Selfie-selfie, beauty camera, photo ed...",BEAUTY,Good Rate,1739,21M,< 1000000,Free,0.0,Everyone,Beauty,2018
101,Beauty Selfie Camera,BEAUTY,Good Rate,2225,52M,< 1000000,Free,0.0,Everyone,Beauty,2018
102,Hairstyles step by step,BEAUTY,Good Rate,4369,14M,< 1000000,Free,0.0,Everyone,Beauty,2018
103,Filters for Selfie,BEAUTY,Good Rate,8572,25M,>= 1000000,Free,0.0,Everyone,Beauty,2018
104,Tie - Always be happy,BEAUTY,Good Rate,964,9.0M,< 100000,Free,0.0,Everyone,Beauty,2018
105,Ulta Beauty,BEAUTY,Good Rate,42050,Varies with device,>= 1000000,Free,0.0,Everyone,Beauty,2018
106,Prom MakeUp Tutorial,BEAUTY,Good Rate,104,12M,< 100000,Free,0.0,Everyone,Beauty,2018
108,Sweet Selfie Beauty Camera,BEAUTY,Good Rate,601,35M,< 1000000,Free,0.0,Everyone,Beauty,2018
109,Colors of white in Urdu,BEAUTY,Good Rate,36,6.7M,< 100000,Free,0.0,Everyone,Beauty,2018
110,Selfie Camera Photo Editor & Filter & Sticker,BEAUTY,Good Rate,187,30M,< 100000,Free,0.0,Teen,Beauty,2018
111,Eyes Makeup Beauty Tips,BEAUTY,Good Rate,30,2.9M,< 100000,Free,0.0,Everyone,Beauty,2018
112,Photo Editor 2018,BEAUTY,Good Rate,134,17M,< 100000,Free,0.0,Everyone,Beauty,2018
113,Step By Step Eyes Makeup Tutorial,BEAUTY,Good Rate,74,2.9M,< 100000,Free,0.0,Everyone,Beauty,2018
115,Girls Hairstyles,BEAUTY,Good Rate,3595,Varies with device,< 1000000,Free,0.0,Everyone,Beauty,2018
118,Haircut Tutorials/Haircut Videos,BEAUTY,Good Rate,38,7.1M,< 100000,Free,0.0,Everyone,Beauty,2018
119,"Sephora: Skin Care, Beauty Makeup & Fragrance ...",BEAUTY,Good Rate,26834,57M,>= 1000000,Free,0.0,Everyone,Beauty,2018
120,"Sticker Camera - Selfie Filters, Beauty Camera",BEAUTY,Good Rate,2277,22M,< 1000000,Free,0.0,Everyone,Beauty,2018
121,Filters for B Live,BEAUTY,Good Rate,2280,24M,< 1000000,Free,0.0,Everyone,Beauty,2018
122,Facial Wrinkle Reduction,BEAUTY,Good Rate,184,21M,< 100000,Free,0.0,Everyone,Beauty,2018
123,Makeup Videos,BEAUTY,Good Rate,9,3.4M,< 100000,Free,0.0,Everyone,Beauty,2018
124,Discover Color,BEAUTY,Good Rate,364,6.4M,< 1000000,Free,0.0,Everyone,Beauty,2018
125,Eyeliner step by step 2018,BEAUTY,Good Rate,18,3.2M,< 100000,Free,0.0,Everyone,Beauty,2018
127,Step By Step Hairstyles For Women,BEAUTY,Good Rate,66,2.9M,< 100000,Free,0.0,Everyone,Beauty,2018
128,Rainbow Camera,BEAUTY,Good Rate,3871,23M,>= 1000000,Free,0.0,Everyone,Beauty,2018
130,Girls hairstyles 2018,BEAUTY,Good Rate,62,3.1M,< 100000,Free,0.0,Everyone,Beauty,2018
4470,AI Face Beauty Analysis - IntelliFace (Free),BEAUTY,Bad Rate,40,13M,< 100000,Free,0.0,Everyone,Beauty,2018
5334,BH Cosmetics,BEAUTY,Good Rate,2,3.6M,< 100000,Free,0.0,Everyone,Beauty,2018
5544,BN Whitening Shoppe Ph,BEAUTY,Good Rate,2,13M,< 1000,Free,0.0,Everyone,Beauty,2018
5915,Best Hairstyles step by step,BEAUTY,Good Rate,45452,9.2M,>= 1000000,Free,0.0,Everyone,Beauty,2018
8276,Beard Live Camera Photo Editor,BEAUTY,Good Rate,900,30M,< 100000,Free,0.0,Everyone,Beauty,2018
8506,Female Daily,BEAUTY,Good Rate,4354,42M,< 1000000,Free,0.0,Teen,Beauty,2018

In [116]:
df_2['App'].value_counts().head()

App
Hush - Beauty for Everyone                            1
Sephora: Skin Care, Beauty Makeup & Fragrance Shop    1
Beard Live Camera Photo Editor                        1
Best Hairstyles step by step                          1
BN Whitening Shoppe Ph                                1
Name: count, dtype: int64

In [101]:
df['last_updated_year'].unique()

array([2018, 2017, 2014, 2016, 2015, 2013, 2012, 2011, 2010])

In [117]:
df['Content Rating'].value_counts()

Content Rating
Everyone           7087
Teen               1022
Mature 17+          411
Everyone 10+        360
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [99]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,last_updated_year
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,Good Rate,159,19M,< 100000,Free,0.0,Everyone,Art & Design,2018
1,Coloring book moana,ART_AND_DESIGN,Good Rate,967,14M,< 1000000,Free,0.0,Everyone,Art & Design;Pretend Play,2018
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,Good Rate,87510,8.7M,>= 1000000,Free,0.0,Everyone,Art & Design,2018
3,Sketch - Draw & Paint,ART_AND_DESIGN,Good Rate,215644,25M,>= 1000000,Free,0.0,Teen,Art & Design,2018
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,Good Rate,967,2.8M,< 1000000,Free,0.0,Everyone,Art & Design;Creativity,2018

In [57]:
! streamlit run app.py

^C

In [78]:
df.sort_values(by= 'Price', ascending= False)[['App', 'Price']].head(1)

                           App  Price
3746  I'm Rich - Trump Edition  400.0

In [82]:
df.sort_values(by= 'Price', ascending= False)['App'].head(1)

3746    I'm Rich - Trump Edition
Name: App, dtype: object

In [90]:
df[df.Reviews > 50000]['App'].nunique()

1948