# **Pandas**
### Pandas is a python library used for Data Analysis and processing
### Key Features
* Fast and efficient Data Frame object with customized indexing.
* Tools for loading from different file formats.
* Data alignment and integrated handling of missing data.
* Reshaping and pivoting of data sets.
* Label-based slicing, indexing and subsetting of large data sets.
* Columns from a data structure can be deleted or inserted.
* Group by data for aggregation and transformations.
* High performance merging and joining of data.
* Time Series functionality.

In [1]:
# Installation (using conda)
# conda install pandas

# Installation (using pip)
# ! pip install pandas

# import
import pandas as pd

# **Series**
####  A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location.
* A Pandas Series is like a column in a table.
* It is a one-dimensional array holding data of any type.

### 1) Creating a Series

#### Using list

In [2]:
my_list = [10,20,30, 40, 50]
ser1 = pd.Series(my_list)
ser1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
# Using a list with customized index (add parameter index)
ser2 = pd.Series(my_list, index=['a', 'b', 'c', 'd', 'e'])
ser2

a    10
b    20
c    30
d    40
e    50
dtype: int64

#### Using Dictionary

In [4]:
# Using a dictionary (keys will be transformed into Series index and values will be the column values)
my_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
ser3 = pd.Series(my_dict)
ser3

a    10
b    20
c    30
d    40
e    50
dtype: int64

#### Using Numpy Array

In [5]:
# Using a Numpy Array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
ser4 = pd.Series(arr)
ser4

0    10
1    20
2    30
3    40
4    50
dtype: int64

### 2) Access Series Values

#### By Index

In [6]:
print(ser4[0])
print(ser4[1])
print(ser4[2])
print(ser4[3])

10
20
30
40

#### By Slicing

In [7]:
# All values
print(ser4[:])
# Range of values
print(ser4[0:2])
# Values reversed
print(ser4[::-1])

0    10
1    20
2    30
3    40
4    50
dtype: int64
0    10
1    20
dtype: int64
4    50
3    40
2    30
1    20
0    10
dtype: int64

### 3) Series Operations

In [8]:
ser5 = pd.Series(np.arange(1, 11))
ser6 = pd.Series(np.arange(10, 20))
print(ser5)
print(ser6)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

#### Addition

In [9]:
ser5 + ser6

0    11
1    13
2    15
3    17
4    19
5    21
6    23
7    25
8    27
9    29
dtype: int64

#### Subtraction

In [10]:
ser6 - ser5

0    9
1    9
2    9
3    9
4    9
5    9
6    9
7    9
8    9
9    9
dtype: int64

#### Multiplication

In [11]:
ser5 * ser6

0     10
1     22
2     36
3     52
4     70
5     90
6    112
7    136
8    162
9    190
dtype: int64

#### Division

In [12]:
ser6 / ser5

0    10.000000
1     5.500000
2     4.000000
3     3.250000
4     2.800000
5     2.500000
6     2.285714
7     2.125000
8     2.000000
9     1.900000
dtype: float64

### 4) Methods

#### Useful Statistical Methods

In [13]:
ser7 = pd.Series([1, 1, 3, 7, 1, 4, 5, 3, 9, 3])
ser7

0    1
1    1
2    3
3    7
4    1
5    4
6    5
7    3
8    9
9    3
dtype: int64

In [18]:
print('the ser7 is ==>',ser7)
print('*--'*20)
print('the summation of ser7 is ==>',ser7.sum())
print('the mean of ser7 is ==>',ser7.mean())
print('the min of ser7 is ==>',ser7.min())
print('the max of ser7 is ==>',ser7.max())
print('the count of ser7 is ==>',ser7.count())
print('the std of ser7 is ==>',ser7.std())
print('the var of ser7 is ==>',ser7.var())
print('the median of ser7 is ==>',ser7.median())
print('the mode of ser7 is ==>',ser7.mode())

the ser7 is ==> 0    1
1    1
2    3
3    7
4    1
5    4
6    5
7    3
8    9
9    3
dtype: int64
*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--
the summation of ser7 is ==> 37
the mean of ser7 is ==> 3.7
the min of ser7 is ==> 1
the max of ser7 is ==> 9
the count of ser7 is ==> 10
the std of ser7 is ==> 2.6687491868330793
the var of ser7 is ==> 7.122222222222222
the median of ser7 is ==> 3.0
the mode of ser7 is ==> 0    1
1    3
dtype: int64

#### Mode

In [19]:
ser8 = pd.Series(['Egypt', 'USA', 'UK', 'Egypt', 'Egypt', 'Germany', 'UK', 'France', 'UK'])
print(ser8)

0      Egypt
1        USA
2         UK
3      Egypt
4      Egypt
5    Germany
6         UK
7     France
8         UK
dtype: object

In [20]:
# The mode method returns a series of all modes in the data
print(ser8.mode())                                         # Here we have two modes Egypt and UK

0    Egypt
1       UK
dtype: object

In [21]:
# To get the First mode
print(ser8.mode()[0])

Egypt

In [22]:
# To get the Second mode
print(ser8.mode()[1])

UK

# **DataFrame**
* A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a `table` with rows and columns.
* Index represents rows

### 1) Creating DataFrame

#### Using Numpy Array

In [23]:
df1 = pd.DataFrame(np.random.randn(5,4))          # Create a 5 X 4 two dimensional array of random numbers
df1

          0         1         2         3
0 -0.100107 -0.631205 -0.224225 -0.337481
1 -0.221968 -0.582851  1.116012  0.687854
2  0.107106 -1.517042  0.429428  1.362249
3 -1.705459  1.224037 -0.045083 -0.527495
4  0.602641 -0.537096 -1.176391  0.605589

In [24]:
# Using array with customized index (add parameter index)
df2 = pd.DataFrame(np.random.randn(5,4), index=['a', 'b', 'c', 'd', 'e'])
df2

          0         1         2         3
a  0.078723  0.027207 -0.736458 -1.108871
b  2.067245 -0.530424 -0.299259 -0.361614
c -1.247404 -1.000133 -0.611847  0.561217
d  0.779398 -0.719164 -0.063976  3.818303
e  0.552024  1.284582 -0.648515  0.537201

In [25]:
# Using array with customized index (add parameter index) and customized column names (add columns parameter)
df3 = pd.DataFrame(np.random.randn(5,4), index=['a', 'b', 'c', 'd', 'e'], columns=['col1', 'col2', 'col3', 'col4'])
df3

       col1      col2      col3      col4
a -0.115597  0.115701 -2.039815  2.854298
b  0.870665  0.105030  1.584116  0.391377
c -0.037028  0.407972  1.058432  0.748336
d -0.249587  0.649638 -0.809488 -0.751427
e -0.420378 -1.026694 -1.550127  0.902429

#### Using Dictionary

In [26]:
# create dataframe Using Dictionary
my_dict = {'col1': [1, 2, 3, 4, 5], 'col2': [6, 7, 8, 9, 10], 'col3': [11, 12, 13, 14, 15]}
df4 = pd.DataFrame(my_dict)                # Here we don't have to add columns parameter because it takes the column names from dict keys
df4

   col1  col2  col3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

### 2) Select, Create and Drop Columns

#### Select column

In [27]:
# Select column
print(df4['col3'])

0    11
1    12
2    13
3    14
4    15
Name: col3, dtype: int64

In [28]:
# Select a list of columns
print(df4[['col1', 'col2']])

   col1  col2
0     1     6
1     2     7
2     3     8
3     4     9
4     5    10

In [29]:
df4

   col1  col2  col3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

#### Create column

In [30]:
# Create column using list
df4['col4'] = [100, 200, 300, 400, 500]         # The same way as adding a new key-value to a dictionary
df4

   col1  col2  col3  col4
0     1     6    11   100
1     2     7    12   200
2     3     8    13   300
3     4     9    14   400
4     5    10    15   500

In [31]:
# Create column using Numpy Array
df4['col5'] = np.arange(1, 6)
df4

   col1  col2  col3  col4  col5
0     1     6    11   100     1
1     2     7    12   200     2
2     3     8    13   300     3
3     4     9    14   400     4
4     5    10    15   500     5

In [32]:
# Create column using Series
df4['col6'] = pd.Series([10, 20, 30, 40, 50])
df4

   col1  col2  col3  col4  col5  col6
0     1     6    11   100     1    10
1     2     7    12   200     2    20
2     3     8    13   300     3    30
3     4     9    14   400     4    40
4     5    10    15   500     5    50

#### Drop Column

In [33]:
# Drop column from Dataframe (Without UPDATING the variable)
df4.drop('col6', axis = 1)

   col1  col2  col3  col4  col5
0     1     6    11   100     1
1     2     7    12   200     2
2     3     8    13   300     3
3     4     9    14   400     4
4     5    10    15   500     5

In [34]:
# Drop column from Dataframe (With UPDATING the variable, add inplace parameter)
df4.drop('col6', axis = 1, inplace = True)

In [35]:
# Or we can use traditional way to update the variable
df4 = df4.drop('col5', axis = 1)
df4

   col1  col2  col3  col4
0     1     6    11   100
1     2     7    12   200
2     3     8    13   300
3     4     9    14   400
4     5    10    15   500

### 3) Select Create and Drop Rows

#### Select Row

In [36]:
df5 = pd.DataFrame(np.random.randn(5,4), index=['a', 'b', 'c', 'd', 'e'], columns=['col1', 'col2', 'col3', 'col4'])
df5

       col1      col2      col3      col4
a -0.528896  0.270820  0.627516  0.734037
b  0.010334 -0.139778  0.965865 -0.244121
c  0.008464 -0.166443  1.234317  0.372938
d -1.679954  0.359803  0.631825  0.005685
e -1.469959  0.313837  0.782638 -1.587759

In [37]:
# Select row (using iloc method)
df5.iloc[0]                                    # This method needs the index of the row starting from 0

col1   -0.528896
col2    0.270820
col3    0.627516
col4    0.734037
Name: a, dtype: float64

In [38]:
# Select a list of rows (using iloc method)
df5.iloc[0:3]

       col1      col2      col3      col4
a -0.528896  0.270820  0.627516  0.734037
b  0.010334 -0.139778  0.965865 -0.244121
c  0.008464 -0.166443  1.234317  0.372938

In [39]:
# Select specific rows (using iloc method)
df5.iloc[[0, 3]]

       col1      col2      col3      col4
a -0.528896  0.270820  0.627516  0.734037
d -1.679954  0.359803  0.631825  0.005685

In [40]:
# Select row from dataframe (using loc method)
df5.loc['a', 'col1']                                    # This method needs the name of the index

np.float64(-0.5288963619913143)

In [41]:
# Select a list of rows (using loc method)
df5.loc['a':'c']

       col1      col2      col3      col4
a -0.528896  0.270820  0.627516  0.734037
b  0.010334 -0.139778  0.965865 -0.244121
c  0.008464 -0.166443  1.234317  0.372938

In [42]:
# Select specific rows (using loc method)
df5.loc[['a', 'd']]

       col1      col2      col3      col4
a -0.528896  0.270820  0.627516  0.734037
d -1.679954  0.359803  0.631825  0.005685

#### Create Row

In [43]:
# Add a new row with index f
df5.loc['f'] = [1, 2, 3, 4]
df5

       col1      col2      col3      col4
a -0.528896  0.270820  0.627516  0.734037
b  0.010334 -0.139778  0.965865 -0.244121
c  0.008464 -0.166443  1.234317  0.372938
d -1.679954  0.359803  0.631825  0.005685
e -1.469959  0.313837  0.782638 -1.587759
f  1.000000  2.000000  3.000000  4.000000

In [44]:
# Update an existing row
df5.loc['f'] = [100, 200, 300, 400]
df5

         col1        col2        col3        col4
a   -0.528896    0.270820    0.627516    0.734037
b    0.010334   -0.139778    0.965865   -0.244121
c    0.008464   -0.166443    1.234317    0.372938
d   -1.679954    0.359803    0.631825    0.005685
e   -1.469959    0.313837    0.782638   -1.587759
f  100.000000  200.000000  300.000000  400.000000

#### Drop Row

In [45]:
# Drop Row (we use the same method for dropping columns but make axis = 0)
df5.drop('f', axis = 0)

       col1      col2      col3      col4
a -0.528896  0.270820  0.627516  0.734037
b  0.010334 -0.139778  0.965865 -0.244121
c  0.008464 -0.166443  1.234317  0.372938
d -1.679954  0.359803  0.631825  0.005685
e -1.469959  0.313837  0.782638 -1.587759

In [46]:
# To drop the row and UPDATE the variable
df5.drop('f', axis = 0, inplace = True)
df5

       col1      col2      col3      col4
a -0.528896  0.270820  0.627516  0.734037
b  0.010334 -0.139778  0.965865 -0.244121
c  0.008464 -0.166443  1.234317  0.372938
d -1.679954  0.359803  0.631825  0.005685
e -1.469959  0.313837  0.782638 -1.587759

### 4) DataFrame Mask

In [47]:
df6 = pd.DataFrame({'name': ['ahmed', 'mohamed', 'ali', 'ziad', 'yasser'],
                    'salary': [1000, 2000, 3000, 4000, 5000],
                    'age': [20, 25, 30, 35, 40]})
df6

      name  salary  age
0    ahmed    1000   20
1  mohamed    2000   25
2      ali    3000   30
3     ziad    4000   35
4   yasser    5000   40

#### Create Mask

In [49]:
# A mask is any filter applied to the dataframe
mask1 = df6['salary'] > 2000                   # Here we need to get only rows where salary is greater than 2000
mask1                                          # The output is True and False because we used the comparison operator `>`

0    False
1    False
2     True
3     True
4     True
Name: salary, dtype: bool

In [50]:
# To get the values corresponding to True
df6[mask1]

     name  salary  age
2     ali    3000   30
3    ziad    4000   35
4  yasser    5000   40

#### Mask Logical Operators

In [51]:
# To use the logical operator `AND` in the mask we replace it with `&` ( Make sure to put each condition in parenthesis() )
mask2 = (df6['salary'] > 2000) & (df6['age'] > 30)
mask2

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [52]:
df6[mask2]

     name  salary  age
3    ziad    4000   35
4  yasser    5000   40

In [53]:
# To use the logical operator `OR` in the mask we replace it with `|` ( Make sure to put each condition in parenthesis() )
mask3 = (df6['salary'] > 2000) | (df6['age'] > 30)
mask3

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [54]:
df6[mask3]

     name  salary  age
2     ali    3000   30
3    ziad    4000   35
4  yasser    5000   40

In [56]:
# To use the logical operator `NOT` in the maske we replace it with `~` TELDA
mask4 = ~(df6['salary'] > 2000)
mask4

0     True
1     True
2    False
3    False
4    False
Name: salary, dtype: bool

In [57]:
df6[mask4]

      name  salary  age
0    ahmed    1000   20
1  mohamed    2000   25

### 5) Data Input and Output

#### Read CSV

In [ ]:
import pandas as pd
# Note : If the data already has its own index, we add parameter index_col = 0
df7 = pd.read_csv('/content/sample_data/california_housing_train.csv', index_col = 0)
df7

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,,,,,,,,
-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...
-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

#### Write CSV

In [ ]:
# Note : If path not specified, it will save the file in the notebook directory
df7.to_csv('my_file.csv')

#### Read Excel

In [ ]:
# Note : If we need to read a specific sheet, we add parameter sheet_name = 'your_sheet_name'
df8 = pd.read_excel('/content/Excel_Sample.xlsx')
df8

#### Write Excel

In [ ]:
# Write Excel file but save it in a new sheet name
df8.to_excel('my_file.xlsx', sheet_name = 'new_sheet')

### 6) Methods

In [59]:
df6

      name  salary  age
0    ahmed    1000   20
1  mohamed    2000   25
2      ali    3000   30
3     ziad    4000   35
4   yasser    5000   40

#### Statistical Methods

In [60]:
# Statistical methods
print(df6['salary'].sum())
print(df6['salary'].mean())
print(df6['salary'].min())
print(df6['salary'].max())
print(df6['salary'].count())
print(df6['salary'].std())
print(df6['salary'].var())
print(df6['salary'].median())
print(df6['salary'].mode()[0])

15000
3000.0
1000
5000
5
1581.1388300841897
2500000.0
3000.0
1000

#### Most common methods

In [61]:
df7

NameError: name 'df7' is not defined

In [ ]:
# To show only first 5 rows of dataframe
df7.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
# To show a specific number of rows from the begining
df7.head(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0

In [ ]:
# To show only last 5 rows of dataframe
df7.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
# To show a specific number of rows from the end
df7.tail(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
# To get summary statistics for the DataFrame (For numerical columns)
df7.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
# To get summary statistics for the DataFrame (For Categorical columns)
df6.describe(include = 'object')

         name
count       5
unique      5
top     ahmed
freq        1

In [ ]:
# To get unique values in a column
df6['name'].unique()

array(['ahmed', 'mohamed', 'ali', 'ziad', 'yasser'], dtype=object)

In [ ]:
# To get number of unique values in a column
df6['name'].nunique()

5

In [ ]:
# To get the count of each category for categorical column
df6['name'].value_counts()

name
ahmed      1
mohamed    1
ali        1
ziad       1
yasser     1
Name: count, dtype: int64

In [ ]:
# To select columns with specific data type
df6.select_dtypes(include = 'object')

      name
0    ahmed
1  mohamed
2      ali
3     ziad
4   yasser

In [ ]:
# Can also select more than one datatype
df6.select_dtypes(include = ['int', 'object'])

      name  salary  age
0    ahmed    1000   20
1  mohamed    2000   25
2      ali    3000   30
3     ziad    4000   35
4   yasser    5000   40

In [ ]:
# To change data type for column (int, float, object)
df6['salary'] = df6['salary'].astype('float')
df6['salary']

0    1000.0
1    2000.0
2    3000.0
3    4000.0
4    5000.0
Name: salary, dtype: float64

In [67]:
df9 = pd.DataFrame({'date': ['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04', '2022-01-05'],
                   'value': [10, 20, 30, 40, 50],
                   'name': ['ahmed', 'mohamed', 'ali', 'ziad', 'yasser']})
df9

         date  value     name
0  2022-01-01     10    ahmed
1  2022-01-02     20  mohamed
2  2022-01-03     30      ali
3  2022-01-04     40     ziad
4  2022-01-05     50   yasser

In [68]:
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    5 non-null      object
 1   value   5 non-null      int64
 2   name    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes

In [69]:
# To change `date` column data type from object to datetime
df9['date'] = pd.to_datetime(df9['date'])
df9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    5 non-null      datetime64[ns]
 1   value   5 non-null      int64
 2   name    5 non-null      object
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 248.0+ bytes

In [70]:
# To extract year, month, day from date column
df9['year'] = df9['date'].dt.year
df9['month'] = df9['date'].dt.month
df9['day'] = df9['date'].dt.day
df9

        date  value     name  year  month  day
0 2022-01-01     10    ahmed  2022      1    1
1 2022-01-02     20  mohamed  2022      1    2
2 2022-01-03     30      ali  2022      1    3
3 2022-01-04     40     ziad  2022      1    4
4 2022-01-05     50   yasser  2022      1    5

### 7) Functions

In [78]:
df9['salary'] = pd.Series([1000, 2000, 3000, 4000, 5000])
df9

        date  value     name  year  month  day  salary
0 2022-01-01     10    ahmed  2022      1    1    1000
1 2022-01-02     20  mohamed  2022      1    2    2000
2 2022-01-03     30      ali  2022      1    3    3000
3 2022-01-04     40     ziad  2022      1    4    4000
4 2022-01-05     50   yasser  2022      1    5    5000

In [79]:
# Creating a function to apply it on a specific column in dataframe using apply() method
def double(x):
  return x * 2

df9['salary'] = df9['salary'].apply(double)
df9

        date  value     name  year  month  day  salary
0 2022-01-01     10    ahmed  2022      1    1    2000
1 2022-01-02     20  mohamed  2022      1    2    4000
2 2022-01-03     30      ali  2022      1    3    6000
3 2022-01-04     40     ziad  2022      1    4    8000
4 2022-01-05     50   yasser  2022      1    5   10000

In [80]:
# Create same function but using lambda
df9['salary'] = df9['salary'].apply(lambda x: x * 2)
df9

        date  value     name  year  month  day  salary
0 2022-01-01     10    ahmed  2022      1    1    4000
1 2022-01-02     20  mohamed  2022      1    2    8000
2 2022-01-03     30      ali  2022      1    3   12000
3 2022-01-04     40     ziad  2022      1    4   16000
4 2022-01-05     50   yasser  2022      1    5   20000

### 8) EDA (Exploratory Data Analysis Summary)

* 1- Data Loading
* 2- Data Understanding
* 3- Data Exploration
* 4- Data Cleaning
* 5- Data Analysis

In [ ]:
# If dataframe has many columns we can use this method to show all columns and don't hide any of them
pd.set_option('display.max_columns', None)

#### 1- Data Loading

* Reading Data is the first step in your project either data was saved in one file or many files and will be all joined together in one dataframe

In [ ]:
# Loading data
df10 = pd.read_csv('/content/sample_data/california_housing_train.csv')
df10

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

#### 2- Data Understanding

* After loading data, we should make sure we understand what each column or feature represent in this data, otherwise it will be hard to make analysis or machine learning for unknow columns

#### 3- Data Exploration

* In this stage we explore the data by taking an overview about it and overview about the problems in the data

In [ ]:
# 1) Check datatype of each column
df9.info()

# 2) Check Summary statistics of the data
df9.describe()
df9.describe(include = 'object')

# 3) Check duplicates and remove them if found
df9.duplicated().sum()
df9 = df9.drop_duplicates()

# 5) Check missing values
df9.isna().sum()

#### 4- Data Cleaning
##### Data Cleaning varies from data to another and from project to another but it is very important stage for both analysis and machine learning
#####  Data Cleaning may include the following :

* Correcting columns names (for ex removing spaces, make it lowercase)
* Correct column data type
* Drop Unnecessary Columns
* Apply function to fix errors in a column
* Removing Inconsistent values

#### 5- Feature Extraction (Engineering)

* In this stage we try to extract a new column or update existing column to be more useful for analysis or ML

#### 6- Data Analysis

* This stage includes answering analysis questions by using charts, so it's important to be easy to understand and interpret for non-technical and stakholders