# **Pandas**

In [1]:
import pandas as pd
import numpy as np

### Pandas Series

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
ser1 = pd.Series(arr)
ser1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [4]:
type(ser1)

pandas.core.series.Series

In [5]:
my_list = ['ahmed', 'mohamed', 'ali', 'zaki']

ser2 = pd.Series(my_list)
ser2

0      ahmed
1    mohamed
2        ali
3       zaki
dtype: object

In [6]:
my_list = ['ahmed', 'mohamed', 'ali', 'zaki']
my_index = [1, 2, 3, 4]
ser3 = pd.Series(my_list, my_index)
ser3

1      ahmed
2    mohamed
3        ali
4       zaki
dtype: object

In [7]:
ser1 = pd.Series(arr)
ser1 / 10

0    0.0
1    0.1
2    0.2
3    0.3
4    0.4
5    0.5
6    0.6
7    0.7
8    0.8
9    0.9
dtype: float64

In [8]:
np.array([1, 2, 3, 4, 5]) * 10

array([10, 20, 30, 40, 50])

#### Create pandas series from a list
#### create another pandas series from numpy array
#### apply multiplication of the two pandas series

In [9]:
ser1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [10]:
ser4 = pd.Series([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
ser4

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [11]:
ser4 * ser1

0      0
1     20
2     60
3    120
4    200
5    300
6    420
7    560
8    720
9    900
dtype: int64

### Methods

In [12]:
ser4.min()

10

In [13]:
ser4.mean()

np.float64(55.0)

In [14]:
ser4.median()

55.0

In [15]:
ser4.mode()

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [16]:
ser5 = pd.Series(['ahmed', 'ahmed', 'ahmed', 'mohamed', 'ali', 'fawzy', 'mostafa'])
ser5

0      ahmed
1      ahmed
2      ahmed
3    mohamed
4        ali
5      fawzy
6    mostafa
dtype: object

In [17]:
ser5.mode()[0]

'ahmed'

In [18]:
ser4.std()

30.276503540974915

In [19]:
ser5

0      ahmed
1      ahmed
2      ahmed
3    mohamed
4        ali
5      fawzy
6    mostafa
dtype: object

In [20]:
ser5[1:5]

1      ahmed
2      ahmed
3    mohamed
4        ali
dtype: object

### Dataframe

In [21]:
arr2 = np.random.randn(4, 5)
arr2

array([[-0.49770782,  2.44639281, -0.91585799, -0.51999751,  1.17831648],
       [ 0.5914213 ,  1.45458692,  0.38179421,  0.101925  ,  0.23618414],
       [-1.03639913,  0.62817108,  0.26945831,  0.35982086, -0.30153091],
       [ 0.75525537,  2.17081635, -0.3107649 , -1.29385003, -1.05371211]])

In [22]:
df1 = pd.DataFrame(arr2, index= [1, 2, 3, 4], columns= ['col1', 'col2', 'col3', 'col4', 'col5'])
df1

       col1      col2      col3      col4      col5
1 -0.497708  2.446393 -0.915858 -0.519998  1.178316
2  0.591421  1.454587  0.381794  0.101925  0.236184
3 -1.036399  0.628171  0.269458  0.359821 -0.301531
4  0.755255  2.170816 -0.310765 -1.293850 -1.053712

In [23]:
my_dict = {'name' : ['ahmed', 'mohamed', 'ali', 'zaki', 'fawzy'],
           'salary' : [1000, 2000, 3000, 4000, 5000],
           'age' : [20, 25, 27, 30, 35]}
my_dict

{'name': ['ahmed', 'mohamed', 'ali', 'zaki', 'fawzy'],
 'salary': [1000, 2000, 3000, 4000, 5000],
 'age': [20, 25, 27, 30, 35]}

In [24]:
df2 = pd.DataFrame(my_dict)
df2

      name  salary  age
0    ahmed    1000   20
1  mohamed    2000   25
2      ali    3000   27
3     zaki    4000   30
4    fawzy    5000   35

In [25]:
df = pd.read_csv('Salary_Data.csv', index_col= 0)
df

    YearsExperience  Salary
id
1               1.1   39343
2               1.3   46205
3               1.5   37731
4               2.0   43525
5               2.2   39891
6               2.9   56642
7               3.0   60150
8               3.2   54445
9               3.2   64445
10              3.7   57189
11              3.9   63218
12              4.0   55794
13              4.0   56957
14              4.1   57081
15              4.5   61111
16              4.9   67938
17              5.1   66029
18              5.3   83088
19              5.9   81363
20              6.0   93940
21              6.8   91738
22              7.1   98273
23              7.9  101302
24              8.2  113812
25              8.7  109431
26              9.0  105582
27              9.5  116969
28              9.6  112635
29             10.3  122391
30             10.5  121872

In [26]:
df[0:5]

    YearsExperience  Salary
id
1               1.1   39343
2               1.3   46205
3               1.5   37731
4               2.0   43525
5               2.2   39891

In [27]:
df.iloc[3, 1]

np.int64(43525)

In [28]:
df.loc[4, 'Salary']

np.int64(43525)

In [30]:
df.head(7)

    YearsExperience  Salary
id
1               1.1   39343
2               1.3   46205
3               1.5   37731
4               2.0   43525
5               2.2   39891
6               2.9   56642
7               3.0   60150

In [31]:
df.tail(7)

    YearsExperience  Salary
id
24              8.2  113812
25              8.7  109431
26              9.0  105582
27              9.5  116969
28              9.6  112635
29             10.3  122391
30             10.5  121872

In [32]:
df.drop([1, 2, 3, 4, 5], axis=0, inplace= True)

In [33]:
df

    YearsExperience  Salary
id
6               2.9   56642
7               3.0   60150
8               3.2   54445
9               3.2   64445
10              3.7   57189
11              3.9   63218
12              4.0   55794
13              4.0   56957
14              4.1   57081
15              4.5   61111
16              4.9   67938
17              5.1   66029
18              5.3   83088
19              5.9   81363
20              6.0   93940
21              6.8   91738
22              7.1   98273
23              7.9  101302
24              8.2  113812
25              8.7  109431
26              9.0  105582
27              9.5  116969
28              9.6  112635
29             10.3  122391
30             10.5  121872

In [34]:
df = df.drop(['Salary', 'Age'], axis= 1)
df

KeyError: "['Age'] not found in axis"

In [ ]:
df

    YearsExperience  Salary
id
1               1.1   39343
2               1.3   46205
3               1.5   37731
4               2.0   43525
5               2.2   39891
6               2.9   56642
7               3.0   60150
8               3.2   54445
9               3.2   64445
10              3.7   57189
11              3.9   63218
12              4.0   55794
13              4.0   56957
14              4.1   57081
15              4.5   61111
16              4.9   67938
17              5.1   66029
18              5.3   83088
19              5.9   81363
20              6.0   93940
21              6.8   91738
22              7.1   98273
23              7.9  101302
24              8.2  113812
25              8.7  109431
26              9.0  105582
27              9.5  116969
28              9.6  112635
29             10.3  122391
30             10.5  121872

In [ ]:
df

    YearsExperience
id
2               1.3
3               1.5
4               2.0
5               2.2
6               2.9
7               3.0
8               3.2
9               3.2
10              3.7
11              3.9
12              4.0
13              4.0
14              4.1
15              4.5
16              4.9
17              5.1
18              5.3
19              5.9
20              6.0
21              6.8
22              7.1
23              7.9
24              8.2
25              8.7
26              9.0
27              9.5
28              9.6
29             10.3
30             10.5

In [ ]:
df

    YearsExperience  Salary
id
1               1.1   39343
2               1.3   46205
3               1.5   37731
4               2.0   43525
5               2.2   39891
6               2.9   56642
7               3.0   60150
8               3.2   54445
9               3.2   64445
10              3.7   57189
11              3.9   63218
12              4.0   55794
13              4.0   56957
14              4.1   57081
15              4.5   61111
16              4.9   67938
17              5.1   66029
18              5.3   83088
19              5.9   81363
20              6.0   93940
21              6.8   91738
22              7.1   98273
23              7.9  101302
24              8.2  113812
25              8.7  109431
26              9.0  105582
27              9.5  116969
28              9.6  112635
29             10.3  122391
30             10.5  121872

In [36]:
df['Age'] = np.arange(25, 50)

In [37]:
df

    YearsExperience  Salary  Age
id
6               2.9   56642   25
7               3.0   60150   26
8               3.2   54445   27
9               3.2   64445   28
10              3.7   57189   29
11              3.9   63218   30
12              4.0   55794   31
13              4.0   56957   32
14              4.1   57081   33
15              4.5   61111   34
16              4.9   67938   35
17              5.1   66029   36
18              5.3   83088   37
19              5.9   81363   38
20              6.0   93940   39
21              6.8   91738   40
22              7.1   98273   41
23              7.9  101302   42
24              8.2  113812   43
25              8.7  109431   44
26              9.0  105582   45
27              9.5  116969   46
28              9.6  112635   47
29             10.3  122391   48
30             10.5  121872   49

In [38]:
df['Salary']

id
6      56642
7      60150
8      54445
9      64445
10     57189
11     63218
12     55794
13     56957
14     57081
15     61111
16     67938
17     66029
18     83088
19     81363
20     93940
21     91738
22     98273
23    101302
24    113812
25    109431
26    105582
27    116969
28    112635
29    122391
30    121872
Name: Salary, dtype: int64

In [39]:
type(df['Salary'])

pandas.core.series.Series

In [41]:
df.to_csv('Salary_Data_updated2.csv')

- Read csv file
- Add new column
- drop one row from data
- drop one column from data

In [42]:
d = {'name' : 'ali', 'salary' : 5000}
d

{'name': 'ali', 'salary': 5000}

In [43]:
d['age'] = 27

In [44]:
d

{'name': 'ali', 'salary': 5000, 'age': 27}

In [45]:
df[~(df['YearsExperience'] != 3)]

    YearsExperience  Salary  Age
id
7               3.0   60150   26

In [126]:
df2 = pd.read_excel('Excel_Sample.xlsx', sheet_name= 'Sheet2', index_col= 0)
df2

   col1  col2  col3  col4
0   100     1     2     3
1   200     5     6     7
2   300     9    10    11
3   400    13    14    15

In [46]:
df.to_excel('Excel_Sample.xlsx', sheet_name= 'Sheet2')

ModuleNotFoundError: No module named 'openpyxl'

In [137]:
df.drop('Gender', axis= 1, inplace= True)

In [138]:
df['Gender'] = (['Male'] * 25) + (['Female'] * 5)
df

    YearsExperience  Salary  Gender
id
1               1.1   39343    Male
2               1.3   46205    Male
3               1.5   37731    Male
4               2.0   43525    Male
5               2.2   39891    Male
6               2.9   56642    Male
7               3.0   60150    Male
8               3.2   54445    Male
9               3.2   64445    Male
10              3.7   57189    Male
11              3.9   63218    Male
12              4.0   55794    Male
13              4.0   56957    Male
14              4.1   57081    Male
15              4.5   61111    Male
16              4.9   67938    Male
17              5.1   66029    Male
18              5.3   83088    Male
19              5.9   81363    Male
20              6.0   93940    Male
21              6.8   91738    Male
22              7.1   98273    Male
23              7.9  101302    Male
24              8.2  113812    Male
25              8.7  109431    Male
26              9.0  105582  Female
27              9.5  116969  Female
28              9.6  112635  Female
29             10.3  122391  Female
30             10.5  121872  Female

In [135]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [140]:
df.describe(include= 'O')

       Gender
count      30
unique      2
top      Male
freq       25

In [142]:
df['Gender'].nunique()

2

In [143]:
df['Gender'].value_counts()

Gender
Male      25
Female     5
Name: count, dtype: int64

- Read CSV file
- Check summary statistics from numerical columns
- Check if there are any outliers
- Check the count of each region

In [50]:
df = pd.read_csv('insurance (1) (1).csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [51]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [52]:
df.describe(include= 'object')

         sex smoker     region
count   1338   1338       1338
unique     2      2          4
top     male     no  southeast
freq     676   1064        364

In [53]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64