In [1]:
import numpy as np
import pandas as pd
import streamlit as st
import plotly.express as px

In [ ]:
import pandas as pd

df = pd.read_csv('melb_data.csv')
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [3]:
df.select_dtypes(include= 'number')

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
0,2,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,-37.79960,144.99840,4019.0
1,2,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,-37.80790,144.99340,4019.0
2,3,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,-37.80930,144.99440,4019.0
3,3,850000.0,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,-37.79690,144.99690,4019.0
4,4,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,-37.80720,144.99410,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,4,1245000.0,16.7,3150.0,4.0,2.0,2.0,652.0,NaN,1981.0,-37.90562,145.16761,7392.0
13576,3,1031000.0,6.8,3016.0,3.0,2.0,2.0,333.0,133.0,1995.0,-37.85927,144.87904,6380.0
13577,3,1170000.0,6.8,3016.0,3.0,2.0,4.0,436.0,NaN,1997.0,-37.85274,144.88738,6380.0
13578,4,2500000.0,6.8,3016.0,4.0,1.0,5.0,866.0,157.0,1920.0,-37.85908,144.89299,6380.0
13579,4,1285000.0,6.3,3013.0,4.0,1.0,1.0,362.0,112.0,1920.0,-37.81188,144.88449,6543.0

In [ ]:
from sklearn.impute import KNNImputer, SimpleImputer
# the logic of the KNNImputer is to fill the missing values with the mean of the k nearest neighbors
# n_neighbors is the number of neighbors to consider for filling the missing values
# n_neighbors=5 means that the mean of the 5 nearest neighbors will be used to fill the missing values 

knn = KNNImputer(n_neighbors= 5)

df['BuildingArea'] = knn.fit_transform(df[['BuildingArea']])
df['BuildingArea']

0        151.96765
1         79.00000
2        150.00000
3        151.96765
4        142.00000
           ...
13575    151.96765
13576    133.00000
13577    151.96765
13578    157.00000
13579    112.00000
Name: BuildingArea, Length: 13580, dtype: float64

In [7]:
# The SimpleImputer is used to fill the missing values with a constant value or the mean/median of the column
# as u see i first creat an instance of the SimpleImputer class
sim_impu = SimpleImputer(strategy= 'median')

df[['Car', 'YearBuilt']] = sim_impu.fit_transform(df[['Car', 'YearBuilt']])

In [8]:
df[['Car', 'YearBuilt']]

       Car  YearBuilt
0      1.0     1970.0
1      0.0     1900.0
2      0.0     1900.0
3      1.0     1970.0
4      2.0     2014.0
...    ...        ...
13575  2.0     1981.0
13576  2.0     1995.0
13577  4.0     1997.0
13578  5.0     1920.0
13579  1.0     1920.0

[13580 rows x 2 columns]

In [9]:
df.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [10]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,151.96765,1970.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.00000,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.00000,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,151.96765,1970.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.00000,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [ ]:
df.BuildingArea

0        151.96765
1         79.00000
2        150.00000
3        151.96765
4        142.00000
           ...
13575    151.96765
13576    133.00000
13577    151.96765
13578    157.00000
13579    112.00000
Name: BuildingArea, Length: 13580, dtype: float64

In [ ]:
# i will drop the columns that are not useful for the analysis

df_cat = df.select_dtypes(include= 'object').drop(['Suburb', 'Address', 'SellerG', 'Date', 'CouncilArea'], axis= 1)
df_cat

      Type Method                  Regionname
0        h      S       Northern Metropolitan
1        h      S       Northern Metropolitan
2        h     SP       Northern Metropolitan
3        h     PI       Northern Metropolitan
4        h     VB       Northern Metropolitan
...    ...    ...                         ...
13575    h      S  South-Eastern Metropolitan
13576    h     SP        Western Metropolitan
13577    h      S        Western Metropolitan
13578    h     PI        Western Metropolitan
13579    h     SP        Western Metropolitan

[13580 rows x 3 columns]

In [14]:
df.Type.value_counts()

Type
h    9449
u    3017
t    1114
Name: count, dtype: int64

In [15]:
df.Type.unique()

array(['h', 'u', 't'], dtype=object)

In [16]:
from sklearn.preprocessing import OrdinalEncoder

ord = OrdinalEncoder(categories= [['u', 't', 'h']])

df_cat['Type'] = ord.fit_transform(df_cat[['Type']])
df_cat['Type']

0        2.0
1        2.0
2        2.0
3        2.0
4        2.0
        ...
13575    2.0
13576    2.0
13577    2.0
13578    2.0
13579    2.0
Name: Type, Length: 13580, dtype: float64

In [17]:
df_cat.Type.value_counts()

Type
2.0    9449
0.0    3017
1.0    1114
Name: count, dtype: int64

### Another Method

In [18]:
type_dict = {
    'u' : 0,
    't' : 1,
    'h' : 2
}
df['Type'] = df.Type.map(type_dict)
df['Type']

0        2
1        2
2        2
3        2
4        2
        ..
13575    2
13576    2
13577    2
13578    2
13579    2
Name: Type, Length: 13580, dtype: int64

In [19]:
df.Type.value_counts()

Type
2    9449
0    3017
1    1114
Name: count, dtype: int64

In [20]:
df_cat

       Type Method                  Regionname
0       2.0      S       Northern Metropolitan
1       2.0      S       Northern Metropolitan
2       2.0     SP       Northern Metropolitan
3       2.0     PI       Northern Metropolitan
4       2.0     VB       Northern Metropolitan
...     ...    ...                         ...
13575   2.0      S  South-Eastern Metropolitan
13576   2.0     SP        Western Metropolitan
13577   2.0      S        Western Metropolitan
13578   2.0     PI        Western Metropolitan
13579   2.0     SP        Western Metropolitan

[13580 rows x 3 columns]

In [21]:
df_cat.Method.value_counts()

Method
S     9022
SP    1703
PI    1564
VB    1199
SA      92
Name: count, dtype: int64

In [22]:
df_cat.Regionname.value_counts()

Regionname
Southern Metropolitan         4695
Northern Metropolitan         3890
Western Metropolitan          2948
Eastern Metropolitan          1471
South-Eastern Metropolitan     450
Eastern Victoria                53
Northern Victoria               41
Western Victoria                32
Name: count, dtype: int64

In [23]:
df_cat.Method

0         S
1         S
2        SP
3        PI
4        VB
         ..
13575     S
13576    SP
13577     S
13578    PI
13579    SP
Name: Method, Length: 13580, dtype: object

In [ ]:
import pandas as pd

# Using pd.get_dummies to convert categorical variable into dummy/indicator variables

pd.get_dummies(df_cat, columns= ['Method'], drop_first= True)

,Type,Regionname,Method_S,Method_SA,Method_SP,Method_VB
0,2.0,Northern Metropolitan,True,False,False,False
1,2.0,Northern Metropolitan,True,False,False,False
2,2.0,Northern Metropolitan,False,False,True,False
3,2.0,Northern Metropolitan,False,False,False,False
4,2.0,Northern Metropolitan,False,False,False,True
...,...,...,...,...,...,...
13575,2.0,South-Eastern Metropolitan,True,False,False,False
13576,2.0,Western Metropolitan,False,False,True,False
13577,2.0,Western Metropolitan,True,False,False,False
13578,2.0,Western Metropolitan,False,False,False,False
13579,2.0,Western Metropolitan,False,False,True,False

In [25]:
df_cat

       Type Method                  Regionname
0       2.0      S       Northern Metropolitan
1       2.0      S       Northern Metropolitan
2       2.0     SP       Northern Metropolitan
3       2.0     PI       Northern Metropolitan
4       2.0     VB       Northern Metropolitan
...     ...    ...                         ...
13575   2.0      S  South-Eastern Metropolitan
13576   2.0     SP        Western Metropolitan
13577   2.0      S        Western Metropolitan
13578   2.0     PI        Western Metropolitan
13579   2.0     SP        Western Metropolitan

[13580 rows x 3 columns]

In [26]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop= 'first', sparse_output= False)

ohe_arr = ohe.fit_transform(df_cat[['Method']])
ohe_arr

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       ...,
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
# to add the column names to the one-hot encoded array
df_ohe =  pd.DataFrame(ohe_arr, columns= ohe.get_feature_names_out())
df_ohe

       Method_S  Method_SA  Method_SP  Method_VB
0           1.0        0.0        0.0        0.0
1           1.0        0.0        0.0        0.0
2           0.0        0.0        1.0        0.0
3           0.0        0.0        0.0        0.0
4           0.0        0.0        0.0        1.0
...         ...        ...        ...        ...
13575       1.0        0.0        0.0        0.0
13576       0.0        0.0        1.0        0.0
13577       1.0        0.0        0.0        0.0
13578       0.0        0.0        0.0        0.0
13579       0.0        0.0        1.0        0.0

[13580 rows x 4 columns]

In [28]:
df_cat = pd.concat([df_cat, df_ohe], axis= 1).drop('Method', axis= 1)
df_cat

,Type,Regionname,Method_S,Method_SA,Method_SP,Method_VB
0,2.0,Northern Metropolitan,1.0,0.0,0.0,0.0
1,2.0,Northern Metropolitan,1.0,0.0,0.0,0.0
2,2.0,Northern Metropolitan,0.0,0.0,1.0,0.0
3,2.0,Northern Metropolitan,0.0,0.0,0.0,0.0
4,2.0,Northern Metropolitan,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...
13575,2.0,South-Eastern Metropolitan,1.0,0.0,0.0,0.0
13576,2.0,Western Metropolitan,0.0,0.0,1.0,0.0
13577,2.0,Western Metropolitan,1.0,0.0,0.0,0.0
13578,2.0,Western Metropolitan,0.0,0.0,0.0,0.0
13579,2.0,Western Metropolitan,0.0,0.0,1.0,0.0

In [29]:
df.Regionname.nunique()

8

In [26]:
# ! pip install category_encoders

In [ ]:
from category_encoders import BinaryEncoder

be = BinaryEncoder()

be.fit_transform(df_cat[['Regionname']])